mampfes/hacs_waste_collection_schedule

- README.md
Added an example how to use [Garbage Collection Card](https://github.com/bruxy70/Garbage-Collection). Using this custom lovelace card requires less yaml code, which reduces complexity. In addition, the required yaml code is more legible, which reduces room for error and helps new users to understand what's going on.
> doc: add example for garbage colleciton card

- doc/source/ics.md
The ics import also works for Entsorgungsgesellschaft Görlitz-Löbau-Zittau.
Thanks for this useful home assistant integration :)
> Add note for EGLZ

- custom_components/waste_collection_schedule/sensor.py
The unique_id property allows users to configure and manage entities in the Home Assistant UI. So, this PR accomplishes that, and thus fixes the warning: "This entity does not have a unique ID, therefore its settings cannot be managed from the UI."
> Add unique_id property to enable configuration via UI

- doc/source/ics.md
Add Awista Starnberg (Abfallwirtschaft Starnberg KU).
Running the ICS download with Awista Starnberg for over a year now, checked explicitly for the new year, all worked without any problem!
> Add Awista Starnberg

- README.md
- custom_components/waste_collection_schedule/waste_collection_schedule/wizard/jumomind_de.py
- doc/source/jumomind_de.md
I found out that you can also use the data of the mymuell.de App with the junomind source.
to get the needed city and area id i have modified the jumomind_de.py script to use it with mymuell
during my testing i got some cities which does not deliver street-data. The script will now quit with a message if you are using mymuell and answer of the "street-data" request is empty.
> Using MyMuell with jumomind sources

- .gitignore
- custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py
- custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py
- doc/source/ics.md
I want to use a garbage service that is only accessible with POST parameters.  
So I added a new attribute in yaml to choose whether to use GET or POST.  GET is the default so there are no adaptions needed for other services.  
Additionally there is bit more debug logging when using in hass.
> Add attribute to choose GET or POST for ICS parameters

- custom_components/waste_collection_schedule/waste_collection_schedule/source/seattle_gov.py
The current APIs that are used for seattle retrieve incorrect data reported in issue [50](https://github.com/mampfes/hacs_waste_collection_schedule/issues/50)
This change mimicks what the actual seattle garbage collection calendar page does. Code might not be perfect, but works. The test now actually retrieve 3 entries for each of the test case, the previous implementation only returned 3 entries for 1 of the 3 tests.
> Update seattle source to use correct APIs

- README.md
- custom_components/waste_collection_schedule/waste_collection_schedule/source/hvcgroep_nl.py
- doc/source/hvcgroep_nl.md
- info.md
This will add waste management from the Dutch HVCGroep ([hvcgroep.nl](https://www.hvcgroep.nl/).) 
In case you want to validate the results, they can be manually seen at https://www.hvcgroep.nl/zelf-regelen/afvalkalender
> Add HVCGroep waste management

- custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py
Errors when parsing an ICS file are not reported to log. 
This patch adds a message to the error log.
> Write error log.

- custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py
- custom_components/waste_collection_schedule/waste_collection_schedule/test/test_sources.py
- custom_components/waste_collection_schedule/waste_collection_schedule/wizard/abfall_io.py
- custom_components/waste_collection_schedule/waste_collection_schedule/wizard/abfall_kreis_tuebingen_de.py
- custom_components/waste_collection_schedule/waste_collection_schedule/wizard/abfallnavi_de.py
- custom_components/waste_collection_schedule/waste_collection_schedule/wizard/awbkoeln_de.py
- custom_components/waste_collection_schedule/waste_collection_schedule/wizard/bsr_de.py
- custom_components/waste_collection_schedule/waste_collection_schedule/wizard/jumomind_de.py
- custom_components/waste_collection_schedule/waste_collection_schedule/wizard/muellmax_de.py
- custom_components/waste_collection_schedule/waste_collection_schedule/wizard/stadtreinigung_hamburg.py
- custom_components/waste_collection_schedule/waste_collection_schedule/wizard/stuttgart_de.py
To run this script in a virtual environment (venv), the shebang line needs to invoke /usr/bin/env instead of /usr/bin/python3 to make sure the python3 version from the venv (including its modules) is executed.
> Change shebang line to respect venvs

- custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py
The ICS split feature is a great idea, but for maximum functionality, it should use a regular expression based split string instead of a plain delimiter.
My garbage has summary lines as follows:
```SUMMARY:Garbage\, green bin\, yard trimmings\, and blue bin
SUMMARY:Yard trimmings\, green bin\, and black bin
SUMMARY:Garbage\, green bin\, yard trimmings\, and blue bin
SUMMARY:Black bin\, yard trimmings\, and green bin
SUMMARY:Garbage\, blue bin\, green bin\, and yard trimmings
SUMMARY:Black bin\, green bin\, and yard trimmings
SUMMARY:Garbage\, blue bin\, yard trimmings\, and green bin
SUMMARY:Black bin\, green bin\, and yard trimmings
SUMMARY:Garbage\, green bin\, yard trimmings\, and blue bin
SUMMARY:Green bin\, yard trimmings\, and black bin
SUMMARY:Garbage\, blue bin\, green bin\, and …
```
> Change ICS split_at to use regex, and make casing uniform.

- custom_components/waste_collection_schedule/waste_collection_schedule/source/seattle_gov.py
- doc/source/seattle_gov.md
Adds support for manually specifying a `prem_code` in the configuration for the seattle_gov source, as automatic lookup can struggle with multi-tenant addresses sometimes (as can the city collection calendar website).
Documentation was updated to mention how to look this up manually, a test case with a manually specified prem_code was added and test_sources passed.
> Add support for directly specifying prem_code for seattle_gov 

- custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py
When trying to prefetch the next year the component crashed when no
year_field was provided.
Additionally there was a syntax error in the fetching of next years ics.
> fix problem in ics source

- .pre-commit-config.yaml
When developing #142 I wanted to execute `pre-commit` on Python 3.9.9, but was unable to do so, as `requests` was missing in the pre-commit venv.
I got the following error message:
```bash
custom_components/waste_collection_schedule/waste_collection_schedule/source/wuerzburg_de.py:3: error:
Library stubs not installed for "requests" (or incompatible with Python 3.9) 
[import]
import requests
^
custom_components/waste_collection_schedule/waste_collection_schedule/source/wuerzburg_de.py:3: note: Hint: "python3 -m pip install types-requests"
custom_components/waste_collection_schedule/waste_collection_schedule/source/wuerzburg_de.py:3: note: (or run "mypy --install-types" to install all missing stub packages)
custom_components/waste_collection_schedule/waste_collection_schedule/source/wuerzbu …
```
> Add types-requests to mypy pre-commit

- custom_components/waste_collection_schedule/waste_collection_schedule/source/abfall_io.py
- custom_components/waste_collection_schedule/waste_collection_schedule/wizard/abfall_io.py
Thanks for writing this integration! Here's a PR that adds my hometown (Ludwigshafen am Rhein).
Also added to wizard, one small detail I noticed is that the wizard terminates after querying `f_id_kommune` and `f_id_strasse`. Using only those parameters works, however it results in less events returned (164) compared to when `f_id_strasse_hnr` is added to the query as well (198). 
Bests,
Florian
Signed-off-by: Florian Heilmann <Florian.Heilmann@gmx.net>
> add Ludwigshafen am Rhein to abfall.io

- README.md
- custom_components/waste_collection_schedule/waste_collection_schedule/source/wuerzburg_de.py
- doc/source/wuerzburg_de.md
- info.md
Adds waste collection for the city of Würzburg.
I know that `days` will be requiring a discussion: I have to call the API with both `ev[start]` and `ev[end]` dates.
Without them, nothing is returned. With just the start date, only event for this day are returned.
The API by default used approx. 1 year to look into the future.
I could also remove the parameter completely and hard-code the +1 year time interval.
> Add wuerzburg_de

- README.md
- custom_components/waste_collection_schedule/waste_collection_schedule/source/kwb_goslar_de.py
- doc/source/kwb_goslar_de.md
Adds support for [KWB-Goslar.de](https://www.kwb-goslar.de/Abfallwirtschaft/Abfuhr/Online-Abfuhrkalender-2022/) (Bad Harzburg, Braunlage, Clausthal-Zellerfeld, Goslar, Langelsheim, Liebenburg, Lutter am Barenberge, Oker, Seesen, Seesen, Vienenburg).
> Add support for KWB-Goslar.de

- doc/source/ics.md
Params are in all cases urlencoded and passed to either the URL or HTTP body with additional headers. This documentation change now reflects this to avoid confustion if the configuration needs to be urlencoded or not. 
This should help removing confusion like happend in https://github.com/mampfes/hacs_waste_collection_schedule/issues/153
> Clarify that params are urlencoded

- README.md
- custom_components/waste_collection_schedule/waste_collection_schedule/source/banyule_vic_gov_au.py
- doc/source/banyule_vic_gov_au.md
- info.md
Adds a source for Banyule City Council, covering an area of North-East Melbourne, Australia.
Based quite heavily upon the implementation for Stonnington Council in #101; they use almost identical mechanisms for fetching upcoming dates. Only major change is a mechanism to bypass one of the lookups.
> Added source for banyule.vic.gov.au

- custom_components/waste_collection_schedule/waste_collection_schedule/source/stonnington_vic_gov_au.py
When the hard waste schedule isn't published yet, skip the entry instead of breaking on date parsing.
Scenario:
> Stonnington: Tighter validation during scraping

- README.md
- custom_components/waste_collection_schedule/waste_collection_schedule/source/mrsc_vic_gov_au.py
- doc/source/mrsc_vic_gov_au.md
- info.md
Fixes #159 
This new provider is based on the [existing provider for Stonnington City Council](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/stonnington_vic_gov_au.py) as it looks like both councils are using the same publishing software, albeit with their own instances deployed.
> add source for mrsc.vic.gov.au

- custom_components/waste_collection_schedule/waste_collection_schedule/source/data_umweltprofis_at.py
- doc/source/data_umweltprofis_at.md
As mentioned in #167, the ICS file provided by data.umweltprofis.at needs a fix-up in order to be parsed correctly.
> Add support for fetching data from umweltprofis.at

- custom_components/waste_collection_schedule/waste_collection_schedule/source/berlin_recycling_de.py
Berlin Recycling is currently broken and fails with an SSLCertVerificationError:
Seems the reason is https://kundenportal.berlin-recycling.de has a misconfigured HTTPS server which is not sending the intermediate certificate (Starfield Secure Certificate Authority - G2). Unlike browsers, python does not support automatic fetching of missing intermediates.
fix #186
> skip ssl check for berlin_recycling_de

- custom_components/waste_collection_schedule/waste_collection_schedule/wizard/abfall_io.py
Added Ortenaukreis to abfall_io wizard.
Tested and working.
> add Ortenaukreis to abfall_io wizard

- custom_components/waste_collection_schedule/waste_collection_schedule/source/banyule_vic_gov_au.py
The source I created accidentally passed datetime objects to the Collection constructor instead of Date objects. A quick fix for that.
While I wrote the source a while ago I didn't actually use it until recently. It "passed" ```test_sources.py``` since it quite happily dumps datetimes as strings 🙃
> Fix Source banyule_vic_gov_au

- README.md
- doc/source/ics.md
I was looking everywhere to see my local waste collection in HA, thanks to your ICal variant I can give support for "Gemeinde Zorneding" and confirm its working.
Also to decrease searching for new users if their collection is supported via ICS/iCal I recommend adding a short list about all ICS/Ical supported variants on the main readme (done with this pull request).
Thank you for your great addon!
> Add new ICS source Gemeinde Zorneding

- custom_components/waste_collection_schedule/waste_collection_schedule/source/wuerzburg_de.py
Fixes for `wuerzburg_de`:
- New URL
- HTML `SELECT`s now may contain line breaks, which the dict comprehension didn't like. Now checking for existence before accessing it in the dict comprehension.
> Fix wuerzburg_de

- custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py
During development of #289, I noticed that the `ICS` class currently has no type annotations. I made the following changes:
- To make it easier in the future to create new ICS-based sources, I added the correct types to the class.
- As a result of this, I was warned by VSCode that the value `dtstart` may be None. Thus, I added corresponding checks and made sure that only entries with a valid start date are returned by the `convert` function.
- I replaced the conditions of `type(e.start)` with corresponding `isinstance(e.start, ...)` calls to enable type inference in modern IDEs. Due to that, I had to change the order of the conditions because `datetime.datetime` inherits from `datetime.date`.
- `split_at` and `regex` were handled differently despite both representing a regular expression …
> Add types to ICS parser and check for None values

- README.md
- custom_components/waste_collection_schedule/waste_collection_schedule/source/static.py
- doc/source/static.md
The static source allows to define static dates or a recurrence.
This is useful if the service provider does not offer an API, nor an ICS file.
It can also simplify the testing of automations by, for example, configuring a daily recurrence.
> Added static source

- custom_components/waste_collection_schedule/waste_collection_schedule/source/republicservices_com.py
Was showing Recycling for Yard Waste because the 'wasteTypeDescription' is set to 'Recycle' for both types in the data. Used 'containerType' to identify Yard Waste.
Snip of Example Data:
``` 
"containerId": "41357515",
"containerType": "YC",
"containerSize": "0.30",
"containerStatus": "Open",
"containerCategory": "Residential",
"customerOwnedInd": false,
"productDescription": "YARD WASTE CART 60 GAL",
"onCallInd": false,
"serviceStartDate": "2019-03-16",
"serviceChangeLastDate": "2019-03-16",
"quantityOnSite": 1,
"quantityOrdered": 1,
"wasteTypeDescription": "Recycle",
```
> Update RepublicServices.com with Yard Waste Marker

- README.md
Typo in the link for `republicservices_com.md`
> Fix Republic Services md link

- README.md
- custom_components/waste_collection_schedule/waste_collection_schedule/source/miljoteknik_se.py
- doc/source/miljoteknik_se.md
- info.md
Hi,
Adding my local provider Ronneby Miljöteknik mainly for my own purposes. The "API" is the form behind their calendar service here: http://www.fyrfackronneby.se/hamtningskalender/
Unfortunately they only provide this service for residential houses, it's not available for apartment buildings, city services offices or similar. This means there's no good testing addresses, I've included my own address as the sole test case but I wonder what the best approach is here? I mean there's gotta be a testing address, but it does constitute personal data which you may not want in the repository, and should I ever move it becomes a bigger issue.
Please also note if there's anything code-wise or docs-wise I need to change as this is my first contribution to this repository and I'm also fairly new to …
> Adding source Ronneby Miljöteknik serving the municipality of Ronneby, Sweden

- custom_components/waste_collection_schedule/waste_collection_schedule/source/ccc_govt_nz.py
The dates are currently not showing owing to the API change as the dates are in the past.
> Fix CCC API date field name change

- custom_components/waste_collection_schedule/waste_collection_schedule/wizard/abfall_io.py
Like requested in #317 this adds the Bayreuth (Landkreis) to the `abfall_io` wizard.
> Add Bayreuth (Landkreis) to abfall_io wizard

- README.md
- doc/source/richmondshire_gov_uk.md
- info.md
I'm sure there's a better way of doing this, but here's the missing info for richmondshire_gov_uk:
- README.md
- info.md
- richmondshire_gov_uk.md
These, and the `richmondshire_gov_uk.py` file in #362, should complete that source request.
> Missing richmondshire_gov_uk info added

- custom_components/waste_collection_schedule/waste_collection_schedule/source/wiltshire_gov_uk.py
- requirements.txt
- Fix addresses which have a black box glass collection.
- Add missing `pyyaml` dependency.
Test:
```
…/hacs_waste_collection_schedule ❯ custom_components/waste_collection_schedule/waste_collection_schedule/test/test_sources.py -s wiltshire_gov_uk -l
Testing source wiltshire_gov_uk ...
found 4 entries for house_uprn
2022-10-06: Mixed dry recycling (blue lidded bin) and glass (black box or basket)
2022-10-20: Mixed dry recycling (blue lidded bin) and glass (black box or basket)
2022-10-14: Household waste
2022-10-28: Household waste
```
Signed-off-by: Russell Hall <owner@russellhall.co.uk>
> fix: Wiltshire source black box collection day

- custom_components/waste_collection_schedule/waste_collection_schedule/service/AbfallnaviDe.py
Added the following new cities to abfallnavi:
- Dorsten
- Oberhausen
- Solingen
- Straelen
- Kreis Viersen
- Brüggen
- Brüggen-Bracht
- Grefrath
- Kempen
- Nettetal
- Niederkrüchten
- Schwalmtal
- Tönisvorst
- Viersen
- Willich
> add new cities to abfallnavi

- custom_components/waste_collection_schedule/waste_collection_schedule/source/recycleapp_be.py
Updates as commented in #407:
API url updated to `https://api.fostplus.be/recycle-public/app/v1`
x-secret parameter updated
`{url}/streets` query change from GET to POST
Results for first test case seem odd, where there was always that many?
> recycleapp_be update

- doc/source/recyclesmart_com.md
> RecycleSmart: fix typo in docs

- README.md
- custom_components/waste_collection_schedule/calendar.py
- custom_components/waste_collection_schedule/sensor.py
- custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py
Due to changes for dedicated calendars some time ago, the global calendar went broken. It only showed waste types which appear in the customize list.
This commit recovers the old behaviour. Any waste type that is not displayed in a dedicated calendar is shown in the global calendar again.
> fix global calendar

- custom_components/waste_collection_schedule/waste_collection_schedule/source/wiltshire_gov_uk.py
Currently the source only returns collections for the current month. This fix adds collections for the next month when the current date is within 14 days of the month end.  This is done by utilising a couple of optional parameters in the API (specifying the month and year required).
Also adds the chargeable garden waste collection which is available for some properties.
> Expanded search to cover next month and added garden waste as collection type

- README.md
- custom_components/waste_collection_schedule/waste_collection_schedule/source/art_trier_de.py
- doc/source/art_trier_de.md
- info.md
Fixes #383
I added multiple test cases that cover different issues for creating the URL. However, it may be the case that some edge cases are not correctly handled as of now. In the current implementation, an error is thrown if the ICS parser is unable to parse the response.
If desired, I could wrap line 74 with a `try` statement and fail silently. I am not sure how the other sources handle such scenarios (I only dealt with Cochem-Zell so far), but I would tend to keep it this way and throw an error.
> Add support for ART Trier

- custom_components/waste_collection_schedule/waste_collection_schedule/source/environmentfirst_co_uk.py
was returning:
```bash
test_sources.py -s environmentfirst_co_uk -i -l
Testing source environmentfirst_co_uk ...
found 2 entries for houseUPRN
ERROR: source returns invalid date format (datetime.datetime instead of datetime.date?)
2022-12-22T00:00:00: RUBBISH [mdi:trash-can]
2022-12-30T00:00:00: RECYCLING [mdi:recycle]
found 3 entries for houseNumber
ERROR: source returns invalid date format (datetime.datetime instead of datetime.date?)
2023-01-03T00:00:00: RUBBISH [mdi:trash-can]
2022-12-27T00:00:00: RECYCLING [mdi:recycle]
2023-01-03T00:00:00: GARDEN WASTE [mdi:leaf]
found 2 entries for houseName
ERROR: source returns invalid date format (datetime.datetime instead of datetime.date?)
2022-12-23T00:00:00: RUBBISH [mdi:trash-can]
2022-12-28T00:00:00: RECYCLING [mdi:recycle]
```
Now …
> datetime fix for environmentfirst_co_uk

- doc/source/awbkoeln_de.md
This might be useful for people who don't have Python installed or don't want to install it.
> Added manual way to retrieve "street_code" for AWB Köln

- custom_components/waste_collection_schedule/waste_collection_schedule/source/art_trier_de.py
During my work on #505, I have come up with some improvements for the new `art_trier_de` source: The logic for parsing the correct district has been simplified and the source will now raise an exception if there is an HTTP error so that the user is aware of potential issues.
> Improve code quality of art_trier_de

- info.md
Doesn't look like the images in info.md are rendering when viewed in the HACS GUI, it's just displaying the alt text. I've added _?raw=true_ to the links to see if that corrects the issue.
> info.md urls updated

- info.md
I'm beginning to see what you meant about HA/HACS rendering of .md files. Looks like using absolute references is what's needed. Hopefully this update sorts the issue out.
> image urls changed to absolute references

- README.md
- update_docu_links.py
Great job on the automated document update script - certainly makes things easier! :+1: 
The Service Provider section for the README is slightly off 
Just an extra "\n" needed in the `update_docu_links.py` and a carriage return after the `<summary>ICS/iCal and User-Specified</summary>`
> Docu links

- custom_components/waste_collection_schedule/waste_collection_schedule/collection.py
- custom_components/waste_collection_schedule/waste_collection_schedule/source/art_trier_de.py
- custom_components/waste_collection_schedule/waste_collection_schedule/source/buergerportal_de.py
- doc/source/buergerportal_de.md
When adding `buergerportal_de`, I somehow missed that the source returns duplicate entries: It differentiates between different container sizes. This PR uses a set to remove such duplicates since in most cases, these different sizes will still be collected on the same day. If this is not the case for certain areas, it also adds a new option `show_volume` that includes the size of the container in the title of the entry. This way, users can use the built-in `customize` option of the sources configuration to adjust the collection types to their needs. These two changes give maximum freedom while still making the source easy to set up for most use cases. The corresponding documentation has also been updated to explain this new parameter and point users to the `customize` option in case they …
> Fix duplicate entries for buergerportal_de & some other enhancements

- custom_components/waste_collection_schedule/waste_collection_schedule/source/braintree_gov_uk.py
Parsing of 11/01/2023 was becoming to the 1st of November, this should be the 11th of January.
Example of the Braintree Website Results:
> Fix Braintree Date Parsing

- doc/source/ics.md
Update AVL Ludwigsburg ics link example, but please create your own file on avl homepage.
The issue recommended to use the ics implemenation, but the link was outdated.
> Update AVL Ludwigsburg ics link example

- custom_components/waste_collection_schedule/waste_collection_schedule/source/grosswangen_ch.py
- doc/source/grosswangen_ch.md
This source doesn't require any arguments. The correct syntax would be to provide an empty dict.
This PR removes the dummy argument `args` from the source and fixes the source docu.
fix #587
> fix empty args list for grosswangen_ch

- custom_components/waste_collection_schedule/waste_collection_schedule/source/grosswangen_ch.py
Added missing `mdi:` from ICON_MAP
Was:
```python
ICON_MAP = {
"Grüngutabfuhr": "mdi:leaf",
"Kehricht-Aussentour": "mdi:trash-can-outline",
"Kartonsammlung": "mdi:recycle",
"Altpapiersammlung": "newspaper-variant-multiple-outline",
"Häckselservice": "mdi:leaf-off",
"Alteisensammlung und Sammlung elektronischer Geräte": "desktop-classic",
"Zusätzliche Gratis-Laubabfuhr": "mdi:leaf",
}
```
Now:
```python
ICON_MAP = {
"Grüngutabfuhr": "mdi:leaf",
"Kehricht-Aussentour": "mdi:trash-can-outline",
"Kartonsammlung": "mdi:recycle",
"Altpapiersammlung": "mdi:newspaper-variant-multiple-outline",     #updated
"Häckselservice": "mdi:leaf-off",
"Alteisensammlung und Sammlung elektronischer Geräte": "mdi:desktop-classic",     #updated
"Zusätzliche Gratis-Laubabfuhr": "mdi:leaf",
}
```
> fix icon map

- doc/source/scambs_gov_uk.md
Fix example configuration for South Cambs, which includes an unneeded 'version' parameter (which gives an error).
> Fix example configuration for South Cambs

- doc/source/ashfield_gov_uk.md
- doc/source/harlow_gov_uk.md
Noticed that I had a couple of errors with my recent PRs in the Readme - an extra Configuration heading in each, and I forgot to change the title of Harlow when I copied it from my Ashfield one as an initial template.
This PR fixes both these issues :)
> Fix Ashfield & Harlow readmes

- doc/source/gotland_se.md
The readme file had references to the old service name (region_gotland_se) plus a spelling error, corrected these.
> Fixed errors in the readme file for gotland_se

- custom_components/waste_collection_schedule/waste_collection_schedule/service/AbfallIO.py
Added www.egst.de (Steinfurt) to the AbfallIO wizard
https://github.com/mampfes/hacs_waste_collection_schedule/issues/676#issue-1581329270
> added egst.de (Steinfurt) to AbfallIO wizard

- custom_components/waste_collection_schedule/waste_collection_schedule/service/AbfallIO.py
I added the "Landkreis Weißenburg-Gunzenhausen" to the AbfallIO wizard since the "AbfallApp Altmühlfranken" uses AbfallIO, see here: https://www.landkreis-wug.de/abfall/abfuhrkalender/
> Added lkr wug to AbfallIO wizard

- custom_components/waste_collection_schedule/waste_collection_schedule/source/hume_vic_gov_au.py
alias listed on mdi icons doesn't resolve, so corrected icon name
> Correct mdi icon for "Rubbish"

- custom_components/waste_collection_schedule/waste_collection_schedule/source/c_trace_de.py
- doc/source/c_trace_de.md
I updated c_trace_de to also allow other subdomains (see #697) and formats because there where only a few changes to be made  and I personally think it would not make sense to make a new integration, there are a few more like this one out there (googling: `site:apps.c-trace.de`)
but I'm not sure if this are to many possible arguments. (especially ical_url_file feels kind of janky)  I'm open to changes or other Idears
> updated c_trace_de to support other than web.ctrace.de urls

- custom_components/waste_collection_schedule/waste_collection_schedule/source/manchester_uk.py
Addresses some issues from #756:
- Uprn  pads to 12 digits if leading `0` is missing
- `h3` text used to identify waste collections rather than `img` alt text
- `DUE TODAY` removed from waste type description , prevents icon mapping issue `2023-03-13: Blue Bin  DUE TODAY [None]`
- New test case added for additional waste types
- Icon map updated with additional waste types
```bash
Testing source manchester_uk ...
found 15 entries for domestic
2023-03-13: Blue Bin [mdi:recycle]
2023-03-27: Blue Bin [mdi:recycle]
2023-04-10: Blue Bin [mdi:recycle]
2023-03-20: Brown Bin [mdi:glass-fragile]
2023-04-03: Brown Bin [mdi:glass-fragile]
2023-04-17: Brown Bin [mdi:glass-fragile]
2023-03-20: Green Bin [mdi:leaf]
2023-03-20: Green Bin [mdi:leaf]
2023-04-03: Green Bin [mdi:leaf]
2023-04-03: Green Bin …
```
> Updated Manchester City Council

- custom_components/waste_collection_schedule/waste_collection_schedule/source/kwu_de.py
adds a workaround for the current issue on the kwu calender, where they have deployed a version pointing to local test system
> fix: add workaround for wrong kwu deployment

- custom_components/waste_collection_schedule/waste_collection_schedule/source/liverpool_gov_uk.py
Corrects datetime/timedelta/date issue mentioned in #765 
```bash
Testing source liverpool_gov_uk ...
found 9 entries for 52 Swallowhurst Crescent Liverpool L11 2UZ
2023-03-24: Refuse [mdi:trash-can]
2023-04-07: Refuse [mdi:trash-can]
2023-04-21: Refuse [mdi:trash-can]
2023-03-17: Recycling [mdi:recycle]
2023-03-31: Recycling [mdi:recycle]
2023-04-14: Recycling [mdi:recycle]
2023-03-17: Green [mdi:leaf]
2023-03-31: Green [mdi:leaf]
2023-04-14: Green [mdi:leaf]
found 9 entries for 1 Aston Street Liverpool L19 8LR
2023-03-21: Refuse [mdi:trash-can]
2023-03-28: Refuse [mdi:trash-can]
2023-04-04: Refuse [mdi:trash-can]
2023-03-28: Recycling [mdi:recycle]
2023-04-11: Recycling [mdi:recycle]
2023-04-25: Recycling [mdi:recycle]
2023-03-28: Green [mdi:leaf]
2023-04-11: Green [mdi:leaf] …
```
> Liverpool source error fix

- custom_components/waste_collection_schedule/waste_collection_schedule/source/sysav_se.py
because the api returns a week instead of a date
fix for #791 
returns the correct week if normal ISO format is expected and not US format
> fixed sysav_se where waste type SLAM would raise an error

- custom_components/waste_collection_schedule/waste_collection_schedule/source/abfallnavi_de.py
- doc/source/abfallnavi_de.md
A general question: how should something like this be handled? Should every argument only allow a single datatype? Especially for house numbers you might accidentaly use an integer instead of a string.
Here in abfallnavi_de if `hausnummer` is an int, it is handles as if `hausnummer` was  `None` (because it does not find the house number in the returned json), but this does not raise an error but returns valid but incomplete or wrong values (see #829)
> allow integer haunummer arguments in abfallnavi_de

- custom_components/waste_collection_schedule/waste_collection_schedule/source/ecoharmonogram_pl.py
fix for #839
The old code iterated over the schedule periods but returned after the first (or returned only the last if additional_sides_matcher is not set). This does not seem to be the wanted behaviour. This increases the found Events (test cases) From:
```
found 158 entries for Simple test case
found 234 entries for Sides multi test case
found 18 entries for Sides test case
found 397 entries for Sides multi test case with district
found 156 entries for Simple test with community
```
to
```
found 158 entries for Simple test case
found 782 entries for Sides multi test case
found 78 entries for Sides test case
found 397 entries for Sides multi test case with district
found 156 entries for Simple test with community
```
Its hard for me to validate if all of them are actually wanted events. …
> fixing ecoharmonogram_pl to get events from multiple schedule periods

- custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py
- doc/source/ics.md
This fixes the regex to allow for collections with exactly two waste types. The current regex does not split these correctly (no comma before the "and").
It seems that Ottawa always has at least 3 waste types per event, so the issue does not occur there.
I've added Simcoe County as a test case that uses two waste type events as the norm.
This also addresses a comment in #77 where a user was looking for the correct regex to use in this case.
> Update ReCollect docs and tests with new split_at regex

- custom_components/waste_collection_schedule/waste_collection_schedule/source/nuernberger_land_de.py
As `mahe112` noted in [this](https://github.com/mampfes/hacs_waste_collection_schedule/pull/549#issuecomment-1552076989) comment, I prepared this PR to fix the issue of missing events in the source: `nuernberger_land_de`.
> nuernberger_land_de: add filter to include all events

- update_docu_links.py
> fixed error where update_docu_links fails in windown.

- doc/source/static.md
Space was missing after colon for weekdays dictionary.
> fix docu for static source

- custom_components/waste_collection_schedule/waste_collection_schedule/source/eastherts_gov_uk.py
- doc/source/eastherts_gov_uk.md
**BREAKING CHANGE (for this source)**
East Herts operate a paid-for Garden Waste collection service. Only properties that have paid for this service will be offered the next collection dates on the lookup. I pay for this service, yet wasn't receiving any dates for the next collection.
In my debugging, I noticed that the council's website has been updated with the following guidance on the search:
> Please enter your property name/number and postcode ONLY. Please do NOT enter your street.
The component was previously providing the street name which was resulting in it ignoring the house number and returning all 35 properties in the post code and selecting the first returned property by default. That property does not subscribe to the garden waste service, hence my problem.
I have removed …
> Fix variable names (typo) and update search to support Garden Waste Collections in eastherts_gov_uk

- custom_components/waste_collection_schedule/waste_collection_schedule/source/republicservices_com.py
Updated Republic Services to try and account for collection delays resulting from public holidays, as per #1005.
Just needed to wait for a public holiday to test using results pulled back from the api.
Previous test cases were all commercial collections that didn't appear to be impacted by public holidays. A `Residential Collection` test case was added as a sanity check. As an illustration, the collection originally planned for 6th July is delayed until the 7th July due to the 4th July holiday. The script now returns the delayed collection date of 7th July.
Given the range of service types, waste formats, and regional variations in whether holidays impact schedules, I'm sure further tweaks will be required at some point.
```bash
Testing source republicservices_com ...
found 1 entries for …
```
> Issue 1005

- doc/ics/recollect.md
- doc/ics/yaml/recollect.yaml
Added the city of Georgetown, TX to the recollect.yaml
Ran ./update_docu_links.py to update the markdown file
Test Results:
```
$ ./test_sources.py -y recollect.yml
Testing ICS recollect
found 50 entries for Cambridge, MA, USA
found 50 entries for Ottawa, ON, Canada
found 37 entries for Georgetown, TX, USA
found 37 entries for Georgetown, TX, USA
2023-07-11 : Trash
2023-07-18 : Recycling
2023-07-18 : Trash
```
> Adding Georgetown, TX to recollect.yaml

- custom_components/waste_collection_schedule/waste_collection_schedule/source/bielefeld_de.py
Bielefeld changed it's url form 
```
https://anwendungen.bielefeld.de/WasteManagementBielefeld/WasteManagementServlet
```
to 
```
https://anwendungen.bielefeld.de/WasteManagementBielefeldTest/WasteManagementServlet
```
Yes, unbelievable but true. They added "Test" to their production URL. Also the URL on their [Main site](https://service.bielefeld.de/detail/-/vr-bis-detail/dienstleistung/3329451/show) refers to that link. 
The above mentioned URL  
```
https://anwendungen.bielefeld.de/WasteManagementBielefeldTest/WasteManagementServlet
```
is not callable in a Browser directly. In the Browser it requires some parameters. 
```
https://anwendungen.bielefeld.de/WasteManagementBielefeldTest/WasteManagementServlet?SubmitAction=wasteDisposalServices
```
But the Integration is working again …
> Change URL of bielefeld_de to new URL

- README.md
- custom_components/waste_collection_schedule/waste_collection_schedule/source/dunedin_govt_nz.py
- doc/source/dunedin_govt_nz.md
- info.md
New source, as requested in #1074
Test case "No Collection" is intended to fail, there is (currently) no collection service for that address.
I think the other test cases cover the different schedules that exist, but the website only provides details for _Calendar 1 & 2_ where Black/Blue and Black/Yellow are collected on alternate weeks. _All Week_ and _Collection 'c'_ are inferred from picking random addresses.
```bash
Testing source dunedin_govt_nz ...
No Collection failed: No collection service for that address
found 2 entries for Calendar 1
2023-07-20 : Black Bag [mdi:trash-can]
2023-07-20 : Blue Bin [mdi:bottle-soda]
found 2 entries for Calendar 2
2023-07-19 : Black Bag [mdi:trash-can]
2023-07-19 : Yellow Bin [mdi:recycle]
found 5 entries for All Week
2023-07-17 : Black Bag …
```
> New Source: Dunedin, Otago, NZ

- custom_components/waste_collection_schedule/waste_collection_schedule/source/eastriding_gov_uk.py
Addresses issue identified in #1115 
```bash
Testing source eastriding_gov_uk ...
2023-08-08 : Blue Bin [mdi:recycle]
2023-08-01 : Green Bin [mdi:trash-can]
2023-07-27 : Brown Bin [mdi:leaf]
2023-08-07 : Blue Bin [mdi:recycle]
2023-07-31 : Green Bin [mdi:trash-can]
2023-07-27 : Brown Bin [mdi:leaf]
2023-08-08 : Blue Bin [mdi:recycle]
2023-08-01 : Green Bin [mdi:trash-can]
2023-08-02 : Brown Bin [mdi:leaf]
found 3 entries for Test_004
2023-08-08 : Blue Bin [mdi:recycle]
2023-08-01 : Green Bin [mdi:trash-can]
2023-07-27 : Brown Bin [mdi:leaf]
```
> Update: eastriding_gov_uk

- custom_components/waste_collection_schedule/waste_collection_schedule/source/basingstoke_gov_uk.py
fix for #1125
fixes `unable to get local issuer certificate` with disableing ssl all together
not ideal
> disable ssl for basingstroke_gov_uk

- custom_components/waste_collection_schedule/waste_collection_schedule/source/samiljo_se.py
fix for #1133 
Taking the 3rd element like the javascript on the website (https://webbservice.indecta.se/kunder/sam/kalender/basfiler/skript/jq.eget.js) `$('#anlnr').val(data[3]);` instead of the last (-1) fixed the error.
They probably added an additional number on the end indecating something different
> fix samilio_se

- custom_components/waste_collection_schedule/waste_collection_schedule/source/nottingham_city_gov_uk.py
- doc/source/nottingham_city_gov_uk.md
It seems they have updated their api and the data that is returned. Here's what it looks like now. I think this has made it much easier as it now provides the datetime of when the bin day is :).
```json
{
"uprn": "000000000000",
"address": "xxxxxxxxxxxx",
"postcode": "xxxxxxxxxxx",
"binTypes": [
"Waste",
"Recycling",
"Garden"
],
"nextCollections": [
{
"collectionType": "Waste",
"collectionDate": "2023-08-10T07:00:00",
"collectionDay": "Thursday"
},
{
"collectionType": "Recycling",
"collectionDate": "2023-08-17T07:00:00",
"collectionDay": "Thursday"
},
{
"collectionType": "Garden",
"collectionDate": "2023-08-17T07:00:00",
"collectionDay": "Thursday"
}
],
"hasWaste": true,
"hasRecycling": true,
"hasGarden": true,
"hasFood": false,
"isCommunal": false,
"nextBinIsWaste": true, …
```
> Update to nottingham_city_gov_uk to support new api and data structure.

- custom_components/waste_collection_schedule/waste_collection_schedule/source/exeter_gov_uk.py
- doc/source/exeter_gov_uk.md
Regex updated to prevent ordinals being removed from month names.
Corrects issue mentioned in #1145.
```bash
Testing source exeter_gov_uk ...
2023-08-02 : Refuse [mdi:trash-can]
2023-08-01 : Recycling [mdi:recycle]
2023-08-01 : Garden waste [mdi:leaf]
2023-08-01 : Food waste [mdi:food]
2023-08-02 : Refuse [mdi:trash-can]
2023-08-01 : Recycling [mdi:recycle]
2023-08-01 : Garden waste [mdi:leaf]
2023-08-01 : Refuse [mdi:trash-can]
2023-08-02 : Recycling [mdi:recycle]
2023-08-02 : Garden waste [mdi:leaf]
found 4 entries for Test_004
2023-08-02 : Refuse [mdi:trash-can]
2023-08-01 : Recycling [mdi:recycle]
2023-08-01 : Garden waste [mdi:leaf]
2023-08-01 : Food waste [mdi:food]
```
> Fix: Exeter Council

- custom_components/waste_collection_schedule/waste_collection_schedule/source/lakemac_nsw_gov_au.py
Lake Macquarie Council no longer provides a date for bulk waste collection, which causes lakemac_nsw_gov_au source to fail
To solve this, I'm proposing simply wrapping creating the `date_object` creation in a try/except statement, and simply ignoring the `next-service` tag if it can't be parsed.
Test before this proposed change:
```
python3 test_sources.py -s lakemac_nsw_gov_au
Testing source lakemac_nsw_gov_au ...
TestcaseI failed: time data '' does not match format '%a %d/%m/%Y'
TestcaseII failed: time data '' does not match format '%a %d/%m/%Y'
```
Test after this proposed change:
```
python3 test_sources.py -s lakemac_nsw_gov_au
Testing source lakemac_nsw_gov_au ...
found 3 entries for TestcaseI
found 3 entries for TestcaseII
```
> Fix error caused by Lake Mac no longer providing bulk waste date

- custom_components/waste_collection_schedule/waste_collection_schedule/source/guildford_gov_uk.py
Line 34 caused an issue with type errors, so I've cast it to a string when reading it in initially:
`fetch failed for source Guildford Borough Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/guildford_gov_uk.py", line 34, in fetch "message=%7B%22actions%22%3A%5B%7B%22id%22%3A%22291%3Ba%22%2C%22descriptor%22%3A%22apex%3A%2F%2FBinScheduleDisplayCmpController%2FACTION%24GetBinSchedules%22%2C%22callingDescriptor%22%3A%22markup%3A%2F%2Fc%3ABinScheduleDisplay%22%2C%22params%22%3A%7B%22database%22%3A%22domestic%22%2C%22UPRN%22%3A%22" …
> Update guildford_gov_uk.py to fix type issues

- custom_components/waste_collection_schedule/waste_collection_schedule/source/innerwest_nsw_gov_au.py
My AU NSW local council (**Inner West Council**) was an amalgamation of three councils several years ago (_Marrickville_, _Leichhardt_ and _Ashfield_), but the waste collection databases are still - STILL! - split by individual old-council areas.
The previous code only searched collection details for the old Marrickville area. This PR adds a search by suburb across the other two databases, to find details for everyone in Innerwest.
Searching is preferred to forcing users to specify out what old council source they're in since there isn't an official way to find out what council you used to be in anymore.
> Add support for subcouncil databases in innerwest.nsw.gov.au

- custom_components/waste_collection_schedule/sensor.py
- custom_components/waste_collection_schedule/waste_collection_schedule/collection_aggregator.py
- doc/faq.md
- doc/installation.md
adding the ability to show the Nth collection date for a sensor wanted by #1099
I haven't spent that much time in the homeassistant custom components code (except for sources) so I might have missed stuff that also need to be changed but after a bit of testing everything seems to work.
I'm also not sure if  `event_index` is a good name for this parameter but I couldn't think of a better name.
Feel free to change the name and the documentation if you like
> Sensor event index

- doc/source/okc_gov.md
updated okc_gov.md: `name: okc.gov` corrected to `name: okc_gov`
as mentioned in recent [comment](https://github.com/mampfes/hacs_waste_collection_schedule/pull/856#issuecomment-1698525012)
> config typo corrected

- .pre-commit-config.yaml
- custom_components/waste_collection_schedule/waste_collection_schedule/source/croydon_gov_uk.py
- doc/source/croydon_gov_uk.md
Update to fix issue identified in #1236.
Now reports collections happening on today's date - see first test case.
```bash
Testing source croydon_gov_uk ...
2023-09-06 : Food waste [mdi:food]
2023-09-06 : General rubbish [mdi:trash-can]
2023-09-06 : Paper and card recycling [mdi:newspaper]
2023-09-13 : Glass, plastics, cans and cartons recycling [mdi:bottle-wine]
2023-09-14 : Glass, plastics, cans and cartons recycling [mdi:bottle-wine]
2023-09-07 : General rubbish [mdi:trash-can]
2023-09-07 : Paper and card recycling [mdi:newspaper]
2023-09-07 : Food waste [mdi:food]
found 4 entries for Test_003
2023-09-07 : General rubbish [mdi:trash-can]
2023-09-14 : Glass, plastics, cans and cartons recycling [mdi:bottle-wine]
2023-09-07 : Paper …
```
> Fix: Croydon, UK

- custom_components/waste_collection_schedule/waste_collection_schedule/source/was_wolfsburg_de.py
Fix for issue identified in #1252
Have added a dict that can be used if other problem characters are identified. "ü" seems to be an issue, but , "ö" and "ä" seem to work fine.
> Fix: was_wolfsburg_dr

- custom_components/waste_collection_schedule/waste_collection_schedule/source/renosyd_dk.py
The description on renosyd is as following:
1 x Restaffald 240L 
1 x Papir/Pap 240L 
1 x Emballage 240L 
1 x Haveaffald 240 L 
1 x Storskrald 
The space between 240 and L in Haveaffald didn't trigger before, fixed it with \s?
> Haveafald new triggers also with "240 L" description

- custom_components/waste_collection_schedule/waste_collection_schedule/source/rushmoor_gov_uk.py
The `rushmoor_gov_uk` integration is supposed to return a "Food" collection each week, however it currently only adds it when the "Refuse" bin is due. Unindenting the block to be outside the `if` statement seems to bring the intended effect.
> Fix Rushmoor Food Waste Schedule

- doc/source/stoke_gov_uk
Issues fixed by this PR:
1. Markdown file name didn't match source file name.
2. Source file name in docu didn't match source file name.
> fix docu for stoke_gov_uk

- custom_components/waste_collection_schedule/waste_collection_schedule/source/okc_gov.py
fix for incapsular blocking requests metioned by @sanctas in #764
> okc_gov header fix incapsular + reformatting

- custom_components/waste_collection_schedule/waste_collection_schedule/source/aha_region_de.py
remove debug file mentioned by #1317 (does not fix #1317)
> removing debug file from aha_region_de + Reformatting

- custom_components/waste_collection_schedule/waste_collection_schedule/source/whittlesea_vic_gov_au.py
Referring to https://github.com/mampfes/hacs_waste_collection_schedule/issues/912
previous fix was to apply 10 hours, however due to DST time zone is now GMT+11 and issue has reappeared.
fix is to offset by 1 day as opposed to hours. I did test 11 hours but this issue would reappear in April (when DST ends)
> Update whittlesea_vic_gov_au.py - DST Fix

- custom_components/waste_collection_schedule/waste_collection_schedule/source/innerwest_nsw_gov_au.py
Reorder Inner West Council possible APIs to attempt old Leichhardt Council before attempting old Marrickville Council.
A single suburb is duplicated between the 3 lists: "Leichhardt" appears in both Leichhardt and Marrickville API endpoints. Only a single street in Leichhardt is listed by the Marrickville endpoint, and that with only a single property; this is likely bad data.
This is not a lasting fix, as it doesn't protect against future duplicates, but there are thousands of properties in "true" Leichhardt, and only one in "false" Leichhardt, so at least this reordering fixes for most people.
> Reorder innerwest_nsw_gov_au APIs to work around duplicate data

- custom_components/waste_collection_schedule/waste_collection_schedule/source/awn_de.py
> fix awn_de by disabling ssl check

- custom_components/waste_collection_schedule/waste_collection_schedule/source/pgh_st.py
pgh.st was down for a while, and just came back up. Seems that it only responds to requests on https now, not http.
> pgh.st now requires https

- custom_components/waste_collection_schedule/waste_collection_schedule/source/bristol_gov_uk.py
Fix for nextCollectionDate timestamp from API containing `T01:00:00` and breaking the integration
> Fix for Bristol nextCollectionDate timestamp

- doc/source/c_trace_de.md
This fixes an inconsistency in the documentation, as `gemeinde` wasn't documented due to a copy & paste error.
Also it extends the documentation of `ortsteil`.
> Update documentation of c_trace_de.md

- custom_components/waste_collection_schedule/waste_collection_schedule/source/stockton_gov_uk.py
Fixed an issue where the date returned from stockton_gov_uk would be "Date not available" during winter months for garden waste. This would cause an error when converting it to a date string.
> Fix "Date not available" error for stockton_gov_uk

- .github/ISSUE_TEMPLATE/BUG-REPORT.yml
- .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
- .github/ISSUE_TEMPLATE/SOURCE-REQUEST.yml
- .github/ISSUE_TEMPLATE/config.yml
adding these issue forms could help to get better Bug reports and source requests.
@dt215git and @mampfes please provide feedback if this is a good idea/implementation.
issue forms documentation: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
>  Note: Issue forms are currently in beta and subject to change.
try these templates at https://github.com/5ila5/template_test (feel free to add create issues)
This disables the possibiltiy to create "normal" issues so please provide feedback about this if we should use this or if we should change something
> add issue forms

- custom_components/waste_collection_schedule/waste_collection_schedule/source/newcastle_staffs_gov_uk.py
Fixes issues raised in #1358
```bash
Testing source newcastle_staffs_gov_uk ...
found 16 entries for Test_001
2023-11-07 : Food Waste [mdi:food]
2023-11-07 : Recycling [mdi:recycle]
2023-11-14 : Food Waste [mdi:food]
2023-11-14 : Household Rubbish [mdi:trash-can]
2023-11-21 : Food Waste [mdi:food]
2023-11-21 : Recycling [mdi:recycle]
2023-11-28 : Food Waste [mdi:food]
2023-11-28 : Household Rubbish [mdi:trash-can]
2023-12-05 : Food Waste [mdi:food]
2023-12-05 : Recycling [mdi:recycle]
2023-12-12 : Household Rubbish [mdi:trash-can]
2023-12-12 : Food Waste [mdi:food]
2023-12-19 : Food Waste [mdi:food]
2023-12-19 : Recycling [mdi:recycle]
2023-12-26 : Household Rubbish [mdi:trash-can]
2023-12-26 : Food Waste [mdi:food]
found 16 entries for Test_002
2023-11-08 : Household Rubbish …
```
> Fix Source: newcastle_staffs_gov_uk

- README.md
- custom_components/waste_collection_schedule/waste_collection_schedule/source/bir_no.py
- doc/source/bir_no.md
- info.md
> New source: BIR

- custom_components/waste_collection_schedule/waste_collection_schedule/source/wokingham_gov_uk.py
The original url is returning a 301 Moved Permanently now
> Update Wokingham API URL

- doc/source/ead_darmstadt_de.md
> EAD Darmstadt: Link to the address search corrected in the documentation

- custom_components/waste_collection_schedule/waste_collection_schedule/source/renosyd_dk.py
Now next year's schedule appears on Renosyd's website the year wraparound bug was revealed. Also I can't spell 🙂
> Fix year wraparound bug + month misspelt in Renosyd.dk

- custom_components/waste_collection_schedule/manifest.json
[`bs4`][1] is a placeholder for [`beautifulsoup4`][2] to prevent typo-squatting. From the description of the `bs4` package on PyPI:
> This is a dummy package managed by the developer of Beautiful Soup to prevent name squatting. The official name of PyPI’s Beautiful Soup Python package is [beautifulsoup4](https://pypi.python.org/pypi/beautifulsoup4). This package ensures that if you type pip install bs4 by mistake you will end up with Beautiful Soup.
While the placeholder does prevent a malicious actor from hijacking the package, it's not a good idea to rely on this.
This **does not** affect the imports like:
```python
from bs4 import BeautifulSoup
```
[1]: https://pypi.org/project/bs4/
[2]: https://pypi.org/project/beautifulsoup4/
> correct dependency on `beautifulsoup4` instead of `bs4`

- custom_components/waste_collection_schedule/waste_collection_schedule/source/wirral_gov_uk.py
wirral_gov_uk source uses a scraper which expects a list of dates like "30 December 2023". For the Christmas schedule they added some extra descriptive text like "30 December 2023 (Saturday) in lieu of 01 January 2024", which caused an exception to be thrown in the date parsing.
This PR adds a regex to pre-validate the scraped rows and discard any extra trailing text.
> wirral_gov_uk: fix for crash introduced due to extra text for Christmas schedule

- custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py
- custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py
Landkreis Göttingen merged with Altkreis Osterode years ago and still has separate waste collection services, modeled as 2 Landkreise.
The app requests to select the landkreis first, which was not supported in app_abfallplus_de.
I also added a test case, because this seems to be a corner case.
> Fix Landkreis Göttingen in app_abfallplus_de

- custom_components/waste_collection_schedule/waste_collection_schedule/service/AbfallnaviDe.py
- custom_components/waste_collection_schedule/waste_collection_schedule/source/abfallnavi_de.py
Fix Unna and other regions who might be affected and provide theire API at `https://abfallapp.regioit.de/abfall-app-{service_domain}/rest` istead of `https://{service_domain}-abfallapp.regioit.de/abfall-app-{service_domain}/rest`
this fixes #1554
> fix abfallnavi_de for affected regions

- custom_components/waste_collection_schedule/waste_collection_schedule/source/abfall_zollernalbkreis_de.py
- doc/source/abfall_zollernalbkreis_de.md
abfall_zolleralbkreis_de now supports city/streat names isntad of ids. removed types argument as this should be done by the customize argrument
> zolleralbkreis_de: remove types, allow city/street name

- doc/source/abfallnavi_de.md
- update_docu_links.py
abfallnavi_de now shows the service id table to be bale to configure the source without needing to run the wizzard
addresses problems mentioned in #1628
> abfallnavi_de md shows service id

- doc/source/nuernberger_land_de.md
The ID format to identify your street / collection tour has changed from 8 digits to 2-8 digits from 2024 on. Fixed the documentation.
> Fix new digit format in Abfallwirtschaft Nuernberger Land from 2024 on (Issue: 2065307965)

- custom_components/waste_collection_schedule/waste_collection_schedule/source/geelongaustralia_com_au.py
When this was reformatted in #1509 it flipped whether it was an error based on the type or not. This should fix it up and match the preferred formatting.
> fix Geelong Australia boolean logic error from reformat

- doc/ics/edg_de.md
- doc/ics/yaml/edg_de.yaml
This pull request updates the documentation of the EDG in Germany, as discussed in #1584 since they changed the format of the ics file.
Thanks to @Xento for the idea!
> fix: add regex to edg_de documentation example

- custom_components/waste_collection_schedule/waste_collection_schedule/source/calgary_ca.py
- doc/source/calgary_ca.md
calgary_ca seems to not return all collections anymore (#1659). They moved to displaying a recollect window.
This adds a message (markdown and logger.warning) to use the recollect ICS configuration instead.
> calgary_ca add logger message to move to recollect ics source

- custom_components/waste_collection_schedule/sensor.py
- doc/installation.md
I would like to suggest an additional option for `details_format` to hide all information about upcoming collections in the attributes.
> feat: add `details_format`: `hidden`

- custom_components/waste_collection_schedule/waste_collection_schedule/source/stadtreinigung_leipzig_de.py
- doc/ics/stadtreinigung_leipzig_de.md
- doc/ics/yaml/stadtreinigung_leipzig_de.yaml
This PR fixes the error "Curently in Maintenance Mode." when downloading the ics.
The download request got two new parameter:
1. Street and street_number
2. mode=download
Thx for your review and overall work.
> Stadtreinigung Leipzig - Fix ics download

- custom_components/waste_collection_schedule/waste_collection_schedule/source/lrasha_de.py
- doc/source/lrasha_de.md
The link to the calendar has changed as well as all of the IDs starting with the new year 2024.
I have tested the changes on my local installation.
> Fix lrasha_de

- custom_components/waste_collection_schedule/waste_collection_schedule/source/exeter_gov_uk.py
This is to fix issue: #1642 
A check for missing dates was added.
In the users example, the date for Garden waste collection was missing.
> Source Exeter_gov_uk: Add check for missing collection dates

- custom_components/waste_collection_schedule/__init__.py
If an unknown source is in the configuration, multiple exceptions are raised. Reason is that None is added to the source_shell list. This adds a check to prevent this.
Example exception:
```
File "/custom_components/waste_collection_schedule/calendar.py", line 35, in async_setup_platform
dedicated_calendar_types = shell.get_dedicated_calendar_types()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_dedicated_calendar_types'
```
> Fix: Core - Add check for unknown source

- custom_components/waste_collection_schedule/waste_collection_schedule/source/recycleapp_be.py
Recycleapp_be stopped working and it seems the issue was an updated x-secret header. In this PR I fix the x-secret header.
Fix for https://github.com/mampfes/hacs_waste_collection_schedule/issues/1716
> Update x-secret in headers recycleapp_be

- custom_components/waste_collection_schedule/waste_collection_schedule/source/adur_worthing_gov_uk.py
@jonathh21 in https://github.com/mampfes/hacs_waste_collection_schedule/commit/6895b577feb9bef7239de5eca8165116411e8077#commitcomment-138314023
> Hi, I am not saying this is related, but my adur lookup stopped working recently, and this is the only change I can see.
> 
> The error i see in the logs is "Address not found" and that seemingly only occurs if no entry is found after the for loop.
> 
> Curiously, this change, which seem innocuous enough, appears to be to make it case insensitive - but i had a capitalised address all along and it worked fine.
> 
> Any word on what this was trying to solve?
> Interestingly - if i replace the variable usages in the urls for self._postcode and {address['value']} with actual values from adurs website.. it works fine.
- This fixes an error where the …
> adur_worthing_gov_uk fixed address match error + imporved error message

- custom_components/waste_collection_schedule/waste_collection_schedule/source/awido_de.py
fixes #1800
this customer did not retrun any data using the https://awido.cubefour.de/WebServices/Awido.Service.svc/secure/getData/{oid} request.
After this fix the script falls back to using the ics download from https://awido.cubefour.de/Customer/{self._customer}/KalenderICS.aspx instead.
> fix awido_de for some regions

- .devcontainer/devcontainer.json
- custom_components/waste_collection_schedule/waste_collection_schedule/source/renosyd_dk.py
- doc/source/renosyd_dk.md
While the old(?) API might still be kept around, Renosyd now advises to check schedule on https://mit.renosyd.dk. As such, I checked the API call made on there and sure enough it's to a different service which I thought I would try contribute an update here.
Would be great if @lexitus could check this over in relation to the `renosyd_dk` changes, and of course feel free to contribute directly to the fork to make any adjustments 👍
> Make use of new Renosyd (DK) API and update `devcontainer`

- doc/installation.md
> sensor types documentation now states to use the alias

- custom_components/waste_collection_schedule/waste_collection_schedule/source/rctcbc_gov_uk.py
They added a hidden `printableCalendar` which contains all available months of data. The old script found all events in the visible and the printableCalendar but associated them all with the month of the visible calendar which lead to a lot of wrong additional entries. This fix tries to parse the printableCalendar first which saves useless web requests. If it fails it falls back to the old approach.
fixes #1916
> fix rctcbc_gov_uk: parsing new hidden calendar fields

- custom_components/waste_collection_schedule/icons.json
adding icon for fetch_data service to satisfy hassfest.
Does sound optional though:
https://developers.home-assistant.io/blog/2024/01/19/icon-translations/
> add icons.joson with fetch_data service icon

- custom_components/waste_collection_schedule/waste_collection_schedule/source/braintree_gov_uk.py
Properties without `Garden Bin` collection services have empty results returned.
This currently breaks every lookup without a Garden Bin collection dates (1/4 of the test cases)
e.g.
This currently breaks the scraper as it's expecting results.
I've modified the code to allow for this to happen.
I also noticed for commercial addresses (Like the council's offices), there's only Clear Sack collection - This change should fix that too, hence adding a new test case
Thanks
> Braintree - Skipping collections without dates

- custom_components/waste_collection_schedule/waste_collection_schedule/source/braintree_gov_uk.py
I got stuck for a while on setting this up due to missing quotes in my `yml` config.
I figured it'd be nice to allow integers.
Merge this first 
https://github.com/mampfes/hacs_waste_collection_schedule/pull/1920
> Braintree - Feature allow int as house number

- custom_components/waste_collection_schedule/waste_collection_schedule/source/renoweb_dk.py
- doc/source/renoweb_dk.md
Adds a setting to `renoweb_dk` for also including entries that are not collected automatically but should be ordered for pickup (`afhentningsbestillingmateriel = True`).
For "fh" municipality that is for example:
- Farligt affald (hazardous waste)
- Tekstilaffald (textile waste)
- Storskrald (large objects waste)
- Haveaffald (garden waste)
Tests:
```bash
./test_sources.py -s renoweb_dk --weekday
Testing source renoweb_dk ...
found 26 entries for test_01
found 195 entries for test_02
found 291 entries for test_03
found 56 entries for test_04
```
> add "include_ordered_pickup_entries" setting to renoweb_dk

- custom_components/waste_collection_schedule/waste_collection_schedule/source/aucklandcouncil_govt_nz.py
Looks like the council have changed their site.
So lets move this over to use Beautiful Soup because who wants to keep state in booleans.
Tests run clean with
```
python3 test_sources.py --source aucklandcouncil_govt_nz -l
```
fixes https://github.com/mampfes/hacs_waste_collection_schedule/issues/1962
> [bug fix] Fix up Auckland Council - appears to be a website change

- custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py
- custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py
This is the next try to fix issue: #1989 
- User-agent headers added to make sure the API delivers the data back.
- Client_id changed from guid to random_hex(48)
- added more test cases, fixed a few tests, Bonn orange is failing (~~needs to be removed in a follow up PR, I will open an issue~~ needs to be checked again...)
Test report:
```
Testing source app_abfallplus_de ...
found 36 entries for de.albagroup.app Braunschweig Hauptstraße 7A  
de.k4systems.bonnorange Auf dem Hügel failed: Street 'Auf dem Hügel' not found., available: []
found 192 entries for de.ucom.abfallavr Brühl Habichtstr. 4A
found 66 entries for de.k4systems.abfallappwug Bergen hauptstr. 1
found 109 entries for de.k4systems.abfallappcux Wurster Nordseeküste Aakweg Alle Hausnummern
found 57 entries for de.abfallwecker …
```
> Fix v2: Source: AppAbfallPlusDE - Add user-agent to request

- custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py
- custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py
[Looks like](https://github.com/mampfes/hacs_waste_collection_schedule/issues/1989#issuecomment-2070347155) the vendor blocked already the changes introduced in #2001.
This is the next try to fix issue: https://github.com/mampfes/hacs_waste_collection_schedule/issues/1989
- Added App-specific User-agent headers added to make sure the API delivers the data back.
I can't test all the apps but the testcases are succesful and some users tested the code and gave positive feedback. (see comments below this [comment](https://github.com/mampfes/hacs_waste_collection_schedule/issues/1989#issuecomment-2070479498))
```
Testing source app_abfallplus_de ...
found 36 entries for de.albagroup.app Braunschweig Hauptstraße 7A  
found 97 entries for de.k4systems.bonnorange Auf dem Hügel
found 192 entries …
```
> Source: AppAbfallPlusDE - Add app-specific user-agent to request header

- custom_components/waste_collection_schedule/waste_collection_schedule/source/awlneuss_de.py
The current implementation is loading the first three months of the year only. 
Fix: Change to full year load
Releated issue: #2014 
```
Testing source awlneuss_de ...
found 143 entries for Neuss, Theodor-Heuss-Platz 13
found 143 entries for Neuss, Niederstrasse 42
found 143 entries for Neuss, Bahnhofstrasse 67
found 143 entries for Neuss, Bismarckstrasse 52
found 143 entries for Neuss, Karlsstrasse 1 (5200)
```
> Fix: Source: AWLNeuss_DE - change to full year load

- doc/ics/gedling_gov_uk.md
- doc/ics/yaml/gedling_gov_uk.yaml
A small update, one of the calendar example names and path was incorrect for the docs. This has been corrected in this pull request.
> Gedling Borough Council: Fix typo on iCal calendar example

- custom_components/waste_collection_schedule/__init__.py
`random.randrange(0, 0)` results in `ValueError: empty range in randrange(0, 0)`
> fix bug where random_fetch_time_offset: 0 leads to an error because random.randrange(0, 0) is called

- custom_components/waste_collection_schedule/__init__.py
- custom_components/waste_collection_schedule/waste_collection_schedule/collection.py
- custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py
- doc/installation.md
Add the option to set a day_offset in the source configuration like for the ics source. This might be helpfull for sources that do fetch the elements correctly from the webpage, but the website is wrong.
fixes #2112
and addresses option to temporarly fix issues like #2113
> add source specifc day_offset parameter

- custom_components/waste_collection_schedule/sensor.py
prevents bug reports like: #2107
Previouse error message on source_index out of range: `AttributeError: 'NoneType' object has no attribute '_entries'`
New Error message (if one index is 3 but only 2 sources are configured): `ValueError: source_index 3 out of range (0-2) please check your sensor configuration`
> improve error message if source_index is out of range

- doc/ics/gedling_gov_uk.md
- doc/ics/yaml/gedling_gov_uk.yaml
To make it easier to access the unofficial calendars that are published, I have created a GitHub pages site, which provides all the calendars in a nicer way.
> Gedling Borough Council: Update guidance to use newly created pages site with all iCal links easily accessible

- custom_components/waste_collection_schedule/waste_collection_schedule/source/haringey_gov_uk.py
Fixes #2125
Test output following changes:
```
$ ./test_sources.py -s haringey_gov_uk -i -l
Testing source haringey_gov_uk ...
2024-06-05 : Recycling [mdi:recycle]
2024-06-05 : Non-Recyclable Waste [mdi:trash-can]
2024-06-05 : Food Waste [mdi:food-apple]
2024-06-07 : Recycling [mdi:recycle]
2024-06-07 : Non-Recyclable Waste [mdi:trash-can]
2024-06-07 : Food Waste [mdi:food-apple]
2024-06-07 : Garden Waste [mdi:leaf]
2024-06-07 : Food Waste [mdi:food-apple]
2024-06-07 : Recycling [mdi:recycle]
2024-06-07 : Non-Recyclable Waste [mdi:trash-can]
found 3 entries for Test_004
2024-06-04 : Non-Recyclable Waste [mdi:trash-can]
2024-06-04 : Food Waste [mdi:food-apple]
2024-06-04 : Recycling [mdi:recycle]
```
> Update haringey_gov_uk as a result of site changes to waste type names

- README.md
- doc/ics/gedling_gov_uk.md
- doc/ics/yaml/gedling_gov_uk.yaml
- doc/source/ics.md
I have restructured the original repository to allow the iCal files to be hosted properly through GitHub pages, this updates the original docs information to point to the custom domain https://www.gbcbincalendars.co.uk. The iCal files can now be directly downloaded and referenced as proper hosted URLs, in sync with the deployment process behind the GitHub pages site.
Using GitHub raw content paths is no longer required, however they will still work as .ics paths, so it wouldn't break any existing usage.
I have tested the new ics paths within my own Home Assistant installation e.g. https://www.gbcbincalendars.co.uk/ical/gedling_borough_council_wednesday_g2_bin_schedule.ics and everything works fine.
> Update domain for Gedling Borough Council source

- custom_components/waste_collection_schedule/waste_collection_schedule/source/awn_de.py
Similar to #1333, I've seen SSL cert verification issues on the latest HassOS. After disabling verification to the `POST` requests in addition to the `GET` request that was done in the aforementioned issue, the component is successfully downloading ICS data for me again.
> awn_de: Skip cert verification on POST requests as well

- custom_components/waste_collection_schedule/waste_collection_schedule/service/AbfallnaviDe.py
- custom_components/waste_collection_schedule/waste_collection_schedule/source/abfallnavi_de.py
- doc/source/abfallnavi_de.md
noticed that strasse may be optional and not prpperly exposed to the user if street is "alle Straßen" (#2172)
> abfallnavi make street an optional parameter if only one street (like alle Straßen is returned)

- custom_components/waste_collection_schedule/waste_collection_schedule/source/ecoharmonogram_pl.py
This fixes the problem of using only last collection list, instead using all downloaded entries.
It also does not allow duplicated entries, that I noticed for my location.
> Gather cumulative entries, no duplicates.

- custom_components/waste_collection_schedule/waste_collection_schedule/source/landkreis_rhoen_grabfeld.py
- doc/source/landkreis_rhoen_grabfeld.md
The API for source "Landkreis Rhön Grabfeld" recently split the trash type "Restmüll/Gelber Sack/Biotonne" into two distinct types:
- "Restmüll/Biotonne"
- "Gelbe Tonne"
This PR updates the source and related documentation accordingly.
> fix source landkreis_rhoen_grabfeld

- doc/ics/gedling_gov_uk.md
- doc/ics/yaml/gedling_gov_uk.yaml
Minor edit to the docs. There is now an enhanced collection search tool, that directly provides the correct schedules and links to the appropriate calendar, without having to use the Gedling's search. The collection search is a proxy to the original, but enhances the data returned into a better structure for displaying on a bespoke website.
> Update gedling.gov.uk to use alternative collection search tool

- custom_components/waste_collection_schedule/waste_collection_schedule/source/highland_gov_uk.py
fixes #2196
Did not show entries where only the NextDateOld keys were populated
now: check weather any NextDateNew is populated => use 'new' dates. else: use Old instead
> fix highland_go_uk not showing entries for all UPRNS

- doc/source/gastrikeatervinnare_se.md
Fixed wrong source name in gastrikeatervinnare source (copy paste error from when I created the source)
> Fixed documentation source name error

- custom_components/waste_collection_schedule/waste_collection_schedule/source/broxbourne_gov_uk.py
Unfortunately, when I originally tested this the active month was "May" which only has three letters. It turns out that the source uses 3 letter month abbreviations as it broke as soon as the month rolled to June.
This fixes the parsing to the correct date format.
> Broxbourne - Correcting source date format handling

- custom_components/waste_collection_schedule/init_ui.py
fixes #2243
coordinator.async_config_entry_first_refresh() does excactly the same:
test if fetch is successfull and if not raise ConfigEntryNotReady
> Remove unneccesary fetch test

- hacs.json
After GUI update, there are some incompatibilities with older version of HA:
- everything since 2023.9.0 works with YAML but config_flow fails
- everything since 2023.12.0 works without any issues
> set minimum HA version to 2023.12.0

- custom_components/waste_collection_schedule/config_flow.py
- custom_components/waste_collection_schedule/translations/de.json
- custom_components/waste_collection_schedule/translations/en.json
makes it a lot easier to skip customize and sensor configuration
fixes  #2309
addresses https://github.com/mampfes/hacs_waste_collection_schedule/pull/2068#issuecomment-2197154592
prevents errors like: #2270, #2263
> config_flow simplified for basic installation

- custom_components/waste_collection_schedule/waste_collection_schedule/source/edpevent_se.py
- doc/source/edpevent_se.md
This fixes issue #2333 / discussion #2329
the output of test script: (i've removed all the outputs above for the other less relevant edpevent providers)
```bash
found 2 entries for Borås - Test1
2024-07-29 : Kärl 1, Kärl 370.0L [mdi:help]
2024-08-07 : Kärl 2, Kärl 370.0L [mdi:help]
found 2 entries for Borås - Test2
2024-08-06 : Kärl 1, Kärl 370.0L [mdi:help]
2024-08-13 : Kärl 2, Kärl 370.0L [mdi:help]
found 2 entries for Borås - Test3
2024-07-29 : Kärl 1, Kärl 370.0L [mdi:help]
2024-08-01 : Kärl 2, Kärl 370.0L [mdi:help]
```
I could not run the _update_docu_links.py since i got an error for the ahk_heidekreis_de.py source:
```bash
/waste_collection_schedule/source/ahk_heidekreis_de.py", line 82
if f"{item["houseNr"]}{item["houseNrAdd"]}" == self._house_number
^^^^^^^
SyntaxError: …
```
> Add support for Borås sweden

- custom_components/waste_collection_schedule/config_flow.py
but the source setup later will strip whitespaces at the start/end,
Currently the suggested waste types may have a space at the end or beginning,
while these will be removed later and the sensor does not match the type anymore
fixes #2325
> config_flow fetching source returns unstripped waste types

- README.md
- custom_components/waste_collection_schedule/sources.json
- custom_components/waste_collection_schedule/waste_collection_schedule/source/poriruacity_govt_nz.py
- doc/source/poriruacity_govt_nz.md
- info.md
fixes #2349
Is kinda hack reverse engineering of the Javascript done on the website
> Add Porirua City NZ

- custom_components/waste_collection_schedule/waste_collection_schedule/source/vivab_se.py
> vivab_se fix bug, where falkenberg address do not work

- README.md
- custom_components/waste_collection_schedule/sources.json
- custom_components/waste_collection_schedule/waste_collection_schedule/source/umweltverbaende_at.py
- doc/ics/gda_gv_at.md
- doc/ics/yaml/gda_gv_at.yaml
- doc/source/ics.md
- doc/source/umweltverbaende_at.md
GDA Amstetten provides a ICS for each address in the district, selectable via a website.
The official homepage moved from https://amstetten.umweltverbaende.at to https://gda.gv.at.
I kept the EXTRA_INFO value in `umweltverbaende_at.py` as GDA Amstetten is still part of NÖ Umweltverbände but maintains its own homepage as listed in https://www.umweltverbaende.at/verbaende.
> Add generic ICS for GDA Amstetten (gda.gv.at)

- custom_components/waste_collection_schedule/waste_collection_schedule/source/wokingham_gov_uk.py
If a collection is today, the web page says for example, "Today 13/08/2024" rather than "Tuesday 13/08/2024". So update waste_date to just look at the date itself and not the text part in the span text.
Fixes:
```
2024-08-13 19:06:17.747 ERROR (SyncWorker_7) [waste_collection_schedule.source_shell] fetch failed for source Wokingham Borough Council:
Traceback (most recent call last):
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch
entries = self._source.fetch()
^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/wokingham_gov_uk.py", line 109, in fetch
date=datetime.strptime(waste_date, "%A %d/%m/%Y").date(),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> Wokingham source includes "Today" rather than day name

- custom_components/waste_collection_schedule/waste_collection_schedule/source/southkesteven_gov_uk.py
Source was fetching for a hard-coded ID: changed to use the configuration value.
Date format was wrong in one of the cases: corrected
Added support for garden waste collections, which have different text (instead of a link like "What goes in the green bin" we get a list of items, the first of which is "Leaves")
> South Kesteven UK: fixes (fetch for configured id, date format); support garden waste collections

- custom_components/waste_collection_schedule/init_ui.py
- custom_components/waste_collection_schedule/init_yaml.py
- custom_components/waste_collection_schedule/service.py
- custom_components/waste_collection_schedule/waste_collection_api.py
- custom_components/waste_collection_schedule/wcs_coordinator.py
Readds the fetch_data service as it was not present for GUI configuariton / did nothing on GUI sources when using both (YAML and GUI)
I modified the service function and moved this to it's own file so we can import it in inti_yaml and init_ui and only have this one function. It works with YAML and GUI configuration (also mixed)
I moved WCSCoordinator and WasteCollectionAPI into ints own file, to prevent weird import loops 
As I was on this I added some typehints
fixes #2469
fixes #2294
> Add fetch_data service for GUI configuration

- .github/workflows/hassfest.yaml
- .github/workflows/validate.yaml
Update the version of the github actions used to fix the nodejs deprecation/replacement annotation.
This PR also updates the used python version to 3.12 as it is the version currently used by HomeAssistant.
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
> Update GitHub workflow

- README.md
- custom_components/waste_collection_schedule/sources.json
- custom_components/waste_collection_schedule/waste_collection_schedule/source/sica_lu.py
- doc/source/sica_lu.md
- info.md
Add source for municipalities in Luxembourg served by [SICA](https://www.sica.lu) 
`sica_lu.py` and `sica_lu.md` were created as per documentation.
`update_docu_links.py` was run and updated `README.md` and `info.md` are included.
Output from test run:
```
./test_sources.py -s sica_lu
Testing source sica_lu ...
found 67 entries for Bertrange
found 67 entries for Capellen
found 66 entries for Garnich
found 67 entries for Holzem
found 68 entries for Kehlen
found 68 entries for Koerich
found 66 entries for Kopstal
found 68 entries for Mamer
found 67 entries for Septfontaines
found 69 entries for Steinfort
```
This source adds the following municipalities / towns:
- Bertrange
- Capellen
- Garnich
- Holzem
- Kehlen
- Koerich
- Kopstal
- Mamer
- Septfontaines
- Steinfort
The following …
> Adding sica lu

- custom_components/waste_collection_schedule/waste_collection_schedule/source/oxford_gov_uk.py
For whatever reason, Oxford City are inconsistent in their date string format:
> Refuse Next Collection: xx xx Sep 2024
> Recycling Next Collection: xx xx August 2024
This PR tries both formats.
Terminal output shows before and after
```
vscode ➜ /workspaces/hacs_waste_collection_schedule $ python ./custom_components/waste_collection_schedule/waste_collection_schedule/test/test_sources.py -s oxford_gov_uk
Testing source oxford_gov_uk ...
Magdalen Road failed: time data 'Thursday 05 Sep 2024' does not match format '%A %d %B %Y'
found 4 entries for Oliver Road (brown bin too)
vscode ➜ /workspaces/hacs_waste_collection_schedule $ python ./custom_components/waste_collection_schedule/waste_collection_schedule/test/test_sources.py -s oxford_gov_uk
Testing source oxford_gov_uk ...
found 3 …
```
> Oxford city: Support shortened month name

- custom_components/waste_collection_schedule/manifest.json
Trying to figure out if HACS the still offers an update to 2.2.0
> version bump manifest.json before release

- custom_components/waste_collection_schedule/waste_collection_schedule/source/real_luzern_ch.py
fixes #2595
from discussion #2592
> fix real_luzern_ch

- requirements.txt
icalevents 0.1.28 is broken, setting dependency to 0.1.29 to force an upgrade on all affected instances
> #2643 upgrade icalevents to 0.1.29

- custom_components/waste_collection_schedule/waste_collection_schedule/source/victoriapark_wa_gov_au.py
Fix for issue raised in  #2684 
before fix:
```bash
Wednesday failed: time data '31 Aug Sep 2024' does not match format '%d %b %Y'
found 5 entries for Park Centre (Thurs)
2024-09-19 : Rubbish [mdi:trash-can]
2024-09-19 : Recycling [mdi:recycle]
2024-09-26 : Go Bin [mdi:leaf]
2024-07-06 : Green Waste [mdi:tree]
2024-08-17 : Bulk Waste [mdi:microwave]
Aqualife (Thurs) failed: time data '31 Aug Sep 2024' does not match format '%d %b %Y'
```
after fix:
```bash
found 5 entries for Wednesday
2024-09-18 : Rubbish [mdi:trash-can]
2024-09-18 : Recycling [mdi:recycle]
2024-09-25 : Go Bin [mdi:leaf]
2024-07-20 : Green Waste [mdi:tree]
2024-08-31 : Bulk Waste [mdi:microwave]
found 5 entries for Park Centre (Thurs)
2024-09-19 : Rubbish [mdi:trash-can]
2024-09-19 : Recycling [mdi:recycle]
2024-09-26 : …
```
> Fix: victoriapark_wa_gov_au

- custom_components/waste_collection_schedule/calendar.py
uid was missing from events being added to the local calendar. This leads to other systems (eg. Google calendar) not being able to import the calendar due to all events having the same uid of 'None'
https://github.com/mampfes/hacs_waste_collection_schedule/issues/1479 and https://github.com/mampfes/hacs_waste_collection_schedule/issues/1105 are blocked without a change such as this
With this change, something like https://github.com/JosephAbbey/ha_calendar_export can be used to export events to other systems
> Added uid to events added to calendar

- custom_components/waste_collection_schedule/waste_collection_schedule/source/dunedin_govt_nz.py
- doc/source/dunedin_govt_nz.md
It is a much easier to use API, as it directly returns all the needed collection dates
This will show the new bin types now
They use a hard coded API key so we might need to change it if they ever change this key
> Dunedin_govt_nz move to the APP API

- custom_components/waste_collection_schedule/waste_collection_schedule/source/sica_lu.py
- doc/source/sica_lu.md
As discussed in #2569 i migrated the sica_lu source to the new API.
Output of test run:
```
Testing source sica_lu ...
found 103 entries for Habscht
found 104 entries for Steinfort
```
> New sica lu api

- custom_components/waste_collection_schedule/waste_collection_schedule/source/kuringgai_nsw_gov_au.py
Fixes #2846 
Not sure how, but the space characters in the  in the ICON-MAP and ROUNDS dict keys had been removed.
```
Testing source kuringgai_nsw_gov_au ...
found 3 entries for randomHouse
2024-10-16 : General Waste [mdi:trash-can]
2024-10-23 : Recycling [mdi:recycle]
2024-10-16 : Green Waste [mdi:leaf]
found 3 entries for randomAppartment
2024-10-18 : General Waste [mdi:trash-can]
2024-10-18 : Recycling [mdi:recycle]
2024-10-18 : Green Waste [mdi:leaf]
found 3 entries for randomMultiunit
2024-10-17 : General Waste [mdi:trash-can]
2024-10-17 : Recycling [mdi:recycle]
2024-10-17 : Green Waste [mdi:leaf]
found 3 entries for 1 Latona St
2024-10-22 : General Waste [mdi:trash-can]
2024-10-22 : Recycling [mdi:recycle]
2024-10-22 : Green Waste [mdi:leaf]
found 3 entries for 1A Latona St …
```
> Fix: Ku-Ring_gai

- custom_components/waste_collection_schedule/waste_collection_schedule/test/test_sources.py
- doc/contributing_source.md
This makes it easy to verify, that a source saving some arguments works as excpected on future fetch calls
> add argument double to test_sources script to verify that fetch() resulst are consistant with future calls of fetch()

- custom_components/waste_collection_schedule/translations/de.json
- custom_components/waste_collection_schedule/translations/en.json
- custom_components/waste_collection_schedule/waste_collection_schedule/source/rbwm_gov_uk.py
Still works as expected:
```
$ ./test_sources.py -s rbwm_gov_uk -l -i
Testing source rbwm_gov_uk ...
found 10 entries for Windsor 1
2024-10-22 : Recycling [mdi:recycle]
2024-10-22 : Refuse [mdi:trash-can]
2024-10-29 : Garden Waste [mdi:leaf]
2024-10-29 : Recycling [mdi:recycle]
2024-11-05 : Recycling [mdi:recycle]
2024-11-05 : Refuse [mdi:trash-can]
2024-11-12 : Garden Waste [mdi:leaf]
2024-11-12 : Recycling [mdi:recycle]
2024-11-19 : Recycling [mdi:recycle]
2024-11-19 : Refuse [mdi:trash-can]
found 10 entries for Windsor 2
2024-10-22 : Recycling [mdi:recycle]
2024-10-22 : Refuse [mdi:trash-can]
2024-10-29 : Garden Waste [mdi:leaf]
2024-10-29 : Recycling [mdi:recycle]
2024-11-05 : Recycling [mdi:recycle]
2024-11-05 : Refuse [mdi:trash-can]
2024-11-12 : Garden Waste [mdi:leaf]
2024-11-12 : …
```
> Fix postcode parameter translation for Windsor and Maidenhead, UK source

- custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py
old error message would also show source not found even though the import error is caused in the source not from importing the source
will improve debuggin for cases like #2907
> source shell improve error message when a import inside the source script fails

- custom_components/waste_collection_schedule/manifest.json
Old approach may download an old version of icalevents and the newest (>=6.0.0) yet incompatible version of icalendar
addresses #2907 and simmilar issues
> fix dependency issue with icalendar and icalevents

- custom_components/waste_collection_schedule/waste_collection_schedule/source/gfa_lueneburg_de.py
- doc/source/gfa_lueneburg_de.md
Fixes: #2926 
- House number was not set correctly
- Deleted a unneeded file write
- Fixed the documentation
```
Testing source gfa_lueneburg_de ...
found 21 entries for Andervenne Am Gallenberg
found 19 entries for Wendish Evern Kückenbrook 5 A
```
> Fix: GFA Lüneburg - set house number correctly

- custom_components/waste_collection_schedule/waste_collection_schedule/source/warszawa19115_pl.py
warszawa19115_pl has recently changed the field name for waste schedule from `harmonogramy` to `harmonogramyZ`.
* Changed the field name + small refactoring
* Added check the field is not null (to avoid an exception)
Test run results:
```
Testing source warszawa19115_pl ...
found 5 entries for Street Name
found 5 entries for Geolocation ID
```
> Fix warszawa19115_pl response schedule new field name

- custom_components/waste_collection_schedule/waste_collection_schedule/source/static.py
Validation for the static schedule is wrong. It works when specifying weekdays as strings, but no when specifying weekdays as dictionary
> Fix static schedule params validation

- doc/faq.md
There was a typo in the next shedules FAQ.
first event_index = 0, 
second event_index = 1, 
third event_index = 3
Updated the event_index of the third one to 2.
Thanks for the wonderful implementation!
> Update Typo in faq.md

- custom_components/waste_collection_schedule/config_flow.py
When sources have blocking calls in the __init__ method, a warning is shown when adding the source via the UI mode. Potential exceptions on init are overwritten with the blocking warning.
Example: #2889 
This PR moves the initialization into the hass.async_add_executor_job
> fix: Prevent blocking calls in source __init__ methods (GUI mode)

- custom_components/waste_collection_schedule/waste_collection_schedule/source/bracknell_forest_gov_uk.py
Bracknell Forest decided to change `General Waste` to `General waste`, breaking this integration. This change implements checking in a case-insensitive way.
Test results:
Before:
```
$ ./test_sources.py -s bracknell_forest_gov_uk
Testing source bracknell_forest_gov_uk ...
found 2 entries for 44 Kennel Lane
found 2 entries for 28 Kennel Lane
found 2 entries for 32 Ashbourne
found 3 entries for 1 Acacia Avenue
```
After:
```
$ ./test_sources.py -s bracknell_forest_gov_uk
Testing source bracknell_forest_gov_uk ...
found 3 entries for 44 Kennel Lane
found 3 entries for 28 Kennel Lane
found 3 entries for 32 Ashbourne
found 4 entries for 1 Acacia Avenue
```
> Fix Bracknell Forest Collections

- custom_components/waste_collection_schedule/init_yaml.py
The "day_offset" setting is missing in the yaml-schema. Looks like that got lost around june-2nd.
fixes: #3027
> Fix: Day_Offset missing in yaml schema

- custom_components/waste_collection_schedule/waste_collection_schedule/source/juneavfall_se.py
This PR fixes #2996.
Added handling for `"NextWastePickup":"v47 Nov 2024",`  v47 is the week number.
Added special test case
Tests:
```
testing source juneavfall_se ...
found 3 entries for Storgatan 12
2024-11-25 : FNI Kärl 1
2024-12-09 : FNI Kärl 2
2025-04-23 : Trädgårdsavfall
found 2 entries for Smedjegatan 20
2024-11-18 : Matavfall
2024-11-18 : Restavfall
found 7 entries for Västra Ubbarp 20, Barnarp
2024-11-15 : FNI Kärl 1
2024-11-25 : FNI Kärl 2
2024-11-15 : Restavfall
2024-11-15 : Restavfall
2024-11-15 : Matavfall
2024-11-15 : Matavfall
2024-11-18 : Slam
```
> Fix: Junaavfall_se date format parsing

- custom_components/waste_collection_schedule/translations/de.json
- custom_components/waste_collection_schedule/translations/en.json
- custom_components/waste_collection_schedule/translations/it.json
- custom_components/waste_collection_schedule/waste_collection_schedule/source/islington_gov_uk.py
- doc/source/islington_gov_uk.md
This PR is to fix #3040.
Breaking change: Postcode is a new configuration requirement.
Tasks:
- Page structure changed
- Postcode is required now
Tests:
```
Testing source islington_gov_uk ...
found 1 entries for Test_001
2024-11-20 : Mixed dry recycling
2024-11-21 : Non-recyclable rubbish
2024-11-21 : Mixed dry recycling
2024-11-21 : Food waste recycling
2024-11-21 : Non-recyclable rubbish
2024-11-21 : Mixed dry recycling
2024-11-21 : Food waste recycling
```
> Fix: islington_gov_uk - Page structure changed

- custom_components/waste_collection_schedule/waste_collection_schedule/source/awg_de.py
Problem: The ssl config of wastemanagement.awg.de has changed and the cert-chain is [incomplete](https://www.ssllabs.com/ssltest/analyze.html?d=wastemanagement.awg.de).
Solution: Switch to legacy_session
Fixes: #3052 
Tests:
```
Testing source awg_de ...
found 16 entries for Achslach Aign 1 
found 24 entries for Böbrach Bärnerauweg 10A
found 40 entries for Am Bäckergütl 1, 94094 Malching
```
> Fix: Switch Awg_de to legacy session handling

- custom_components/waste_collection_schedule/waste_collection_schedule/source/abfallwirtschaft_pforzheim_de.py
It seems that the container names were changed and thus the test cases fail. This commit fixes this change. All tests run successfully afterwards.
All container types of the source are selected with this change, including specialties like christmas tree collection in early January.
If this is not correct please let me know.
Thanks!
Fixes #3055
> Fix renamed containers in source abfallwirtschaft_pforzheim_de

- custom_components/waste_collection_schedule/waste_collection_schedule/source/warwickdc_gov_uk.py
Fixes: #3081 
Error: Exceptional collection are shown with a different date format
Solution: Additional date parsing
Test:
```
Testing source warwickdc_gov_uk ...
found 16 entries for Test_001
found 16 entries for Test_002
found 16 entries for Test_003
```
> Fix: Warwickdc_gov_uk date parsing

- custom_components/waste_collection_schedule/waste_collection_schedule/source/republicservices_com.py
I commented on #1430 that I was having a similar issue. After some self doubt I decided to create a pull request. Below is my comment from the bug for convenience. 
After I made the comment I called and spoke with a customer service rep and the confirmed what was on their site and my understanding of the issue. 
> After a lot of reviewing the Republic Waste site I found this:
> 
> > Holiday schedules vary by service location. Residential collection may be delayed due to these and other holidays:
> > 
> > Memorial Day
> > July 4th
> > Labor Day
> > Thanksgiving Day
> > Christmas Day
> > New Year's Day
> > 
> > Holidays typically push our residential pickup schedules back one day with regular schedules resuming the following > week.
> 
> Currently, the integration is showing my garbage …
> Fix holiday schedule for republicservices

- custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_emsland_de.py
- doc/source/awb_emsland_de.md
This PR tries to fix https://github.com/mampfes/hacs_waste_collection_schedule/issues/3131 by adding a new (optional) parameter, in which the corresponding request period can be entered to override the default request period.
Therefore, for the specific issue, you can enter "Jahresübersicht 2024" to get the waste collection schedule for the current year.
> AWB Emsland request this AND next years data instead of only next years

- custom_components/waste_collection_schedule/waste_collection_schedule/source/republicservices_com.py
During testing, `rs_json` was loading as a single item array with `None` as the item. This fix adds a check to ensure the item is truthy before proceeding to other checks. This change was tested and verified locally.
Fixes #3152
> adding check if item is True in list

- custom_components/waste_collection_schedule/waste_collection_schedule/source/salford_gov_uk.py
Salford have recently updated their site. Now requires a user-agent in the header otherwise gets a 403 response. Also needed slight amend to check for finding relevant data on page.
Fixes https://github.com/mampfes/hacs_waste_collection_schedule/issues/3208
> Fix Salford_gov_uk source

- custom_components/waste_collection_schedule/waste_collection_schedule/source/awm_muenchen_de.py
At the end of the year, awm_muenchen_de offers two calendar links (2024 and 2025).
Instead of fetching the first one, fetch all offered calendars.
Solves the problem that only the 2024 schedule was fetched.
> Fetch all calendars offered by awm_muenchen_de

- custom_components/waste_collection_schedule/waste_collection_schedule/source/stirling_wa_gov_au.py
Fixes #3215 
```bash
Testing source stirling_wa_gov_au ...
found 4 entries for -31.9034183 115.8320855
2024-12-25 : Red [mdi:trash-can]
2024-12-25 : Yellow [mdi:recycle]
2025-01-01 : Green [mdi:leaf]
2024-11-04 : GreenVerge [mdi:pine-tree]
found 4 entries for -31.878331, 115.815553
2024-12-25 : Red [mdi:trash-can]
2025-01-01 : Yellow [mdi:recycle]
2024-12-25 : Green [mdi:leaf]
2024-10-21 : GreenVerge [mdi:pine-tree]
```
> Fix: Stirling WA api url

- custom_components/waste_collection_schedule/waste_collection_schedule/source/merton_gov_uk.py
- doc/source/merton_gov_uk.md
Also updated the test cases as they don't seem to be valid IDs any more.
Tested with `python custom_components/waste_collection_schedule/waste_collection_schedule/test/test_sources.py -s merton_gov_uk -lit` and the tests now pass successfully
> fix: Merton UK has changed the format of the dates

- custom_components/waste_collection_schedule/waste_collection_schedule/source/darebin_vic_gov_au.py
Fixes #3321
original api url:
```bash
Testing source darebin_vic_gov_au ...
274 Gower Street PRESTON 3072 failed: 'NoneType' object is not subscriptable
```
updated api url:
```bash
Testing source darebin_vic_gov_au ...
found 156 entries for 274 Gower Street PRESTON 3072
found 156 entries for 116 HAROLD STREET THORNBURY 3071
```
> Fix: Darebin, Australia

- custom_components/waste_collection_schedule/waste_collection_schedule/source/wokingham_gov_uk.py
Fixes #3320 
updated to take account for changed schedules during Christmas period.
```bash
Testing source wokingham_gov_uk ...
found 7 entries for Test_001
2025-01-02 : Household Waste (Christmas Schedule) [mdi:trash-can]
2024-12-24 : Recycling (Christmas Schedule) [mdi:recycle]
2025-01-08 : Recycling (Christmas Schedule) [mdi:recycle]
2024-12-24 : Food Waste (Christmas Schedule) [mdi:food]
2025-01-02 : Food Waste (Christmas Schedule) [mdi:food]
2025-01-08 : Food Waste (Christmas Schedule) [mdi:food]
2025-01-03 : Garden Waste (Christmas Schedule) [mdi:leaf]
found 7 entries for Test_002
2024-12-24 : Household Waste (Christmas Schedule) [mdi:trash-can]
2025-01-08 : Household Waste (Christmas Schedule) [mdi:trash-can]
2025-01-02 : Recycling (Christmas Schedule) [mdi:recycle]
2024-12-24 : …
```
> Fix: Wokingham, UK

- custom_components/waste_collection_schedule/waste_collection_schedule/source/tauranga_govt_nz.py
Bugfix -  Add a missing else clause which is causing new year pickups to show in the incorrect year.
> Fix tauranga_govt_nz date

- custom_components/waste_collection_schedule/waste_collection_schedule/source/conwy_gov_uk.py
- doc/source/conwy_gov_uk.md
It appears the endpoint used to retrieve data for Conwy County Borough Council has recently been updated. This PR updates the provider to use the new endpoint.
> Update Conwy County Borough Council endpoint

- custom_components/waste_collection_schedule/waste_collection_schedule/source/abfall_havelland_de.py
Abfall Havelland has changed its API. It`s now even simpler to retrieve the data.
I created two specific testcases (one with a more complex street name) and they where ok.
Would be nice if you could integrate this PR very soon because i see UNKNOWN in my HomeAssistant otherwise :/
Tests:
Testing source abfall_havelland_de ...
found 78 entries for Wustermark Drosselgasse
found 77 entries for Milow Friedhofstr.
found 79 entries for Falkensee Ahornstr.                     <--- new testcase
found 78 entries for Falkensee complex street name   <--- new testcase
> Fix for new API for abfall_havelland_de

- custom_components/waste_collection_schedule/waste_collection_schedule/source/alw_wf_de.py
The ALW Wolfenbüttel API has started to return every entry twice (since 2025-01-01). This causes this integration to also add them to the calender and sesnors twice.
This PR deduplicates the returned entries by creating a "hash" (haha) from the timestamp + bin type so we add every bin type and timestamp combination only once.
> Deduplicate entries in ALW-WF

- custom_components/waste_collection_schedule/waste_collection_schedule/source/nottingham_city_gov_uk.py
Nottingham City API sometimes give multiple dates for bins, particularly just after collection date. Locally, it makes sense to only use the smallest of these dates as we want the NEXT collection only.
Here's an example API response which is causing the issue:
```json
{
"uprn": "200001405145",
"address": "FLAT 2 3 CAMERON STREET",
"postcode": "NG5 2HS",
"binTypes": [
"CommunalRecycling",
"Waste",
"Garden",
"Recycling"
],
"nextCollections": [
{
"collectionType": "Waste",
"collectionDate": "2025-01-07T07:00:00",
"collectionDay": "Tuesday"
},
{
"collectionType": "Recycling",
"collectionDate": "2025-01-14T07:00:00",
"collectionDay": "Tuesday"
},
{
"collectionType": "Recycling",
"collectionDate": "2400-01-11T00:00:00",
"collectionDay": "Tuesday"
},
{
"collectionType": "Garden", …
```
> Refactor Nottingham City to pull only one date per bin type

- custom_components/waste_collection_schedule/waste_collection_schedule/source/heidelberg_de.py
- doc/source/heidelberg_de.md
During inspection of the failed CI pipeline on my last pull request (#3497 / #3498), I recognized that using `CONFIG_FLOW_TYPES` with a public method call has unexpected side effects. Whenever the file is being imported (e.g., by running `test_sources.py` or `update_docu_links.py`), the `Source.get_available_streets()` method is being called in order to fill the `CONFIG_FLOW_TYPES` dictionary even without access to values of the dictionary at all. This leads to unnecessary and maybe excessive calls to the public API. [It's visible in this pipeline run here](https://github.com/mampfes/hacs_waste_collection_schedule/actions/runs/12674155047/job/35323279820#step:7:12).
First, I thought about answering calls from both test/debug scripts with an empty list using this workaround:
```python …
```
> Heidelberg: Revert pre-fill of streets and ignore timezone on Christmas tree collection parse

- doc/ics/seon_ch.md
- doc/ics/yaml/seon_ch.yaml
Update with new calendar url for 2025
> Update calendar url for Seon (Switzerland)

- .pre-commit-config.yaml
- custom_components/waste_collection_schedule/waste_collection_schedule/service/CitiesAppsCom.py
- custom_components/waste_collection_schedule/waste_collection_schedule/source/citiesapps_com.py
- custom_components/waste_collection_schedule/waste_collection_schedule/wizard/citiesapps_com.py
Fixes #3460
Updates citiesapp related code to use v2 api.
Also updates wizard to be compatible.
@mampfes Thank you and all the contributors for your work on this integration. Its much appreciated. Also note that I am not a python developer, so any suggestions are welcome :)
> citiesapps_com: Update to citiesapp v2 api

- custom_components/waste_collection_schedule/waste_collection_schedule/source/kingston_gov_uk.py
Date parsing is now in its own function because it has grown in complexity. Kingston has stopped including years in their dates, so we have to add them manually and account for year boundaries.
> Fix date parsing for kingston.gov.uk. Fixes #3224

- custom_components/waste_collection_schedule/waste_collection_schedule/source/opendata_bordeauxmetropole_fr.py
There are a few cities without geoshape, which means that all the city is impacted by the scheduling (like Villenave d'Ornon).
It has been tested on my HA instance
> fix(Bordeaux-metropole/Villenave d'ornon): Allow cities without geo_shape

- custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_bad_kreuznach_de.py
fixes #3381
The API returns calendar entries from 2024. An extended `until` for calculation is necessary to get entries for 2025.
According to the [documentation](https://dateutil.readthedocs.io/en/stable/rrule.html) `until` and `count` are deprecated when used together, so I removed the count completely.
> fix missing data for AWB Bad Kreuznach

- custom_components/waste_collection_schedule/waste_collection_schedule/source/poznan_pl.py
Updating poznan source to create calendar's events for all available dates
> Updating poznan source

- custom_components/waste_collection_schedule/waste_collection_schedule/source/oslokommune_no.py
- doc/source/oslokommune_no.md
Fixes #3759
OsloKommune documentation was showing references to args that were not used, as well as a confusing reference to both street_id and street_code. This looks like it was due to  oslokommune_no being based on the code for minrenovasjon_no which does use those args and the differences hadn't been cleaned up in the documentation.
> Fix: oslokommune

- custom_components/waste_collection_schedule/waste_collection_schedule/source/ecoharmonogram_pl.py
fixes a logical error, where it loop over every side when side_matcher is not provided and it would return on first found side when side_matcher is provided
that meant that if side_matcher didn't match against first found side,
there would be no entries found
one schedule provider in test cases also updated names for sides, so I updated this test accordingly
> ecoharmonogram_pl: return if sides_matcher is empty when creating entries in loop

- custom_components/waste_collection_schedule/waste_collection_schedule/source/recyclecoach_com.py
This updates the `schedule_url` of RecycleCoach source to a new schedule endpoint. The existing endpoint returns `This pattern does not exist in database` and inspecting the requests of my municipality's online schedule shows calls to this new endpoint.
Should fix #3784 and #3764
> Update `schedule_url` for recyclecoach source

- custom_components/waste_collection_schedule/waste_collection_schedule/source/north_ayrshire_gov_uk.py
Fixes #3906
Test_004  shows partial collections are now handled without errors.
```bash
Testing source north_ayrshire_gov_uk ...
2025-03-19 : Blue [mdi:recycle]
2025-04-02 : Grey [mdi:trash-can]
2025-03-26 : Purple [mdi:glass-fragile]
2025-03-27 : Brown [mdi:leaf]
2025-03-27 : Blue [mdi:recycle]
2025-03-20 : Grey [mdi:trash-can]
2025-04-03 : Purple [mdi:glass-fragile]
2025-03-26 : Brown [mdi:leaf]
found 4 entries for Test_003
2025-03-21 : Blue [mdi:recycle]
2025-04-04 : Grey [mdi:trash-can]
2025-03-28 : Purple [mdi:glass-fragile]
2025-03-27 : Brown [mdi:leaf]
found 2 entries for Test_004
2025-03-19 : Blue [mdi:recycle]
2025-03-26 : Grey [mdi:trash-can]
```
> Fix: North Ayrshire

- custom_components/waste_collection_schedule/waste_collection_schedule/source/oxford_gov_uk.py
csrf token no longer present on a separate landing page, so now have to load the form page and submit that for the csrf token.
After this change, I've re-run the tests and they now pass:
```
$ git log --oneline | head -n1
e590679d Fix oxford_gov_uk
$ python test_sources.py -s oxford_gov_uk -t
Testing source oxford_gov_uk ...
found 6 entries for Magdalen Road
found 8 entries for Oliver Road (brown bin too)
```
> Fix oxford_gov_uk

- custom_components/waste_collection_schedule/waste_collection_schedule/source/aha_region_de.py
The website of Aha had some changes. Because of the changes you can't get the adresses of all streets anymore, so you have to hand over the first letter of your street.
Furthermore the "ladeort" field has no ID anymore but a name, so we needed to change that.
3 of 5 tests are succesfull, the other tests fail because there are no ICS for these adresses anymore.
Probably fixes #3455 and #3995.
> Fix for Aha website change.

- custom_components/waste_collection_schedule/waste_collection_schedule/source/swale_gov_uk.py
Adds functionality to handle "tomorrow" and "today" being returned by Swale Council. Fixes https://github.com/mampfes/hacs_waste_collection_schedule/issues/4016
> Fix: #4016 Swale Council return non-calendar dates.

- custom_components/waste_collection_schedule/waste_collection_schedule/source/nsomerset_gov_uk.py
Simple PR for adding Garden Waste item, newly added to the council data table
> Add Garden Waste Support for North Somerset

- custom_components/waste_collection_schedule/waste_collection_schedule/source/nsomerset_gov_uk.py
collection.get("Following collection date") may be None 
fixes second test case
> fix: nsomester_gov_uk failing if Following collection date is not provided

- custom_components/waste_collection_schedule/waste_collection_schedule/source/royalgreenwich_gov_uk.py
The page with alternative collection dates during bank holidays: https://www.royalgreenwich.gov.uk/recycling-and-rubbish/bins-and-collections/bank-holiday-collection-dates
> Added support for bank holiday overrides in royalgreenwich_gov_uk

- custom_components/waste_collection_schedule/waste_collection_schedule/source/wigan_gov_uk.py
Wigan council appear to have updated some of their tags, causing the script to fail when trying to find the next collection date.
The fix involves a small change to adjust `dateWrapper-next` to `dateWrap-next`.
> Wigan Council: Fix parsing by changing dateWrapper-next to dateWrap-next

- custom_components/waste_collection_schedule/waste_collection_schedule/source/ilrifiutologo_it.py
Porting the fix to #3561 proposed by @iuginP here https://github.com/mampfes/hacs_waste_collection_schedule/issues/3561#issuecomment-2932658908 .
Source IlRifiutologo was not working without the fix.
> fix: Source IlRifiutologo not respond anymore

- custom_components/waste_collection_schedule/waste_collection_schedule/source/royalgreenwich_gov_uk.py
Yesterday I started receiving 403s while accessing URLs from Royal Greenwich Council. This seems fixes it (at least for now).
```bash
$ curl https://www.royalgreenwich.gov.uk/site/custom_scripts/repo/apps/waste-collection/new2023/ajax-response-uprn.php -A 'python-requests/2.32.3'
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>
```
```bash
$ curl https://www.royalgreenwich.gov.uk/site/custom_scripts/repo/apps/waste-collection/new2023/ajax-response-uprn.php -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:139.0) Gecko/20100101 Firefox/139.0'
ADDRESS_NOT_SET
```
> Added passing user-agent to bypass firewall for royalgreenwich

- custom_components/waste_collection_schedule/waste_collection_schedule/source/rbwm_gov_uk.py
add headers to RBWM request to prevent 403 error.
> Fix 403 error for Windsor and Maidenhead

- custom_components/waste_collection_schedule/waste_collection_schedule/source/blaby_gov_uk.py
Fixes #4382 
Use `verify=False` to negate the SSL verification error.
```bash
Testing source blaby_gov_uk ...
2025-07-11 : Refuse [mdi:trash-can]
2025-07-25 : Refuse [mdi:trash-can]
2025-07-18 : Recycling [mdi:recycle]
2025-08-01 : Recycling [mdi:recycle]
found 6 entries for Test_002
2025-07-18 : Refuse [mdi:trash-can]
2025-08-01 : Refuse [mdi:trash-can]
2025-07-11 : Recycling [mdi:recycle]
2025-07-25 : Recycling [mdi:recycle]
2025-07-11 : Garden [mdi:leaf]
2025-07-25 : Garden [mdi:leaf]
found 4 entries for Test_003
2025-07-09 : Refuse [mdi:trash-can]
2025-07-23 : Refuse [mdi:trash-can]
2025-07-16 : Recycling [mdi:recycle]
2025-07-30 : Recycling [mdi:recycle]
```
> Fix: Blaby, UK

- custom_components/waste_collection_schedule/waste_collection_schedule/source/chesterfield_gov_uk.py
Fixes #4396
First request needed verify=False added, other requests already were already using that setting.
```bash
Testing source chesterfield_gov_uk ...
2025-07-11 : Domestic Recycling [mdi:recycle]
2025-07-11 : Domestic Paid Garden [mdi:leaf]
2025-07-18 : Domestic Refuse [mdi:trash-can]
found 2 entries for Test_002
2025-07-23 : Domestic Recycling [mdi:recycle]
2025-07-16 : Domestic Refuse [mdi:trash-can]
2025-07-21 : Domestic Refuse [mdi:trash-can]
2025-07-14 : Domestic Recycling [mdi:recycle]
2025-07-14 : Domestic Paid Garden [mdi:leaf]
found 2 entries for Test_004
2025-07-15 : Domestic Refuse [mdi:trash-can]
2025-07-22 : Domestic Recycling [mdi:recycle]
```
> Fix: Chesterfield, UK

- README.md
- custom_components/waste_collection_schedule/waste_collection_schedule/source/solihull_gov_uk.py
Fixes #4411 
Minor updates after looking into the above issue.
```
Testing source solihull_gov_uk ...
found 5 entries for 100070994046
2025-07-09 : Mixed Recycling [mdi:recycle]
2025-07-23 : Mixed Recycling [mdi:recycle]
2025-07-02 : Garden Waste [mdi:leaf]
2025-07-09 : Household Waste [mdi:trash-can]
2025-07-16 : Household Waste [mdi:trash-can]
found 5 entries for 200003821723, Predict
2025-07-07 : Mixed Recycling [mdi:recycle]
2025-07-21 : Mixed Recycling [mdi:recycle]
2025-06-30 : Garden Waste [mdi:leaf]
2025-07-07 : Household Waste [mdi:trash-can]
2025-07-14 : Household Waste [mdi:trash-can]
found 6 entries for New Garden Waste Subscription Service
2025-07-10 : Mixed Recycling [mdi:recycle]
2025-07-24 : Mixed Recycling [mdi:recycle]
2025-07-03 : Garden Waste [mdi:leaf]
2025-07-17 : …
```
> Update: Solihull, UK

- custom_components/waste_collection_schedule/waste_collection_schedule/source/swale_gov_uk.py
Fixes #4427 
Update payload keys for form submissions
```bash
Testing source swale_gov_uk ...
found 4 entries for Swale House
2025-07-17 : Food [mdi:food-apple]
2025-07-17 : Recycling [mdi:recycle]
2025-07-24 : Food [mdi:food-apple]
2025-07-24 : Refuse [mdi:trash-can]
found 5 entries for 1 Harrier Drive
2025-07-17 : Food [mdi:food-apple]
2025-07-17 : Refuse [mdi:trash-can]
2025-07-17 : Garden [mdi:leaf]
2025-07-24 : Food [mdi:food-apple]
2025-07-24 : Recycling [mdi:recycle]
found 7 entries for garden waste test
2025-07-17 : Food [mdi:food-apple]
2025-07-17 : Refuse [mdi:trash-can]
2025-07-17 : Garden [mdi:leaf]
2025-07-17 : Garden [mdi:leaf]
2025-07-17 : Garden [mdi:leaf]
2025-07-24 : Food [mdi:food-apple]
2025-07-24 : Recycling [mdi:recycle]
```
> Fix: Swale, UK

- doc/contributing_ics.md
The actual fix is to execute pytest in `hacs_waste_collection_schedule`, not in `waste_collection_schedule`.
Other than that I changed the formatting of the paragraph. In markdown documents, you usually start each sentence on a new line. This is easier when reviewing changes. The rendered document looks the same.
> Fix: doc where to execute pytest

- custom_components/waste_collection_schedule/waste_collection_schedule/source/blacktown_nsw_gov_au.py
Fixes #4434
Replaced requote_uri  with params
```bash
Testing source blacktown_nsw_gov_au ...
found 2 entries for Plumpton Marketplace
2025-07-21 : General Waste [trash-can]
2025-07-28 : Recycling [mdi:recycle]
found 2 entries for Rooty Hill Tennis & Squash Centre
2025-07-21 : General Waste [trash-can]
2025-07-28 : Recycling [mdi:recycle]
found 2 entries for Workers Blacktown
2025-07-23 : General Waste [trash-can]
2025-07-23 : Recycling [mdi:recycle]
found 2 entries for Hythe St
2025-07-21 : General Waste [trash-can]
2025-07-28 : Recycling [mdi:recycle]
found 3 entries for Issue#4434
2025-07-18 : General Waste [trash-can]
2025-07-18 : Recycling [mdi:recycle]
2025-07-18 : Food and Garden Waste [mdi:trash-can]
```
> Fix: Blacktown, AUS

- custom_components/waste_collection_schedule/waste_collection_schedule/source/publidata_fr.py
Handles new “24/7” and days with a hyphen in between them instead of a comma.
> Fix Publidata,FR (#4341)

- custom_components/waste_collection_schedule/waste_collection_schedule/source/ashford_gov_uk.py
Fixes #4417
Forces request to use TLSv1.2 & AES256-SHA256 to match Ashford's server, otherwise
`SSL: UNEXPECTED_EOF_WHILE_READING` errors occur.
```bash
Testing source ashford_gov_uk ...
Forcing requests to use legacy TLSv1.2 & AES256-SHA256 to match ashford.gov.uk website
found 3 entries for 100060796052
2025-08-01 : Household Refuse (grey bin / black sacks) [mdi:trash-can]
2025-07-25 : Recycling (green bin / clear sacks) [mdi:recycle]
2025-07-25 : Food Waste (black container with orange lid) [mdi:food]
Forcing requests to use legacy TLSv1.2 & AES256-SHA256 to match ashford.gov.uk website
found 3 entries for 100060780440
2025-07-25 : Household Refuse (grey bin / black sacks) [mdi:trash-can]
2025-08-01 : Recycling (green bin / clear sacks) [mdi:recycle]
2025-07-25 : Food Waste (black …
```
> Fix: Ashford, UK

- custom_components/waste_collection_schedule/waste_collection_schedule/source/northherts_gov_uk.py
This pull request fixes issue #4145 
North Hertfordshire changed providers which broke the previous API integration.
The new portal is similar to `croydon_gov_uk.py` with a few minor adjustments.
I have kept the original parameters as to not to break existing configurations, although address search and matching works differently in this implementation.
```
$ python3 ./custom_components/waste_collection_schedule/waste_collection_schedule/test/test_sources.py -s northherts_gov_uk
Testing source northherts_gov_uk ...
found 5 entries for Example
found 5 entries for Example No Postcode Space
```
Ensured `pytest` still passes
> Fix North Hertfordshire, UK after council API change

- custom_components/waste_collection_schedule/waste_collection_schedule/source/awn_de.py
Some time this week the `awn_de` iCal download broke. It seems to be related to an upstream change of the `ApplicationName` parameter.
> Fix: AWN ApplicationName for iCal download

- custom_components/waste_collection_schedule/waste_collection_schedule/source/eastherts_gov_uk.py
Updated East Herts source following website changes implemented after the #4475 PR was merged.
Accounts for API url/endpoint changes - see PR discussion for details.
```bash
Testing source eastherts_gov_uk ...
Used postcode to find an approximate uprn (10023089734). Update config with property uprn for more accurate results.
found 4 entries for Example
2025-08-22 : Recycling [mdi:recycle]
2025-08-30 : Paper [mdi:newspaper]
2025-08-22 : Food [mdi:food]
2025-08-27 : Refuse [mdi:trash-can]
Used postcode to find an approximate uprn (10023089734). Update config with property uprn for more accurate results.
found 4 entries for Example No Postcode Space
2025-08-22 : Recycling [mdi:recycle]
2025-08-30 : Paper [mdi:newspaper]
2025-08-22 : Food [mdi:food]
2025-08-27 : Refuse [mdi:trash-can]
found 5 …
```
> Update: East Herts, UK

- custom_components/waste_collection_schedule/waste_collection_schedule/source/rushmoor_gov_uk.py
I don't know what or when this happened, but since last week my integration stopped working.  Appears that the API is returning properly formatted json.  
I cloned locally, and same issue happened, after the change, tests pass:
```
Testing source rushmoor_gov_uk ...
found 7 entries for GU14
2025-08-21 : Refuse [mdi:trash-can]
2025-08-14 : Recycling [mdi:recycle]
2025-08-21 : GardenWaste [mdi:leaf]
2025-08-14 : FoodWaste [mdi:food-apple]
2025-08-07 : Refuse [mdi:trash-can]
2025-08-07 : GardenWaste [mdi:leaf]
2025-08-07 : FoodWaste [mdi:food-apple]
```
Was failing with:
```
fetch failed for source Rushmoor Borough Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, 
in fetch entries: …
```
> Fix for Rushmoor

- custom_components/waste_collection_schedule/waste_collection_schedule/service/EcoHarmonogramPL.py
- doc/source/ecoharmonogram_pl.md
This PR adds a new app to the `Ecoharmonogram` service that contains the city of `Opole`.
> Add `opole` app to the ecoharmonogram service

- custom_components/waste_collection_schedule/waste_collection_schedule/source/glasgow_gov_uk.py
they changed the url's capitalization after a cyber incident, breaking it
> Glasgow, UK Update the URL to the new one

- custom_components/waste_collection_schedule/waste_collection_schedule/source/north_norfolk_gov_uk.py
Fixes #4684 
Now handles empty list return when property doesn't subscribe to one of the waste types.
```bash
Testing source north_norfolk_gov_uk ...
found 2 entries for Test_001
2025-09-11 : Grey bin [mdi:trash-can]
2025-09-18 : Green bin [mdi:recycle]
found 2 entries for Test_002
2025-09-11 : Green bin [mdi:recycle]
2025-09-18 : Grey bin [mdi:trash-can]
2025-09-11 : Grey bin [mdi:trash-can]
2025-09-16 : Brown bin [mdi:leaf]
2025-09-18 : Green bin [mdi:recycle]
````
> handle non-subscribed bin collection

- custom_components/waste_collection_schedule/waste_collection_schedule/source/edlitz_at.py
Fixes #4639 
```yaml
Testing source edlitz_at ...
found 10 entries for TestSource
2025-09-17 : Restmüll [mdi:trash-can]
2025-09-24 : Biomüllabfuhr [mdi:food]
2025-09-26 : Gelber Sack [mdi:recycle-variant]
2025-10-08 : Biomüllabfuhr [mdi:food]
2025-10-15 : Restmüll [mdi:trash-can]
2025-10-22 : Biomüllabfuhr [mdi:food]
2025-10-24 : Gelber Sack [mdi:recycle-variant]
2025-11-05 : Biomüllabfuhr [mdi:food]
2025-11-05 : Papier Tonne [mdi:newspaper]
2025-11-12 : Restmüll [mdi:trash-can]
found 10 entries for IgnoredArgument
2025-09-17 : Restmüll [mdi:trash-can]
2025-09-24 : Biomüllabfuhr [mdi:food]
2025-09-26 : Gelber Sack [mdi:recycle-variant]
2025-10-08 : Biomüllabfuhr [mdi:food]
2025-10-15 : Restmüll [mdi:trash-can]
2025-10-22 : Biomüllabfuhr [mdi:food]
2025-10-24 : Gelber Sack …
```
> fixed wrong source and icons for edlitz_at
