mampfes/hacs_waste_collection_schedule

custom_components/waste_collection_schedule/package/wizard/abfall_io.py
See https://www.awg-info.de/index.php?id=59 - ICS/CSV generator directly queries the abfall_io api
=> Add district "Calw" to abfall_io wizard

README.md, custom_components/waste_collection_schedule/package/source/pgh_st.py, doc/pgh_st.md
PGH.ST serves Pittsburgh, PA, USA.
=> Add source for PGH.ST (incl. url-quote fix)

README.md, custom_components/waste_collection_schedule/package/source/seattle_gov.py, doc/source/seattle_gov.md
Added Seattle Public Utilities service provider for Seattle, Washington, USA.
=> Add source for Seattle Public Utilities

README.md, custom_components/waste_collection_schedule/package/source/brisbane_qld_gov_au.py, doc/source/brisbane_qld_gov_au.md, info.md
Added Brisbane City Council in Queensland, Australia as a source.
=> Add source for Brisbane City Council

README.md, custom_components/waste_collection_schedule/__init__.py, custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/jumomind_de.py, custom_components/waste_collection_schedule/waste_collection_schedule/test/test_sources.py, custom_components/waste_collection_schedule/waste_collection_schedule/wizard/jumomind_de.py, doc/source/abfall_io.md, doc/source/abfall_kreis_tuebingen_de.md, doc/source/abfallnavi_de.md, doc/source/awbkoeln_de.md, doc/source/bsr_de.md, doc/source/jumomind_de.md, doc/source/muellmax_de.md, doc/source/stadtreinigung_hamburg.md, doc/source/stuttgart_de.md, info.md
- add support for mymuell app to jumomind (thanks to bjoernwolter)
- fix missing renames of package in documentation and comments
- cleanup importlib handling in scraper
=> Jumomind de

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/rh_entsorgung_de.py, doc/source/rh_entsorgung_de.md, info.md
This pull request adds [rh-entsorgung.de](https://www.rh-entsorgung.de/de/Service/Abfallkalender/) as source
=> Add rh-entsorgung source and documentation

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/sector27_de.py, doc/source/sector27_de.md, info.md
add a regional provider in the region Kreis Recklinghausen.
available for at least the cities of Datteln, Marl, Oer-Erkenschwick.
sadly you can get the arguments for the function only by "hacking" the webpage. see sector27_de.md
=> add sector27

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/was_wolfsburg_de.py, doc/source/was_wolfsburg_de.md, info.md
=> add source WAS-Wolfsburg.de

.gitignore, README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/berlin_recycling_de.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/bsr_de.py, custom_components/waste_collection_schedule/waste_collection_schedule/test/test_sources.py, doc/source/berlin_recycling_de.md, info.md
add source berlin-recycling.de
fix #62
=> Berlin recycling

custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py, doc/source/ics.md
=> Fix capitalize in ics

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/hygea_be.py, doc/source/hygea_be.md, info.md
=> Add hygea be

custom_components/waste_collection_schedule/waste_collection_schedule/source/seattle_gov.py
I stepped through and found the issues were just down to two URL's that had changed
=> Simple fix for Seattle Public Utilities

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/stonnington_vic_gov_au.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/thehills_nsw_gov_au.py, doc/source/stonnington_vic_gov_au.md, info.md
This is a major council area in inner city Melbourne, Victoria, Australia.
=> Add source for stonnington.vic.gov.au

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/stonnington_vic_gov_au.py, info.md
add source for stonnington citz council, Australia
=> Stonnington

doc/source/ics.md
Hey there,
the integration process is pretty straight forward for this page, e.g.
```yaml
waste_collection_schedule:
sources:
- name: ics
args:
url: https://www.muellabfuhr-deutschland.de/weimarer-land/location/0c595d1c-2cbc-4d19-ae81-df5318fceb7c/pickups/ical.ics
```
However, as the main offering is an app, there is no direct link from the main page https://www.muellabfuhr-deutschland.de to region's local page like https://www.muellabfuhr-deutschland.de/weimarer-land .
The user needs to find this link via the web page of their authority.
----
Adding the below, so that search engines can guide users here :)
These I was able to find:
* https://www.muellabfuhr-deutschland.de/burgenlandkreis
* https://www.muellabfuhr-deutschland.de/saalekreis
* …
=> Add muellabfuhr-deutschland to ics support list

custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py
caused by next year handing and therefore only appears in december
fix #116
=> fix fault in ics scraper

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/sysav_se.py, doc/source/sysav_se.md, info.md
Added new integration for Sysav in Sweden.
=> Added new provider Sysav_se

custom_components/waste_collection_schedule/waste_collection_schedule/source/abfall_zollernalbkreis_de.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/lindau_ch.py, doc/source/lindau_ch.md
Added source for Abfall Lindau  CH,
Added icons to abfall_zollernalbkreis_de
=> Added lindau_ch, added icons to zollernalbkreis_de

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/awr_de.py, doc/source/awr_de.md, info.md
New source: Abfallwirtschaft Rendsburg
=> add source awr_de

custom_components/waste_collection_schedule/waste_collection_schedule/wizard/abfall_io.py
Thanks for that cool integration. 
I added Landkreis Heilbronn in abfall.io wizard.
=> add Landkreis Heilbronn in abfall.io wizard

custom_components/waste_collection_schedule/waste_collection_schedule/wizard/abfall_io.py
Added key for service provider eBe Essen in abfall.io wizard
=> ebe Essen Service Provider

custom_components/waste_collection_schedule/calendar.py
When looking through the code, I stumbled across this. Pretty sure, that it is just missing curly brackets.
Would be relevant if multiple scrapers are used with the same date & collection types.
Thanks for the cool integration, very much liked how easy it was to implement an additional source!
=> Add missing brackets

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/ccc_govt_nz.py, doc/source/ccc_govt_nz.md, info.md
Also makes the other New Zealand plugins in the documentation more readable
=> Add support for Christchurch City Council, NZ

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/york_gov_uk.py, doc/source/york_gov_uk.md, info.md
Adds waste collection for the city of York, UK.
=> Adds York, UK source

doc/source/ics.md
Hi,
I've added documentation for using the ics-file from service provider Limburg.net in Belgium with your HA-extension.
Greetings,
d3claes
=> Update for ics.md

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/cambridge_gov_uk.py, doc/source/cambridge_gov_uk.md
Cambridge UK added as source.
Documentation and code added.
=> Add cambridge_gov_uk as source

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/colchester_gov_uk.py, doc/source/colchester_gov_uk.md, info.md
Add support for waste removal the borough of Colchester, United Kingdom
=> Add support for Colchester.gov.uk for United Kingdom

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_bad_kreuznach_de.py, doc/source/awb_bad_kreuznach_de.md, info.md
=> add source for AWB Bad Kreuznach

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/wellington_govt_nz.py, doc/source/wellington_govt_nz.md, info.md
Using ICS file from council website to ingest data
=> Adding Source for Wellington City Council New Zealand

doc/source/ics.md
Splitted list of German counties by Bundesland and added Bodenseekreis (list and example configuration)
=> Update ics.md by adding Bodenseekreis in Germany

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/bmv_at.py, doc/source/bmv_at.md, doc/source/data_umweltprofis_at.md, info.md
add source for bmv.at
fix #189
=> add source for bmv.at

custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py, doc/source/ics.md
fix #195
add support to disable ssl certificate check for ics
=> add support to disable ssl certificate verification for ics

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/aw_harburg.py, doc/source/aw_harburg_de.md
I added the waste source for Landkreis Harburg in Niedersachsen Germany.
The source can be found here: https://www.landkreis-harburg.de/bauen-umwelt/abfallwirtschaft/abfallkalender/
I hope I did everything according to the instructions and it can be merged.
=> Added new data source for Harburg Germany

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_oldenburg_de.py, doc/source/awb_oldenburg_de.md, info.md
This PR adds a source for [AWB Stadt Oldenburg](https://services.oldenburg.de/index.php?id=430&no_cache=1).
```bash
$ python test_sources.py -s awb_oldenburg_de
Testing source awb_oldenburg_de ...
found 69 entries for Polizeiinspektion Oldenburg
```
=> Added source for AWB Oldenburg (Oldb)

custom_components/waste_collection_schedule/calendar.py, custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py
=> add unique id for calendar

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_lm_de.py, doc/source/awb_lm_de.md, info.md
Nothing much to say, this PR adds support for AWB Limburg-Weilburg.
=> Add support for AWB Limburg-Weilburg

custom_components/waste_collection_schedule/waste_collection_schedule/source/ccc_govt_nz.py
Fixes errors that occurred after the URL was shifted to a new cloud service.
=> Christchurch City Council: URL change

custom_components/waste_collection_schedule/waste_collection_schedule/source/ipswich_qld_gov_au.py, doc/source/ipswich_qld_gov_au.md
=> Ipswich City Council, QLD, Australia Source

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/a_region_ch.py, doc/source/a_region_ch.md, info.md
=> add source for a_region_ch

custom_components/waste_collection_schedule/waste_collection_schedule/source/a_region_ch.py, doc/source/a_region_ch.md
=> fix missing data for a_region_ch

custom_components/waste_collection_schedule/calendar.py
https://developers.home-assistant.io/blog/2022/04/18/calendar-data-model
fix #222
=> adapt to new calendar data model

custom_components/waste_collection_schedule/waste_collection_schedule/source/campbelltown_nsw_gov_au.py, doc/source/campbelltown_nsw_gov_au.md
Added basic support for Campbelltown NSW Australia.
=> Add source Campbelltown.nsw.gov.au

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/warszawa19115_pl.py, doc/source/warszawa19115_pl.md, info.md
Added support for Warsaw, Poland https://warszawa19115.pl/harmonogramy-wywozu-odpadow
I based on Banyule City Council integrations, so big thanks to the author!
=> Added support for warszawa19115.pl

custom_components/waste_collection_schedule/waste_collection_schedule/wizard/abfall_io.py
=> add Goettingen to abfall_io wizard

custom_components/waste_collection_schedule/waste_collection_schedule/source/bmv_at.py
some cities (Rattersdorf) requires to query ort + strasse + hausnummer
fix #224
=> fix bmv_at

custom_components/waste_collection_schedule/waste_collection_schedule/source/rh_entsorgung_de.py, doc/source/rh_entsorgung_de.md
=> fix rh_entsorgung_de

custom_components/waste_collection_schedule/waste_collection_schedule/source/nawma_sa_gov_au.py
=> fix nawma_sa_gov_au

custom_components/waste_collection_schedule/waste_collection_schedule/source/scambs_gov_uk.py, doc/source/ics.md, doc/source/scambs_gov_uk.md, info.md
Added South Cambridgeshire UK service (scambs_gov_uk).
Added iCal example for South Cambs.
=> South Cambs service added

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/peterborough_gov_uk.py, doc/source/peterborough_gov_uk.md
Added Peterborough City Council UK service
=> Adding Peterborough UK source

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/belmont_wa_gov_au.py, doc/source/belmont_wa_gov_au.md, info.md
Added source belmont_wa_gov_au.py
Added docs belmont_wa_gov_au.md
Updated info.md and README.md with Belmont City Council details
Apologies if this is not up to scratch, I'm not a developer by any stretch of the imagination.
=> Add source belmont_wa_gov_au

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/cheshire_east_gov_uk.py, doc/source/cheshire_east_gov_uk.md, info.md
Added Cheshire East Council UK service
=> [feat] Add Cheshire East Source

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/nsomerset_gov_uk.py, doc/source/nsomerset_gov_uk.md, info.md
Adding of collection data for North Somerset council, covering Clevedon, Nailsea, Portishead and Weston super Mare.
=> Add North Somerset council

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/wakefield_gov_uk.py, doc/source/wakefield_gov_uk.md, info.md
=> [feat] Add Wakefield Council

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/alw_wf_de.py, doc/source/alw_wf_de.md, info.md
This adds support for https://www.alw-wf.de/.
They don't have a public API but they do have an iOS and Android app. They have "authentication" with the API there, but the credentials are not really secure und hardcoded into the app, so whatever.
=> Add ALW Wolfenbüttel as source

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/fccenvironment_co_uk.py, doc/source/fccenvironment_co_uk.md, info.md
=> Add source fccenvironment_co_uk

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/derby_gov_uk.py, doc/source/derby_gov_uk.md, info.md
Happy to make any changes/improvements if needed. Mostly based mine on the Nottingham one.
=> Add support for Derby City Council (UK)

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/chesterfield_gov_uk.py, doc/source/chesterfield_gov_uk.md, info.md
=> New Source: Chesterfield_gov_uk

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/republicservices_com.py, doc/source/republicservices_com.md, info.md
Adding source for a relatively large (I think) USA municipal waste service.  This should work for Commercial, Residential, Industrial, and Contracted service through Republic Services.
Feel free to correct mistakes, propose fixes, improvements, best practices, etc.  I'm a novice, so happy to fix my poor code :-).
Cheers!
DeadEnd
=> Add source for Republic Services (USA)

custom_components/waste_collection_schedule/waste_collection_schedule/source/chesterfield_gov_uk.py
=> convert uprn to string to allow also numerical uprn's

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/wiltshire_gov_uk.py, doc/source/wiltshire_gov_uk.md, info.md
Wiltshire Council added as a source. 
Documentation and code submitted as per guidelines.
Thanks for the plugin :)
=> Add wiltshire_gov_uk as source

custom_components/waste_collection_schedule/calendar.py
=> Fixed resolving of upcomig events

custom_components/waste_collection_schedule/waste_collection_schedule/source/warszawa19115_pl.py
=> Postpone getting geolocation until first fetch

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/ssam_se.py, doc/source/ssam_se.md, info.md
Added source for swedish waste collection company SSAM
=> Added source for SSAM.se

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/westberks_gov_uk.py, doc/source/westberks_gov_uk.md, info.md
Source and documentation added to support West Berkshire Council.
I am *not* a Python dev, so I'm sure there are better ways to do some of the things I've done here.  Happy to learn if anyone wants to improve it!
=> Add support for West Berkshire Council (westberks.gov.uk)

custom_components/waste_collection_schedule/waste_collection_schedule/source/minrenovasjon_no.py, doc/source/minrenovasjon_no.md
=> Plugin for Min Renovasjon in Norway

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/innerwest_nsw_gov_au.py, doc/source/innerwest_nsw_gov_au.md
This adds the Inner West Council (NSW) and is modeled off Brisbane City Council as they share the same API backend.
=> Adding Inner West Council

custom_components/waste_collection_schedule/waste_collection_schedule/wizard/abfall_io.py
=> Add ASO OHZ to AbfallIO

custom_components/waste_collection_schedule/waste_collection_schedule/source/ssam_se.py
Certain addresses were not working properly. Updated code to reflect these different waste types and schedules.
=> Source SSAM; Fixed problem with certain addresses

custom_components/waste_collection_schedule/waste_collection_schedule/source/recycleapp_be.py
This code resolve this problem #337
=> Resolve the bug #337

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/rushmoor_gov_uk.py, doc/source/rushmoor_gov_uk.md, info.md
https://www.rushmoor.gov.uk/recycling-rubbish-and-environment/bins-and-recycling/bin-collection-day-finder/
=> Add support for Rushmoor Borough Council, UK

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/manchester_uk.py, doc/source/manchester_uk.md, info.md
Adds support for manchester city council's page.
https://www.manchester.gov.uk/bincollections/
=> Add source for manchester city council.

custom_components/waste_collection_schedule/calendar.py
=> remove python 3.10 type hinting

doc/source/aw_harburg_de.md
=> fix typo in aw_harbug_de docu

custom_components/waste_collection_schedule/waste_collection_schedule/source/oslokommune_no.py, doc/source/oslokommune_no.md
=> New Source: Oslo Kommune

custom_components/waste_collection_schedule/waste_collection_schedule/source/minrenovasjon_no.py
=> minrenovasjon_no: Add default icon for waste types.

custom_components/waste_collection_schedule/waste_collection_schedule/source/abfall_io.py, custom_components/waste_collection_schedule/waste_collection_schedule/wizard/abfall_io.py
Added the key to the wizard and a test case.
Hopefully I haven't forgotten anything else.
Thanks for this great project, finally I can throw away this "AbfallApp" 😁
=> Added "LK Traunstein" to abfall.io script

doc/source/ics.md
I have tweaked various elements to integrate Bromley Council.
This is my first change to a github post, so apologies if I have done anything breaking
=> Update ics.md to add London Borough of Bromley

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/stadt_willich_de.py, doc/source/stadt_willich_de.md, info.md
Adds support for stadt-willich.de waste collection dates
https://www.stadt-willich.de/de/dienstleistungen/abfallkalender-als-ical-datei/
=> Add source for Stadt Willich

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/muenchenstein_ch.py, doc/source/muenchenstein_ch.md, info.md
Added a new source and documentation for Münchenstein, Switzerland.
=> Added source for Muenchenstein, BL, Switzerland

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/wyndham_vic_gov_au.py, doc/source/wyndham_vic_gov_au.md, info.md
Added new source for Wyndham City Council, Melbourne, Australia
=> Added source for Wyndham City Council

custom_components/waste_collection_schedule/waste_collection_schedule/source/oslokommune_no.py, doc/source/oslokommune_no.md
I updated the documentation to reflect all required fields, and added more dynamic fetching of waste collection types so that paper collection was supported too.
=> Update Oslo Kommune integration

custom_components/waste_collection_schedule/waste_collection_schedule/source/wuerzburg_de.py
Fixed HTTP 403 for wuerzburg_de source-url: added missing HTTP header (user-agent)
=> Fix wuerzburg_de

custom_components/waste_collection_schedule/waste_collection_schedule/source/wiltshire_gov_uk.py
Provides a small fix for Wiltshire Council, where the string doesn't always exactly match.
=> Fix up for Wiltshire council to consider non-glass recycling

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/waipa_nz.py, doc/source/waipa_nz.md, info.md
(this is my first time creating a pull request, please let me know if I messed anything up!)
Added Waipa District Council source. Tests pass without issue.
=> add Waipa District, New Zealand

.gitignore, README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/newcastle_gov_uk.py, doc/source/newcastle_gov_uk.md, info.md, requirements.txt
Add a new source for Newcastle-Upon-Tyne, UK
=> Add Newcastle-Upon-Tyne

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/awn_de.py, doc/source/awn_de.md, info.md
=> Add support for Abfallwirtschaft Neckar-Odenwald-Kreis

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/landkreis_rhoen_grabfeld.py, doc/source/landkreis_rhoen_grabfeld.md, info.md
Add integration for Landkreis Rhön Grabfeld.
Tested via test-script and also runs perfectly fine on my local home-assistant instance
=> add integration for Landkreis Rhön Grabfeld

custom_components/waste_collection_schedule/waste_collection_schedule/source/warszawa19115_pl.py
It appears there was an update that broke this integration.
This fixes it.
=> Fix for request returning no data for warszawa19115

custom_components/waste_collection_schedule/waste_collection_schedule/source/chesterfield_gov_uk.py
Pre-emptive fix for continued discussion in #386
Attempts to deal with periodically change in fwuid parameter
=> Further update to chesterfield_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/richmondshire_gov_uk.py
Apologies if this is problematic, my first pull request.
=> Add source for Richmondshire, North Yorkshire

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/bielefeld_de.py, doc/source/bielefeld_de.md, info.md
[Online-Abfallkalender](https://anwendungen.bielefeld.de/WasteManagementBielefeld/WasteManagementServlet?SubmitAction=wasteDisposalServices) from Stadt Bielefeld Umweltbetrieb
=> Add Stadt Bielefeld

doc/source/ics.md
Sample config wasn't valid yaml.
Offtopic: Great integration, thanks for building/maintaining this!!!
=> Fix sample configuration for Recollect ics config

custom_components/waste_collection_schedule/waste_collection_schedule/source/aucklandcouncil_govt_nz.py
Addresses Issue #423
Code snippet added to work around **SSL error unsafe legacy renegotiation disabled** server error.
Original code commented out, but not removed, just in case there is a need to revert at some point.
=> Updated aucklandcouncil_govt_nz

custom_components/waste_collection_schedule/waste_collection_schedule/service/EcoHarmonogramPL.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/ecoharmonogram_pl.py, doc/source/ecoharmonogram_pl.md
This MR allows user to narrow down town by district. Seems that there are towns with the same names supported by ecoharmonogram.
Signed-off-by: pawel.hulek <pawelhulek@gmail.com>
=> adds districts to ecoharmogram

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/canadabay_nsw_gov_au.py, doc/source/canadabay_nsw_gov_au.md, info.md
Copy paste of Inner West Council (https://github.com/mampfes/hacs_waste_collection_schedule/pull/320) and Brisbane City Council (https://github.com/mampfes/hacs_waste_collection_schedule/pull/34) as they share the same API backend.
Also formatted the markdown table.
=> Add City of Canada Bay Council

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/walsall_gov_uk.py, doc/source/walsall_gov_uk.md, info.md
addresses Issue #432
```
python3 test_sources.py -s walsall_gov_uk -l -i
Testing source walsall_gov_uk ...
found 11 entries for test001
2022-11-14: GREEN [mdi:recycle]
2022-11-28: GREEN [mdi:recycle]
2022-12-12: GREEN [mdi:recycle]
2022-12-27: GREEN [mdi:recycle]
2023-01-09: GREEN [mdi:recycle]
2022-11-14: GREY [mdi:trash-can]
2022-11-28: GREY [mdi:trash-can]
2022-12-12: GREY [mdi:trash-can]
2022-12-27: GREY [mdi:trash-can]
2023-01-09: GREY [mdi:trash-can]
2022-11-14: BROWN [mdi:leaf]
found 12 entries for test002
2022-11-09: GREEN [mdi:recycle]
2022-11-23: GREEN [mdi:recycle]
2022-12-07: GREEN [mdi:recycle]
2022-12-21: GREEN [mdi:recycle]
2023-01-04: GREEN [mdi:recycle]
2022-11-09: GREY [mdi:trash-can]
2022-11-23: GREY [mdi:trash-can]
2022-12-07: GREY [mdi:trash-can]
2022-12-21: GREY …
```
=> walsall_gov_uk source added

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/sheffield_gov_uk.py, doc/source/sheffield_gov_uk.md, info.md
Added source for Sheffield City Council with support for all bin types.
I never got Dev Containers working to properly test, however I have manually added this as a source to my instance of Home Assistant/HACS and tested fine.
=> Added source for Sheffield City Council

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/abfalltermine_forchheim_de.py, doc/source/abfalltermine_forchheim_de.md, info.md
Source for City and Landkreis of Forchheim
=> Add source for Landkreis Forchheim, Germany

custom_components/waste_collection_schedule/waste_collection_schedule/service/EcoHarmonogramPL.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/ecoharmonogram_pl.py
Added community for ecoharmonogram based on https://github.com/m4tek/hacs_waste_collection_schedule
Example using:
```
waste_collection_schedule:
sources:
- name: ecoharmonogram_pl
args:
community: "108"
town: "Gdańsk"
street: "Jabłoniowa"
house_number: "55"
```
=> Added community for ecoharmonogram.

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/maroondah_vic_gov_au.py, doc/source/maroondah_vic_gov_au.md, info.md
New source for the Maroondah City Council.
=> Added source for Maroondah City Council VIC AU

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/lewisham_gov_uk.py, doc/source/lewisham_gov_uk.md, info.md
Added source for London Borough of Lewisham with support for all bin types and valid test cases.
=> Added source for London Borough of Lewisham

doc/source/ics.md
=> add docu for fes frankfurt to ics.md

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/regioentsorgung_de.py, doc/source/regioentsorgung_de.md, info.md
This adds another data source `regioentsorgung`, corresponding to https://regioentsorgung.de/service/abfallkalender/
=> Add `regioentsorgung_de` source

custom_components/waste_collection_schedule/waste_collection_schedule/source/canterbury_gov_uk.py
Canterbury Gov have changed the responses given by their API. This fixes that change
=> canterbury_gov_uk: Fix Broken API requests

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/tewkesbury_gov_uk.py, doc/source/tewkesbury_gov_uk.md, info.md
Added source for Tewkesbury Borough Council using the public API endpoint used by their website.
=> Added support for waste collection for Tewkesbury Borough Council (UK)

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/horowhenua_govt_nz.py, doc/source/horowhenua_govt_nz.md, info.md
* This largely takes previous work from @dt215git for the kuringgai_nsw_gov_au source which seems to use the same backend API as this district (among other AU districts also present in this repository)
* This provider currently only provides Rubbish/Garbage and Recycling services.
=> Add schedule for Horowhenua District, New Zealand

custom_components/waste_collection_schedule/waste_collection_schedule/source/aw_harburg_de.py
During year transistion, there are 2 links instead of one available. In addition, the ical for the upcoming year seams to be temporary invalid.
fix #410
=> add support for multiple links to aw_harburg_de

custom_components/waste_collection_schedule/waste_collection_schedule/source/abfall_io.py
=> remove logging output for abfall_io

custom_components/waste_collection_schedule/waste_collection_schedule/source/data_umweltprofis_at.py, doc/source/data_umweltprofis_at.md
=> add XML support for umweltprofis_at

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/staedteservice_de.py, doc/source/staedteservice_de.md, info.md
Added the staedteservice_de.py and staedteservice_de.md
Updated the README.md and info.md
=> Added Städteservice Raunheim Rüsselsheim

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/wermelskirchen_de.py, doc/source/wermelskirchen_de.md, info.md
Loads ics from Wermelskirchen city website.
=> Added source for wermelskirchen

custom_components/waste_collection_schedule/waste_collection_schedule/source/canadabay_nsw_gov_au.py, doc/source/canadabay_nsw_gov_au.md
To match the website also retrieving 1 year of data.
=> canadabay_nsw_gov_au: retrieve 1 year of data

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/middlesbrough_gov_uk.py, doc/source/middlesbrough_gov_uk.md, info.md
Added source and documentation for Middlesbrough council - UK
Currently uses the UPRN.
=> Added support for Middlesbrough Council - UK

README.md, doc/source/tewkesbury_gov_uk.md, info.md
Couple of tweaks I noticed after my last pull request went in for this source, nothing major!
=> Minor tweaks to tewkesbury_gov_uk.md, and fixed MD header level for Norway

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/kingston_gov_uk.py, doc/source/kingston_gov_uk.md, info.md
Added source and documentation for Middlesbrough council - UK
Currently uses the UPRN.
=> Added Support for Kingston Council - UK

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/korneuburg_stadtservice_at.py, doc/source/korneuburg_stadtservice_at.md, info.md
Added support Korneuburg in Austria
=> added Source for Korneuburg [Austria]

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/stadtservice_bruehl_de.py, doc/source/stadtservice_bruehl_de.md, info.md
Add Source for StadtService Brühl
Update stadtservice_bruehl_de.md
=> Add StadtService Brühl

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/bracknell_forest_gov_uk.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/braintree_gov_uk.py, doc/source/bracknell_forest_gov_uk.md, doc/source/braintree_gov_uk.md, info.md
Added source and documentation for Bracknell Forest, UK and Braintree, UK. Uses Post Code and House Number.
=> Add Bracknell Forest, UK & Braintree, UK.

custom_components/waste_collection_schedule/waste_collection_schedule/service/SSLError.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/aucklandcouncil_govt_nz.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/bielefeld_de.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/ccc_govt_nz.py
Uses SSLError workaround from aucklandcouncil_govt_nz to address the same error in this script.
```bash
test_sources.py -s ccc_govt_nz -i -l
Testing source ccc_govt_nz ...
found 3 entries for 53 Hereford Street
2022-12-27: Recycle [None]
2023-01-03: Garbage [None]
2022-12-27: Organic [None]
```
=> SSLError fix for Christchurch City Council

custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_es_de.py
AWB-ES uses one ics file per year, now every linked ics for a given location gets pulled
=> awb_es_de: now using all available ics

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/hvcgroep_nl.py, doc/source/hvcgroep_nl.md, info.md
=> improve hvcgroep source to support other dutch services

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/nillumbik_vic_gov_au.py, doc/source/nillumbik_vic_gov_au.md, info.md
Another addition, this one was based on the Melton source as both councils use the same website back end.
=> Added source for Nillumbik VIC AU

custom_components/waste_collection_schedule/waste_collection_schedule/source/srvatervinning_se.py, doc/page_template.md
#487 
```text
./test_sources.py -s srvatervinning_se -l
Testing source srvatervinning_se ...
found 30 entries for Skansvägen
2023-01-03: Restavfall
2023-01-10: Restavfall
2023-01-17: Restavfall
2023-01-03: Restavfall
2023-01-10: Restavfall
2023-01-17: Restavfall
2023-01-03: Restavfall
2023-01-10: Restavfall
2023-01-17: Restavfall
2023-01-03: Restavfall
2023-01-10: Restavfall
2023-01-17: Restavfall
2023-01-03: Restavfall
2023-01-10: Restavfall
2023-01-17: Restavfall
2023-01-03: Restavfall
2023-01-10: Restavfall
2023-01-17: Restavfall
2023-01-03: Restavfall
2023-01-10: Restavfall
2023-01-17: Restavfall
2023-01-03: Restavfall
2023-01-10: Restavfall
2023-01-17: Restavfall
2023-01-03: Restavfall
2023-01-10: Restavfall
2023-01-17: Restavfall
2023-01-03: Restavfall
2023-01-10: Restavfall …
```
=> add test cases to srvatervinning_se

README.md
republic_services isn't throwing a JSONDecoderError for me
```bash
test_sources.py -s republicservices_com -i -l
Testing source republicservices_com ...
found 1 entries for Scott Country Clerk
2023-01-06: Solid Waste [mdi:trash-can]
found 1 entries for Branch County Clerk
2023-01-02: Solid Waste [mdi:trash-can]
```
Have removed in from the Know Issues part of the README.
Also corrected a badge url.
=> republicservice_com

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/goldcoast_qld_gov_au.py, doc/source/goldcoast_qld_gov_au.md, info.md
Adding service provider for Gold Coast QLD Australia.
There is no direct API that can be queried and had to use what was available to me. (Which is HTML parsing)
Updated:
- README.md
- info.md
Added:
- /doc/source/goldcoast_qld_gov_au.md
- /custom_components/waste_collection_schedule/waste_collection_schedule/source/goldcoast_qld_gov_au.py
Test Results
```
Testing source goldcoast_qld_gov_au ...
found 3 entries for MovieWorx
found 3 entries for The Henchman
found 3 entries for Pie Pie
```
=> Adding goldcoast qld gov au

doc/source/c_trace_de.md
added a (imo) better help, how to get the service-name and other parameters for c-trace
=> added service and more help

doc/source/berlin_recycling_de.md
=> Fix documentation for berlin_recycling_de

README.md
=> add HA hangs to known issues

custom_components/waste_collection_schedule/waste_collection_schedule/source/stadtservice_bruehl_de.py
=> split waste types into separate entities

custom_components/waste_collection_schedule/waste_collection_schedule/source/goldcoast_qld_gov_au.py
Fix for #559 - Line 27 had the wrong parameters, not sure how this made it through the tests!
=> Fix: #559 - goldcoast_qld_gov_au definition for street_address was incorrect

custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py, doc/source/ics.md
=> add docu for ICS file

doc/source/art_trier_de.md
While copying a readme file for my new source I found a typo in another one. 🤣
=> art_trier_de: fix copy paste error in readme

custom_components/waste_collection_schedule/waste_collection_schedule/source/stadtreinigung_leipzig_de.py
=> fix stadtreinigung_leipzig_de

custom_components/waste_collection_schedule/waste_collection_schedule/source/awido_de.py
=> accept numerical house numbers for awido_de

custom_components/waste_collection_schedule/waste_collection_schedule/source/c_trace_de.py
WZV uses id 0 for "Restabfall"
fix #585
=> fix missing waste type for c_trace_de

doc/source/ics.md
documentation for custom header use case "Abfallwirtschaftsbetrieb Ilm-Kreis"
See https://github.com/mampfes/hacs_waste_collection_schedule/issues/586
=> Ics custom header use case documentation

custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py, doc/source/ics.md
=> add support for custom headers to ics source

doc/source/centralbedfordshire_gov_uk.md
in response to https://github.com/mampfes/hacs_waste_collection_schedule/issues/627
=> fixing centralbedfordshire_gov_uk documentation

custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py
=> handle ICS files with UTF byte order mark (BOM) correctly

custom_components/waste_collection_schedule/waste_collection_schedule/source/tekniskaverken_se.py
=> Updated source for Linköping - Tekniska Verken

custom_components/waste_collection_schedule/waste_collection_schedule/source/wiltshire_gov_uk.py
uprn now automatically padded to 12 characters to address issue identified in #649
Icon map also added
=> updated wiltshire_gov_uk

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/lakemac_nsw_gov_au.py, doc/source/lakemac_nsw_gov_au.md, info.md
Add Lake Macquarie City Council
=> Add Lake Macquarie City Council

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/stavanger_no.py, doc/source/stavanger_no.md, info.md
Initial PR for
Stavanger,Norway
=> Add Stavanger,Norway

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/remidt_no.py, doc/source/remidt_no.md, info.md
=> added remidt.no Orkland muni

doc/source/ics.md
Hi Steffen,
I created an example for including the OSB-ICS-Files into Home-Assistant for the docs.
Feel free to merge if you thinks it is helpful.
Best
Stephan
=> Add example for Osnabrück OSB ics-file

doc/source/zaw_online_de.md
=> Corrected ZAW-URL

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/onkaparingacity_com.py, doc/source/onkaparingacity_com.md, info.md
```
$ ./test_sources.py -s onkaparingacity_com -i -l
Testing source onkaparingacity_com ...
found 3 entries for TestcaseI
2023-02-28: General Waste [mdi:trash-can]
2023-02-28: Recycling Waste [mdi:recycle]
2023-03-07: Green Waste [mdi:leaf]
```
=> Add City of Onkaparinga Council

custom_components/waste_collection_schedule/__init__.py, custom_components/waste_collection_schedule/services.yaml
> takes 0 positional arguments but 1 was given
fix #705
=> fix fetch_data service call

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/hume_vic_gov_au.py, doc/source/hume_vic_gov_au.md, info.md
Add Hume City Council waste collection schedule
=> Hume City Council

custom_components/waste_collection_schedule/waste_collection_schedule/source/hume_vic_gov_au.py
Corrected Recycling & Green Waste and added another test
=> Hume.vic.gov.au Corrected Recycling & Green Waste

custom_components/waste_collection_schedule/waste_collection_schedule/source/fccenvironment_co_uk.py
Fixes #714 
EDIT: Looks like my linter restyled a few lines here, lemme know if you want them reverted.
=> Disable TLS checking for fccenvironment.co.uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/cardinia_vic_gov_au.py
Extrapolate bin collection data for 4 weeks
=> Cardinia Shire additional bin collection data

custom_components/waste_collection_schedule/waste_collection_schedule/source/hume_vic_gov_au.py, doc/source/hume_vic_gov_au.md
Allow optional prediction of future collections using the predict boolean
=> hume_vic_gov_au: Optional prediction of future collections

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/movar_no.py, doc/source/movar_no.md, info.md
Per request https://github.com/mampfes/hacs_waste_collection_schedule/issues/718
=> Add support for movar_no

custom_components/waste_collection_schedule/waste_collection_schedule/source/republicservices_com.py
Test case with different waste collection types added, as per #717
```bash
Testing source republicservices_com ...
found 1 entries for Scott Country Clerk
2023-03-02: Solid Waste [mdi:trash-can]
found 1 entries for Branch County Clerk
2023-03-06: Solid Waste [mdi:trash-can]
found 7 entries for Contract Collection
2023-03-07: Recycle [mdi:recycle]
2023-03-21: Recycle [mdi:recycle]
2023-04-04: Recycle [mdi:recycle]
2023-04-18: Recycle [mdi:recycle]
2023-05-02: Recycle [mdi:recycle]
2023-03-07: Solid Waste [mdi:trash-can]
2023-03-07: Yard Waste [mdi:leaf]
```
=> additional Republic Service  test case added

custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_oldenburg_de.py
Fixes issues rasied in #731
Original API_URL response
```bash
Testing source awb_oldenburg_de ...
Error: Street not found..
found 0 entries for Polizeiinspektion Oldenburg
```
Updated API_URL response
```bash
Testing source awb_oldenburg_de ...
found 89 entries for Polizeiinspektion Oldenburg
2023-03-08: Restabfall [None]
2023-03-09: Gelber Sack/Tonne [None]
2023-03-09: Altpapier [None]
2023-03-15: Bioabfall [None]
2023-03-22: Restabfall [None]
2023-03-23: Gelber Sack/Tonne [None]
2023-03-29: Bioabfall [None]
2023-04-05: Restabfall [None]
2023-04-06: Gelber Sack/Tonne [None]
2023-04-06: Altpapier [None]
2023-04-13: Bioabfall [None]
2023-04-19: Restabfall [None]
2023-04-19: Sommerbiotonne [None]
2023-04-20: Gelber Sack/Tonne [None]
2023-04-26: Bioabfall [None]
2023-05-03: Restabfall [None] …
```
=> AWB Oldenburg endpoint update

custom_components/waste_collection_schedule/waste_collection_schedule/source/midsussex_gov_uk.py
Update to midsussex_gov_uk.py: Empty string default values supplied to correct issues flagged by @thor9898
=> MidSussex update

custom_components/waste_collection_schedule/waste_collection_schedule/source/midsussex_gov_uk.py, doc/source/midsussex_gov_uk.md
Implemented an "address" arg to try and reduce config issues. `.md` file updated to reflect changes.
Test_004 implements the new arg
```bash
Testing source midsussex_gov_uk ...
2023-03-08: Rubbish bin collection [mdi:trash-can]
2023-03-15: Recycling bin collection [mdi:recycle]
2023-03-22: Rubbish bin collection [mdi:trash-can]
2023-03-29: Recycling bin collection [mdi:recycle]
2023-03-09: Rubbish bin collection [mdi:trash-can]
2023-03-16: Recycling bin collection [mdi:recycle]
2023-03-23: Rubbish bin collection [mdi:trash-can]
2023-03-30: Recycling bin collection [mdi:recycle]
found 6 entries for Test_003
2023-03-06: Garden bin collection [mdi:leaf]
2023-03-09: Rubbish bin collection [mdi:trash-can]
2023-03-16: Recycling bin …
```
=> Updated MidSussex args

custom_components/waste_collection_schedule/waste_collection_schedule/source/samiljo_se.py
Fix for error on collection day and missing collection days. Also translated a few variables to improve readability.
n_schedule/test$ python3 test_sources.py -s samiljo_se
Testing source samiljo_se ...
found 39 entries for Test1
found 52 entries for Test2
found 52 entries for Test3
=> Samiljo_se update

custom_components/waste_collection_schedule/waste_collection_schedule/service/Samiljo_se_wastetype_searcher.py, doc/source/samiljo_se.md
samiljo_se_wastetype_searcher.py is a servicescript used to map new waste types not yet in NAME_MAP.
=> Added service samiljo_se_wastetype_searcher.py

custom_components/waste_collection_schedule/waste_collection_schedule/source/zva_sek_de.py
fixed #774 by adding event start and end time to the request parameters
=> fixed zva_sek_de where events where one day too early

custom_components/waste_collection_schedule/waste_collection_schedule/source/awido_de.py
fixed #737 
There was a logic error if no street where given it tried to get the id using the not existing street which leads to a wrong id given to the last request.
=> fixed awido_de to work corrcectly wihthout the street parameter

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/administration_esch_lu.py, doc/source/administration_esch_lu.md, requirements.txt
Using it for myself, but maybe it will be useful to someone else from my city. 
It parses the data from a commune website.
=> Adding source for Luxembourg Esch-sur-Alzette

doc/source/bromley_gov_uk.md
Corrected the conflict between config yaml and example yaml as mentioned in [HA Community](https://community.home-assistant.io/t/waste-collection-schedule-framework/186492/265) post
=> Bromley.md typo corrected

custom_components/waste_collection_schedule/waste_collection_schedule/source/westberks_gov_uk.py
support uprn as integer
fix #789
=> fix westberks_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/campbelltown_nsw_gov_au.py
Hi there, just looking to contribute a fix for issue #824. 
Some things had changed with the APIs:
1. The API endpoint URLs
2. The JSON returned by the address search API
3. The HTML generated by the waste collection API
I update the code to suit, and tested with test_sources.py to confirm that it's now working:
Also works in my HA instance:
=> Fixed issue #824 with the Campbelltown NSW (AU) source

custom_components/waste_collection_schedule/waste_collection_schedule/source/hvcgroep_nl.py, doc/source/hvcgroep_nl.md
@wouterhardeman found some mistakes in my [last PR](https://github.com/mampfes/hacs_waste_collection_schedule/pull/834). So here are some fixes :)
=> Fix naming and documentation of new args for HVCgroep

custom_components/waste_collection_schedule/waste_collection_schedule/source/stevenage_gov_uk.py
Corrects #847 
```bash
Testing source stevenage_gov_uk ...
found 3 entries for Coopers Close schedule
2023-04-12 : Recycling [mdi:recycle]
2023-04-18 : Refuse [mdi:trash-can]
2023-04-25 : Recycling [mdi:recycle]
found 3 entries for Wansbeck Close schedule
2023-04-11 : Refuse [mdi:trash-can]
2023-04-17 : Recycling [mdi:recycle]
2023-04-24 : Refuse [mdi:trash-can]
found 3 entries for Chepstow Close schedule
2023-04-12 : Refuse [mdi:trash-can]
2023-04-18 : Recycling [mdi:recycle]
2023-04-25 : Refuse [mdi:trash-can]
```
=> Stevenage fix

custom_components/waste_collection_schedule/waste_collection_schedule/source/c_trace_de.py, doc/source/c_trace_de.md
=> c_trace_de: adding support for Ortsteil parameter

custom_components/waste_collection_schedule/waste_collection_schedule/source/aucklandcouncil_govt_nz.py
=> add support for diffrent food types

custom_components/waste_collection_schedule/waste_collection_schedule/source/abki_de.py
=> fixing abki_de

custom_components/waste_collection_schedule/waste_collection_schedule/source/abki_de.py
=> fixing abki_de recycling

custom_components/waste_collection_schedule/waste_collection_schedule/source/abki_de.py
previous fix #893
second fix for #891
=> fixing abki_de: replace wrong street_input

custom_components/waste_collection_schedule/waste_collection_schedule/source/kingston_gov_uk.py
If one waste type is not available or is an empty String it raised an exception.
fix for #899
=> Kingston_gov_uk fix error if one waste type not available

custom_components/waste_collection_schedule/waste_collection_schedule/source/tewkesbury_gov_uk.py, doc/source/tewkesbury_gov_uk.md
fix for #897
mostly cosemtic: show that uprn is also supported
Added exception if API returns status != ok
=> tewkesbury add support for UPRN instead of postcode

custom_components/waste_collection_schedule/waste_collection_schedule/source/berlin_recycling_de.py
Basing on the work of @5ila5 I have a working version of Berlin Recycling
=> WIP: Fix Berlin Recycling

custom_components/waste_collection_schedule/waste_collection_schedule/source/bsr_de.py
=> add offset = 1 day for bsr.de

custom_components/waste_collection_schedule/waste_collection_schedule/source/grafikai_svara_lt.py
Hi,
As grafikai.svara.lt started to use https, it broke schedule collection. This PR changes url to https
=> change grafikai.svara.lt api url to use https instead of http

custom_components/waste_collection_schedule/waste_collection_schedule/source/binzone_uk.py
=> Quick fix to Issue #937

custom_components/waste_collection_schedule/waste_collection_schedule/source/reading_gov_uk.py
I mistakenly left a `breakpoint()` in after some testing
=> reading_gov_uk remove breakpoint()

custom_components/waste_collection_schedule/waste_collection_schedule/source/jumomind_de.py
=> fix for wrong named variable not matching md example

custom_components/waste_collection_schedule/waste_collection_schedule/source/wirral_gov_uk.py
Typo corrected - skip schedule list if no dates are returned.
=> Wirral, UK - minor update

doc/ics/lebach_de.md, doc/ics/yaml/lebach_de.yaml
=> fix docu for lebach

doc/source/static.md
=> remove obsolete weekday list in static source docu

custom_components/waste_collection_schedule/waste_collection_schedule/source/kuringgai_nsw_gov_au.py
Fix for Ku-Ring-Gai, as reported in #964
```bash
Testing source kuringgai_nsw_gov_au ...
found 3 entries for randomHouse
2023-05-10 : General Waste [mdi:trash-can]
2023-05-10 : Recycling [mdi:recycle]
2023-05-10 : Green Waste [mdi:leaf]
found 3 entries for randomAppartment
2023-05-12 : General Waste [mdi:trash-can]
2023-05-12 : Recycling [mdi:recycle]
2023-05-12 : Green Waste [mdi:leaf]
found 3 entries for randomMultiunit
2023-05-11 : General Waste [mdi:trash-can]
2023-05-18 : Recycling [mdi:recycle]
2023-05-11 : Green Waste [mdi:leaf]
found 3 entries for 1 Latona St
2023-05-16 : General Waste [mdi:trash-can]
2023-05-23 : Recycling [mdi:recycle]
2023-05-16 : Green Waste [mdi:leaf]
found 3 entries for 1A Latona St
2023-05-16 : General Waste [mdi:trash-can]
2023-05-23 : Recycling …
```
=> Ku-ring-gai update

doc/source/static.md
=> fix docu for static source

custom_components/waste_collection_schedule/waste_collection_schedule/source/potsdam_de.py, doc/source/potsdam_de.md
Requested by #625
Highly based on their crappy java script.
```
Testing source potsdam_de ...
found 75 entries for Golm Akazienweg mixed 
found 128 entries for Teltower Vorstadt  Albert-Einstein-Str. 2
found 68 entries for Uetz  Kanalweg 
```
=> Adding potsdam de

custom_components/waste_collection_schedule/waste_collection_schedule/source/south_norfolk_and_broadland_gov_uk.py, doc/source/south_norfolk_and_broadland_gov_uk.md
- allow configuartion with only postcode and address.
- old configuration still works as expected
- update documentation.
- contains #999
=> Norfolk and Broadland add better configuration options

doc/source/south_norfolk_and_broadland_gov_uk.md
add new arguments to the template up front, and clarify the payload method's shortcomings. Clarify what SNBC is.
=> Clarify SNBC documentation

custom_components/waste_collection_schedule/waste_collection_schedule/source/thehills_nsw_gov_au.py
improve matching for suburb, street, and houseNo to be case insensitive and ignoring spaces to prevent issues like #1009
=> thehills_nsw_gov_au make search/matching more robust

doc/source/tmbc_gov_uk.md
Updated the page title which reflected another authority
=> Correct council name tmbc_gov_uk.md

doc/ics/recollect.md, doc/ics/yaml/recollect.yaml
add changes from #1029 to the ics yaml file
=> recollect adding md changes to yaml file

custom_components/waste_collection_schedule/waste_collection_schedule/source/northlincs_gov_uk.py
Addresses issue reported in #1040 
```bash
Testing source northlincs_gov_uk ...
found 30 entries for Test_001
2023-06-15 : Plastic and cardboard wheeled bin [mdi:recycle]
2023-06-15 : Brown garden waste wheeled bin [mdi:leaf]
2023-06-22 : General waste wheeled bin [mdi:trash-can]
2023-06-22 : Blue kerbside box - paper [mdi:package-variant]
2023-06-22 : Green kerbside box - cans, glass and aluminium foil [mdi:glass-fragile]
2023-06-22 : Textiles Bag [mdi:sack]
2023-06-29 : Plastic and cardboard wheeled bin [mdi:recycle]
2023-06-29 : Brown garden waste wheeled bin [mdi:leaf]
2023-07-06 : General waste wheeled bin [mdi:trash-can]
2023-07-06 : Blue kerbside box - paper [mdi:package-variant]
2023-07-06 : Green kerbside box - cans, glass and aluminium foil [mdi:glass-fragile]
2023-07-06 : …
```
=> North Lincs update

doc/source/static.md
Otherwise you will get only the next 10 events, which is most probably not what you want.
=> make clear that either until or count is required for static source

custom_components/waste_collection_schedule/waste_collection_schedule/source/north_kesteven_org_uk.py
requested by https://github.com/mampfes/hacs_waste_collection_schedule/issues/986#issuecomment-1604298646 in #986
=> update north_kesteven_org_uk to display more pickup dates

README.md, doc/ics/trv_no.md, doc/ics/yaml/trv_no.yaml, doc/source/ics.md, info.md
documentation for ICS source: discussed in #1048
=> add ICS source for Trondheim, Norway

custom_components/waste_collection_schedule/waste_collection_schedule/source/cmcitymedia_de.py, custom_components/waste_collection_schedule/waste_collection_schedule/wizard/cmcitymedia_de.py
Fix SSL error from cmcitymedia_de.
Their server has a strange SSL configuration, so I have now "fixed" the error to dont use SSL. https://github.com/mampfes/hacs_waste_collection_schedule/pull/672
=> Fix CmCityMedia, to now use API without ssl

custom_components/waste_collection_schedule/waste_collection_schedule/source/recyclecoach_com.py
=> fixing bug with recyclecoach_com: district_id & Reformatting

custom_components/waste_collection_schedule/waste_collection_schedule/source/cherwell_gov_uk.py
Addresses date format error mentioned in #1116
=> Update: cherwell_gov_uk

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/hcc_govt_nz.py, doc/source/hcc_govt_nz.md, info.md
=> Add Hamilton City Council source

custom_components/waste_collection_schedule/waste_collection_schedule/source/hausmuell_info.py
=> fixed hausmuell_info not working properly for some addresses containing special characters

custom_components/waste_collection_schedule/waste_collection_schedule/source/maroondah_vic_gov_au.py
Not an expert but according to my testing the URL for the Maroondah spatial platform has changed - see hyperlink [here](https://www.maroondah.vic.gov.au/Explore/About-our-City/Maps-of-Maroondah/Online-mapping).
=> Update Maroondah URL

custom_components/waste_collection_schedule/waste_collection_schedule/source/stockton_gov_uk.py
fix regext (filtered out st from august)
fix for #1171
=> stockton fix regex for august + Reformatting

custom_components/waste_collection_schedule/waste_collection_schedule/source/warszawa19115_pl.py
API was updated and now uses GET instead of POST.
=> Update warszawa19115_pl to use GET

custom_components/waste_collection_schedule/waste_collection_schedule/source/bristol_gov_uk.py
add lastCollectionDate (includes same day) like discussed in #1173
switched to response.json() instead of relying on regex to extract json data
=> minor improvement of bristol_gov_uk

README.md, doc/source/ics.md, update_docu_links.py
fix for #1178
bug caused by #1163
=> fix update_docu_links extra_info for ics yamls

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/sandnes_no.py, doc/source/sandnes.md, info.md
requested by #1190
tests:
```
Testing source sandnes_no ...
found 22 entries for TestcaseI
2023-09-05 : Papir [mdi:recycle]
2023-09-05 : Restavfall [mdi:trash-can]
2023-09-12 : Våtorganisk avfall [mdi:leaf]
2023-09-19 : Restavfall [mdi:trash-can]
2023-09-26 : Våtorganisk avfall [mdi:leaf]
2023-10-03 : Papir [mdi:recycle]
2023-10-03 : Restavfall [mdi:trash-can]
2023-10-10 : Våtorganisk avfall [mdi:leaf]
2023-10-17 : Restavfall [mdi:trash-can]
2023-10-24 : Våtorganisk avfall [mdi:leaf]
2023-10-31 : Papir [mdi:recycle]
2023-10-31 : Restavfall [mdi:trash-can]
2023-11-07 : Våtorganisk avfall [mdi:leaf]
2023-11-14 : Restavfall [mdi:trash-can]
2023-11-21 : Våtorganisk avfall [mdi:leaf]
2023-11-28 : Papir [mdi:recycle]
2023-11-28 : Restavfall [mdi:trash-can]
2023-12-05 : Våtorganisk avfall …
```
=> adding sandnes_no

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/iris_salten_no.py, doc/source/iris_salten_no.md, info.md
requetsed by #1192
tests:
```bash
Testing source iris_salten_no ...
found 6 entries for Alsosgården 11, bodø
2023-08-30 : Matavfall [mdi:food-apple]
2023-08-30 : Papir og Papp [mdi:package-variant]
2023-09-13 : Matavfall [mdi:food-apple]
2023-09-13 : Restavfall [mdi:trash-can]
2023-09-22 : Plast [mdi:recycle]
2023-09-22 : Glass- og metallemballasje [mdi:bottle-soda]
found 5 entries for Kalnesveien 3, Fauske kommune
2023-09-04 : Matavfall [mdi:food-apple]
2023-09-04 : Papir og Papp [mdi:package-variant]
2023-09-18 : Matavfall [mdi:food-apple]
2023-09-18 : Restavfall [mdi:trash-can]
2023-09-21 : Plast [mdi:recycle]
```
=> adding iris_salten_no

doc/source/durham_gov_uk.md
Correcting a couple of typos that affected link/url formatting
=> Durham.md typos

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/sandnes_no.py, doc/source/sandnes.md, info.md
fixed issues in mds mentioned in #1202
=> replace wrongly paced Stavanger with Sandnes

custom_components/waste_collection_schedule/waste_collection_schedule/source/croydon_gov_uk.py
get more tokens for requests to pass multiple tests in a row might fix issue mentioned in #975
```bash
Testing source croydon_gov_uk ...
2023-09-06 : Food waste [mdi:food]
2023-09-06 : General rubbish [mdi:trash-can]
2023-09-06 : Paper and card recycling [mdi:newspaper]
2023-09-13 : Glass, plastics, cans and cartons recycling [mdi:bottle-wine]
2023-09-14 : Glass, plastics, cans and cartons recycling [mdi:bottle-wine]
2023-09-07 : General rubbish [mdi:trash-can]
2023-09-07 : Paper and card recycling [mdi:newspaper]
2023-09-07 : Food waste [mdi:food]
found 4 entries for Test_003
2023-09-07 : General rubbish [mdi:trash-can]
2023-09-14 : Glass, plastics, cans and cartons recycling [mdi:bottle-wine]
2023-09-07 : Paper and card recycling …
```
=> fix croydon_gov_uk to pass even on fast requests

custom_components/waste_collection_schedule/waste_collection_schedule/source/lincoln_gov_uk.py
adds extra refuse event at recylcing date if its not allready the same like requested in https://github.com/mampfes/hacs_waste_collection_schedule/issues/1246#issuecomment-1711739220
=> lincoln add Refuse at recycling date

doc/source/aylesburyvaledc_gov_uk.md
=> typo corrected

custom_components/waste_collection_schedule/waste_collection_schedule/source/bielefeld_de.py
=> fix Bielefeld_de

custom_components/waste_collection_schedule/waste_collection_schedule/source/maroondah_vic_gov_au.py
The local council have updated their website so it is now using OpenCities like many other local councils in this jurisdiction. I've updated the source to reflect that and this is working well with the test_source.py script and in my instance of Home Assistant.
=> Updated Maroondah VIC AU to use OpenCities API

custom_components/waste_collection_schedule/waste_collection_schedule/source/innerwest_nsw_gov_au.py
=> fix innerwest wrong events

custom_components/waste_collection_schedule/waste_collection_schedule/source/c_trace_de.py, doc/source/c_trace_de.md
=> fix c_trace_de: add gemeinde param needed for some municipalities

custom_components/waste_collection_schedule/waste_collection_schedule/source/awigo_de.py
=> fix awigo using badbergen instead of bergen

README.md, update_docu_links.py
prevents weired resorting that my differ from client to client
=> add additional sort paramater to update_docu_links.py to prevent different behaviour from client to client

custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py
=> fix issue with app_abfallplus_de for some apps/addresses

custom_components/waste_collection_schedule/waste_collection_schedule/source/northlincs_gov_uk.py
Fixes issue raised in #1354 
```bash
Testing source northlincs_gov_uk ...
found 32 entries for Test_001
2023-10-26 : General waste wheeled bin [mdi:trash-can]
2023-10-26 : Blue kerbside box - paper [mdi:package-variant]
2023-10-26 : Green kerbside box - cans, glass and aluminium foil [mdi:glass-fragile]
2023-10-26 : Textiles Bag [mdi:sack]
2023-11-02 : Plastic and cardboard wheeled bin [mdi:recycle]
2023-11-02 : Brown garden waste wheeled bin [mdi:leaf]
2023-11-09 : General waste wheeled bin [mdi:trash-can]
2023-11-09 : Blue kerbside box - paper [mdi:package-variant]
2023-11-09 : Green kerbside box - cans, glass and aluminium foil [mdi:glass-fragile]
2023-11-09 : Textiles Bag [mdi:sack]
2023-11-16 : Plastic and cardboard wheeled bin [mdi:recycle]
2023-11-16 : Brown garden waste wheeled …
```
=> Fix: northlincs_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/mamirolle_info.py
Add an ignored argument to keep the arguments as required in HA source configuration
Fixes #1351
=> Fix mamirolle info args

custom_components/waste_collection_schedule/waste_collection_schedule/source/stoke_gov_uk.py
fix for #1364
(not reproducable with our test cases)
=> fix stoke_gov_uk as some addresses my provide different date format

custom_components/waste_collection_schedule/waste_collection_schedule/source/landkreis_kusel_de.py
=> fix landkreis_kusel_de

custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py
=> app_abfallplus_de allow integer house numbers

doc/ics/hameln_pyrmont_de.md, doc/ics/yaml/hameln_pyrmont_de.yaml
=> hameln ICS Documentation disable ssl check

doc/source/whittlesea_vic_gov_au.md
=> fix whittlesea AU docu

custom_components/waste_collection_schedule/waste_collection_schedule/source/staedteservice_de.py, doc/source/staedteservice_de.md
=> fix staedteservice_de

custom_components/waste_collection_schedule/waste_collection_schedule/source/zva_sek_de.py
zva_sek_de shows next years collections in November and december
=> minor improvement for zva_sek_de

custom_components/waste_collection_schedule/waste_collection_schedule/source/zva_sek_de.py
Data from Init is destroyed. Subsequent calls failed.
=> Solution to Issue 1401

custom_components/waste_collection_schedule/waste_collection_schedule/service/AbfallnaviDe.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/abfallnavi_de.py
fixes #1409
Some address may not return all events if a new calendar (year change) is published and the internal street_id changes only new events will be returned
This should fix this. May also happen with city_id changing but i suspect this will probably not happen (not confirmed)
=> improve abfallnavi_de

custom_components/waste_collection_schedule/waste_collection_schedule/source/karlsruhe_de.py, doc/source/karlsruhe_de.md
karlsruhe_de add ladeort argument requested by #1412
minor reformatting
=> karlsruhe_de add ladeort argument

custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py, custom_components/waste_collection_schedule/waste_collection_schedule/wizard/app_abfallplus_de.py
=> fix app_abfallpluse_de for apps requireing bundesland

custom_components/waste_collection_schedule/waste_collection_schedule/source/kwu_de.py, doc/source/kwu_de.md
kwu_de now supports integer house numbers 
fix for #1416
=> improve kwu_de

custom_components/waste_collection_schedule/waste_collection_schedule/source/nsomerset_gov_uk.py
nsomester_gov_uk shows next two instead of only the next event
based on discussion in #1376
=> nsomester_gov_uk shows next two instead of only the next event

custom_components/waste_collection_schedule/waste_collection_schedule/source/northherts_gov_uk.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/waverley_gov_uk.py
=> fix waverley_gov_uk and northherts_gov_uk house number check

custom_components/waste_collection_schedule/waste_collection_schedule/source/portenf_sa_gov_au.py
fix for #1110
may Require reevaluation in December.
=> fix portenf_sa_gov_au incorrect dates + reformatting

custom_components/waste_collection_schedule/waste_collection_schedule/source/bromley_gov_uk.py
fix for #1269
new implementation will retry getting the file multiple times (up to 15) every two seconsd as this is basically the approach the website does (hx-trigger="every 2s")
=> fix bromley_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/portsmouth_gov_uk.py
=> fix portsmouth_gov_uk + REFORMATTING

custom_components/waste_collection_schedule/waste_collection_schedule/wizard/app_abfallplus_de.py, doc/source/tbv_velbert_de.md
improve apps_abfalplus_de wizzard to sort select elemnts
fix wrong tbv_velbert_de example configuration
=> fix tbv_velbert_de example config improve abfalplus wizzard

custom_components/waste_collection_schedule/waste_collection_schedule/source/regioentsorgung_de.py
fix for @altacoon problem mentioned in #1409
=> regioentsorgugn_de get entries for all years + reformatting

custom_components/waste_collection_schedule/waste_collection_schedule/source/midsussex_gov_uk.py
=> fix midsussex_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/sbazv_de.py
=> sbazv remove uneccesary code createing duplicates in decmber

custom_components/waste_collection_schedule/waste_collection_schedule/source/mojiodpadki_si.py
This pull request fixes parsing of mojiodpadki.si source year for the schedules.
=> Fix mojiodpadki.si turn-of-the-year handling

custom_components/waste_collection_schedule/waste_collection_schedule/source/hausmuell_info.py
=> fix hausmuell_info for erfurt

custom_components/waste_collection_schedule/waste_collection_schedule/source/rushmoor_gov_uk.py
fix for #1485
they redesigned their collection site and removed the ICS option. This approach parses the JSON data returned by their "API"
=> fix rushmoor_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/minrenovasjon_no.py
fix for #1482
based on https://github.com/Danielhiversen/home_assistant_min_renovasjon/commit/5aea465824aec47e8261c9792c7682009b46b6dd
=> fix minrenovasjon_no + Refomatting

custom_components/waste_collection_schedule/waste_collection_schedule/source/sbazv_de.py
=> sbazv_de remove duplicates

custom_components/waste_collection_schedule/waste_collection_schedule/source/dudley_gov_uk.py
=> dudley_gov_uk add xmas holiday check

custom_components/waste_collection_schedule/waste_collection_schedule/source/sysav_se.py
fix for #1536 
thy changed API location to `https://ca-weu-sysav-edp-api-prod.icypond-fdc05156.westeurope.azurecontainerapps.io/api` as I do not know if this is a static url I get this url from the webpage from the data-api key of an div element
=> fix sysav_se

custom_components/waste_collection_schedule/waste_collection_schedule/source/umweltverbaende_at.py, doc/source/umweltverbaende_at.md
will improve situations like #1547 for some municipalities
compatibility with old kremsstadt configurations is preserved
=> umwelverbaende_at now supports calendar option + ties fetch next year in Dec

custom_components/waste_collection_schedule/waste_collection_schedule/source/cornwall_gov_uk.py
adds garden collections to cornwall, UK
fixes #1556
=> Cornwall, UK add garden collection + refactoring

custom_components/waste_collection_schedule/waste_collection_schedule/source/abfall_lippe_de.py
improves "bug" mentioned in #1568
=> abfall_lippe_de now fetches next year in december

doc/source/landkreis_kusel_de.md
fix indentation and remove unnecessary whitespaces in code blocks.
closes mampfes/hacs_waste_collection_schedule#1520
=> docs: fix indentation `doc/source/landkreis_kusel_de.md`

custom_components/waste_collection_schedule/waste_collection_schedule/source/abfallwirtschaft_vechta_de.py
Next collection dates were in next year so HA said "Unknown"
=> fix last few days in december having no dates

custom_components/waste_collection_schedule/waste_collection_schedule/source/portenf_sa_gov_au.py
=> fix protenf_ssa_gov_au

custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_mainz_bingen_de.py
awb_main_bingen_de now get all ical links this means it will get the file from this and the following year if provided.
Also did some reformatting
This closes  #1578
=> awb_main_bingen_de now get all ical links (next year)

custom_components/waste_collection_schedule/waste_collection_schedule/source/stavanger_no.py
=> fix stavanger_no wrong year bug

doc/ics/edg_de.md, doc/ics/yaml/edg_de.yaml
=> update edg_de ics documentation

custom_components/waste_collection_schedule/waste_collection_schedule/source/tmbc_gov_uk.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/westberks_gov_uk.py
- Tonbridge & Malling (tmbc_go_uk) now shows propper year for next year events. Fixes #1590
- Westberks (westberks_gov_uk) now shows propper year for next year events. Fixes #1592
=> Fix Tonbridge & Malling and westberks wrong year bug

custom_components/waste_collection_schedule/waste_collection_schedule/source/was_wolfsburg_de.py
fixes #1593
looks like they removed the ICS option this now uses the same approach for all collection types
=> fix was_wolfsburg_de

custom_components/waste_collection_schedule/waste_collection_schedule/source/abfallwirtschaft_pforzheim_de.py, doc/source/abfallwirtschaft_pforzheim_de.md
=> abfallwirtschaft_pforzheim_de get next year data

custom_components/waste_collection_schedule/waste_collection_schedule/source/brisbane_qld_gov_au.py
Address code desitions mentioned in  #1610
=> update brisbane to raise exceptions + refactoring

custom_components/waste_collection_schedule/waste_collection_schedule/source/basildon_gov_uk.py, doc/source/basildon_gov_uk.md
Basildon Council have changed their API to mybasildon.powerappsportals.com, Bristol Council also uses a "powerappsportals.com" API so was used as the basis of this code, unfortunately the API responses are different so had to be amended.
Updated:
basildon_gov_uk.py
basildon_gov_uk.md
**BREAKING CHANGES**
API now requires a UPRN (previously postcode/address)
=> Basildon source updated to new provider

custom_components/waste_collection_schedule/waste_collection_schedule/source/ccc_govt_nz.py
=> Support override dates for Christchurch NZ

custom_components/waste_collection_schedule/waste_collection_schedule/source/doncaster_gov_uk.py
=> doncaster_gov_uk fetches 1 year isntead of 3 weeks

custom_components/waste_collection_schedule/waste_collection_schedule/source/movar_no.py
From January 2024 there are new Kommunenummers which breaks the script. This pull request changes to the new Kommunenummers.
=> Fix movar_no (Updated Kommunenummers for 2024 onward)

custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_bad_kreuznach_de.py, doc/source/awb_bad_kreuznach_de.md
fixes #1643
Looks like they do not provide the dates individual anymore but just a start day and an interval + holidays where collections should move. I Hope everything works fine.
With my test everything looked fine. 
removed old app fetch as the old app wasn't online anymore
=> fix awb_bad_kreuznach_de + removed old fetch method

custom_components/waste_collection_schedule/waste_collection_schedule/source/karlsruhe_de.py
I have tested the changes on my local HA installation. Please review the code (as I'm not an experienced python developer). Thanks!
=> Fix [Bug]: source 'City of Karlsruhe' stopped working #1655

custom_components/waste_collection_schedule/waste_collection_schedule/source/fccenvironment_co_uk.py
=> Fix fccenvironment co uk harborough

custom_components/waste_collection_schedule/waste_collection_schedule/source/braintree_gov_uk.py
=> Fix braintree gov uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/karlsruhe_de.py
=> fix Karlsruhe_de (again)

custom_components/waste_collection_schedule/waste_collection_schedule/source/rh_entsorgung_de.py
fixes issue mentioned here: #1455
Instead of offering a own source this now simply inherits from the jumomind_de source
=> fix rh_entsorung_de now inherits from jumomind_de

custom_components/waste_collection_schedule/waste_collection_schedule/source/geoport_nwm_de.py
=> geoport_nwm_de now shows all collections for names including '- '

custom_components/waste_collection_schedule/waste_collection_schedule/source/portenf_sa_gov_au.py
=> portenf_sa_gov_au fix calendar logic

custom_components/waste_collection_schedule/waste_collection_schedule/source/adur_worthing_gov_uk.py
=> adur_worthing_gov_uk address lookup cases insensitive

custom_components/waste_collection_schedule/waste_collection_schedule/source/mamirolle_info.py
Fix date parsing for cases like first day of month '1er'
=> Fix Mamirolle info first day of monthIgnore letters in special dates like '1er'

custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py
=> fix app_abfallplus for some regions

custom_components/waste_collection_schedule/waste_collection_schedule/source/oxford_gov_uk.py
Source website was changed. 
Solution: Change pageids
Fixes: #1761 
No doc change
test case successful
=> Source Oxford_gov_uk: Fix - Support new website layout

custom_components/waste_collection_schedule/waste_collection_schedule/source/northnorthants_gov_uk.py
integration returned wrong dates caused by timezone converteion (at least from a german system)
noticed while debugging https://github.com/mampfes/hacs_waste_collection_schedule/issues/1108#issuecomment-1934753287
=> northnorthants_gov_uk fix timezone issues

custom_components/waste_collection_schedule/waste_collection_schedule/source/wastenet_org_nz.py, doc/source/wastenet_org_nz.md
=> fix wastenet_org_nz

custom_components/waste_collection_schedule/waste_collection_schedule/source/heilbronn_de.py, doc/source/heilbronn_de.md
fixes  #1728
based on code provided by @hubelbubel (https://github.com/mampfes/hacs_waste_collection_schedule/issues/1728#issuecomment-1925637621)
=> fix heilbronn_de

custom_components/waste_collection_schedule/waste_collection_schedule/source/telford_gov_uk.py
=> fix telford_gov_uk: date falls on 29. Feb in leap-year

custom_components/waste_collection_schedule/waste_collection_schedule/source/miljoteknik_se.py
=> fix miljoteknik_se + reformatting

custom_components/waste_collection_schedule/waste_collection_schedule/source/heilbronn_de.py
fixes bug where collections are returned multiple times instead of once
=> heilbronn_de fix duplicate bug

custom_components/waste_collection_schedule/waste_collection_schedule/source/abfall_io.py
=> abfall io fix leap year bug

custom_components/waste_collection_schedule/waste_collection_schedule/wizard/app_abfallplus_de.py
=> app_abfallplus_de: fix wizzard bezirk needed condition

custom_components/waste_collection_schedule/manifest.json
=> increase version in manifest.json to next release number instead of last release

README.md, custom_components/waste_collection_schedule/waste_collection_schedule/source/multiple.py, doc/installation.md, doc/source/multiple.md, update_docu_links.py
This addresses issues like #1801
@mampfes what do you think about this approach?
=> add source multiple to combine multiple sources to one Entity

custom_components/waste_collection_schedule/waste_collection_schedule/source/srvatervinning_se.py, doc/source/srvatervinning_se.md
- Adds city as a configurable argument.
- Updated the documentation with more up to date configuration information and added examples.
=> Improves SRV återvinning AB implementation

doc/source/multiple.md
=> fix documentaiont of source 'multiple'

custom_components/waste_collection_schedule/waste_collection_schedule/source/chichester_gov_uk.py
Fixes #1813
Chichester District Council updated the web app they are using which broke the scrape.
=> Fix Chichester District Council source

custom_components/waste_collection_schedule/waste_collection_schedule/source/wastenet_org_nz.py
fixes #1872
date was parsed as y/m/d but is provided as d/m/y
=> fix watenet_org_nz

custom_components/waste_collection_schedule/waste_collection_schedule/source/barnsley_gov_uk.py
=> fix barnsley_gov_uk failing if date is 'Today' insetead of date format

custom_components/waste_collection_schedule/waste_collection_schedule/source/basingstoke_gov_uk.py
=> basingstoke warning instead of error on failed date parse

custom_components/waste_collection_schedule/waste_collection_schedule/source/republicservices_com.py, doc/source/republicservices_com.md
=> republicservices_com now shows Bulk Waste instead of Solid Waste for Bulk Waste collection when using method=2

custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py
app_abfallplus_de now shows all collection rythms if you can select multiple different rythms with the rythms in the name to disable unwanted rythms using the customize section.
fixes #1909
=> AppApfallplusDE show all waste types if you can select multiple collection rythms

custom_components/waste_collection_schedule/waste_collection_schedule/source/aha_region_de.py
Sometimes ICAL files seem to be compleatly empty. This "fix" skipps these ical files of this waste type instead of failing all together. A warning is printed into the logs.
addresses #1912
=> aha_region_de now skipps waste type if ical file is invalid instead of raising an exception

custom_components/waste_collection_schedule/waste_collection_schedule/source/braintree_gov_uk.py
This is a little simple fix for using the url variable
This PR will need merging first:
https://github.com/mampfes/hacs_waste_collection_schedule/pull/1920
=> Braintree - Use URL variable

custom_components/waste_collection_schedule/waste_collection_schedule/source/bradford_gov_uk.py
=> bradford_gov_uk now supports integer uprns

custom_components/waste_collection_schedule/waste_collection_schedule/source/merri_bek_vic_gov_au.py
implements fix descriped in #1930
=> fix merri_bek_vic_gov_au

custom_components/waste_collection_schedule/waste_collection_schedule/source/static.py
=> fix static wrong weekday assignment

custom_components/waste_collection_schedule/waste_collection_schedule/source/jumomind_de.py
fixes https://github.com/mampfes/hacs_waste_collection_schedule/issues/1500#issuecomment-2040364315
=> jumomind_de fix event shows multiple times + get dates from same API as address

custom_components/waste_collection_schedule/waste_collection_schedule/source/umweltverbaende_at.py, doc/source/umweltverbaende_at.md
=> umweltverbaende_at now supports more complex calendar arguments

custom_components/waste_collection_schedule/waste_collection_schedule/source/ecoharmonogram_pl.py
=> fixed ecoharmonogram_pl matching wrong town using 'in' + Reformatting

custom_components/waste_collection_schedule/waste_collection_schedule/source/haringey_gov_uk.py
=> fix harringey_gov_uk not working for addresses that list communal collections

doc/ics/stadtreinigung_leipzig_de.md, doc/ics/yaml/stadtreinigung_leipzig_de.yaml
=> ICS: stadreiiknigung_leipzig_de update description

custom_components/waste_collection_schedule/waste_collection_schedule/source/gateshead_gov_uk.py
=> fix gateshead_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/sepan_remondis_pl.py
=> fix sepan_remodis_pl returning wrong dates

custom_components/waste_collection_schedule/waste_collection_schedule/source/ashford_gov_uk.py
=> fix ashford_gov_uk

custom_components/waste_collection_schedule/__init__.py
addresses first warning of #2023
Not tested yet
=> remove deprecated function call 'async_load_platform'

custom_components/waste_collection_schedule/waste_collection_schedule/source/basildon_gov_uk.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/bristol_gov_uk.py
=> Fix typo in icon specification: "varient" should be "variant".

custom_components/waste_collection_schedule/waste_collection_schedule/source/mansfield_vic_gov_au.py
The council website is displaying information about a potential future green-waste service, which wasn't parsing correctly.
=> Fix mansfield_vic_gov_au

custom_components/waste_collection_schedule/waste_collection_schedule/source/maldon_gov_uk.py
=> maldon_gov_uk additionaly returns 'Last Collection' dates + reformatting

custom_components/waste_collection_schedule/__init__.py
Partially fixes https://github.com/mampfes/hacs_waste_collection_schedule/issues/2023
=> Import from thread instead event loop

.vscode/launch.json
This allows you to be editing a source script in VS Code, then just press F5 to run it through the test script with the debugger attached.
=> Introduce VS Code debug config

custom_components/waste_collection_schedule/waste_collection_schedule/source/ashford_gov_uk.py
fixes https://github.com/mampfes/hacs_waste_collection_schedule/issues/1914#issuecomment-2126335629
=> ashford_gov_uk now shows collections that are due 'Today'

custom_components/waste_collection_schedule/waste_collection_schedule/source/bsr_de.py
=> bsr_de remove offset from  ICS class as it would return wrong dates

custom_components/waste_collection_schedule/waste_collection_schedule/source/maidstone_gov_uk.py
fixes #2106
Maidstone changed it api
=> fix maidstone_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py
=> fix app_abfallplus_de for apps that show a lot of collection types below a Sondermüll Headline

custom_components/waste_collection_schedule/waste_collection_schedule/source/southkesteven_gov_uk.py
=> add_southkesteven_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/portenf_sa_gov_au.py
=> portenf_sa_gov_au disable ssl verification for post requests (already disabled for get)

custom_components/waste_collection_schedule/waste_collection_schedule/source/denbighshire_gov_uk.py
=> denbigshire_gov_uk move to new API

custom_components/waste_collection_schedule/waste_collection_schedule/source/lewisham_gov_uk.py
=> fix_lewisham_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/highland_gov_uk.py, doc/source/highland_gov_uk.md
fixes #2053
Breaks existing configuration as the new implementeation needs a UPRN While the old needed a different internal ID
=> fix highland_gov_uk (breaks exsiting configurations)

custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_oldenburg_de.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/ks_boerde_de.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/newcastle_gov_uk.py
made these regex strings raw strings as mypy did complain
=> make regex strings raw strings

custom_components/waste_collection_schedule/waste_collection_schedule/source/awido_de.py
=> make awido street/city/hnr search case insensitve

doc/source/stevenage_gov_uk.md
=> Link to search engine for UPRN

custom_components/waste_collection_schedule/waste_collection_schedule/source/portenf_sa_gov_au.py
fixes #2218
Failed when month div above calendar would show only one month (July 2024) instead of a month range like: July - May 2024
=> fix portenf_sa_gov_au

custom_components/waste_collection_schedule/waste_collection_schedule/source/ashfield_gov_uk.py, doc/source/ashfield_gov_uk.md
=> fix ashfield_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/wyreforestdc_gov_uk.py, doc/source/wyreforestdc_gov_uk.md
=> rewrite of wyreforestdc_gov_uk

custom_components/waste_collection_schedule/translations/en.json, custom_components/waste_collection_schedule/waste_collection_schedule/source/hawkesbury_nsw_gov_au.py, doc/source/hawkesbury_nsw_gov_au.md
This change fixes the integration to the Hawkesbury NSW Gov API. 
Changes include: 
- Fix to handle inconsistency between dates and datetimes in bin _week<number> field
- Added Postcode and State to the get request parameters and as a argument for the integration
- Added fix to handle missing organic schedule frequency field when organics are not collected at address
=> Update to Hawkesbury NSW GOV AU Integration 

custom_components/waste_collection_schedule/waste_collection_schedule/service/EcoHarmonogramPL.py, doc/source/ecoharmonogram_pl.md
fix missing `,` in wizzard which lead to a small issue in the md file.
fixes this issue introduced in #2236
=> minor md fix for ecoharmonogram_pl

custom_components/waste_collection_schedule/config_flow.py
fixes https://github.com/mampfes/hacs_waste_collection_schedule/issues/2233#issuecomment-2220355181
=> fix config flow not showing arg if it has a not None default value

custom_components/waste_collection_schedule/calendar.py, custom_components/waste_collection_schedule/const.py, custom_components/waste_collection_schedule/init_yaml.py
This fixes #2245 
Additional:
Looks like that some init.py changes got lost with the move to init-yaml.py
=> Fix calendar entries not created for yaml config entries

custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py
This PR is addressing the latest backend changes and fixes #2197 
1. Move from IOS to Android request structure
2. Pausing 1sec between requests
3. Adjusting request header structure
=> Fix: Source: App_AbfallPlus_de - Request header structure changes

custom_components/waste_collection_schedule/waste_collection_schedule/source/kuringgai_nsw_gov_au.py, doc/source/kuringgai_nsw_gov_au.md
+ fixed documentation for old version that only allowed string variables
fixes https://github.com/mampfes/hacs_waste_collection_schedule/issues/2050#issuecomment-2226945283
=> kuringgai_nsw_gov_au accept integer post_code and street_number

custom_components/waste_collection_schedule/waste_collection_schedule/source/broxtowe_gov_uk.py
fixes 2nd = 3rd test case.
Should not affect a lot of addresses
=> broxtowe skip date if not parsable instead of fail compleatly + reformatting

custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py
=> treating ics params in GUI as DICT not STRING

custom_components/waste_collection_schedule/waste_collection_schedule/source/api_golemio_cz.py
=> api_golemio_cz fix wrong typehint lead to integer instead of float GUI input field

custom_components/waste_collection_schedule/waste_collection_schedule/source/kwu_de.py
=> kwu_de imporve error messages + reformatting

custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py
=> fix AppAbfallplus failing if a street contains a tab

custom_components/waste_collection_schedule/waste_collection_schedule/source/circulus_nl.py
=> fix circulus_nl

custom_components/waste_collection_schedule/sources.json, doc/ics/yaml/abfall_hdh_de.yaml, doc/ics/yaml/abfallkalender_erftstadt_de.yaml, doc/ics/yaml/abfallwirtschaft_sonneberg_de.yaml, doc/ics/yaml/abfallwirtschaft_uhk_de.yaml, doc/ics/yaml/art_trier_de.yaml, doc/ics/yaml/azv_hof_de.yaml, doc/ics/yaml/bee_emden_de.yaml, doc/ics/yaml/contarina_it.yaml, doc/ics/yaml/detmold_de.yaml, doc/ics/yaml/edg_de.yaml, doc/ics/yaml/entsorgung_cham_de.yaml, doc/ics/yaml/entsorgung_regional_de.yaml, doc/ics/yaml/entsorgung_sad_de.yaml, doc/ics/yaml/eva_abfallentsorgung_de.yaml, doc/ics/yaml/fes_frankfurt_de.yaml, doc/ics/yaml/hameln_pyrmont_de.yaml, doc/ics/yaml/hws_halle_de.yaml, doc/ics/yaml/ilm_kreis_de.yaml, doc/ics/yaml/muensingen_ch.yaml, doc/ics/yaml/neu_ulm_de.yaml, doc/ics/yaml/openerz_metaodi_ch.yaml, doc/ics/yaml/osnabrueck_de.yaml, doc/ics/yaml/recollect.yaml, doc/ics/yaml/st-poelten_at.yaml, doc/ics/yaml/stadtreinigung_leipzig_de.yaml, doc/ics/yaml/swk_herford_de.yaml, doc/ics/yaml/zah_hildesheim_de.yaml, update_docu_links.py
As people seem to not differenciate between normal sources and ICS sources I think it is best to move the ICS sources to the country specific source selecter this also allows to have some default params for some ics sources (where it makes sense)
=> config_flow move ICS sources to country selection with selected default params

custom_components/waste_collection_schedule/waste_collection_schedule/source/kwu_de.py
this fixes a problem where street Im Feldweg is selected when searching for the street Feldweg
fixes #2266
=> kwu_de match street with == intead of in

custom_components/waste_collection_schedule/waste_collection_schedule/source/manchester_uk.py
fixes: #2003 
- New service endpoint.
Test cases:
```
Testing source manchester_uk ...
found 130 entries for domestic #1
found 130 entries for domestic #2
found 130 entries for domestic #3
found 208 entries for domestic #4
found 130 entries for domestic #5
```
=> Fix Manchester_UK - New service endpoint

custom_components/waste_collection_schedule/waste_collection_schedule/source/alw_wf_de.py
=> alw_wf_de improve city/street matching

doc/source/manchester_uk.md
addresses https://github.com/mampfes/hacs_waste_collection_schedule/issues/2003#issuecomment-2236168566
=> manchester_uk.md update section on how to find UPRN

doc/source/apps_imactivate_com.md
removes unnecesary md section addedin #2315
=> apps_imactivate_com md fix

custom_components/waste_collection_schedule/config_flow.py
=> Config Flow Union Type prefere string over other types

custom_components/waste_collection_schedule/waste_collection_schedule/source/muellmax_de.py
=> muellmax_de improve error message

custom_components/waste_collection_schedule/waste_collection_schedule/source/ahk_heidekreis_de.py
This fixes the error i wrote about in pull request #2335 
The problem in ahk_heidekreis_de caused the update_docu_links.py to fail
=> Double quotes caused error with f-string

custom_components/waste_collection_schedule/waste_collection_schedule/source/lbbd_gov_uk.py
Fixes a problem where if you paid for garden waste to be collected the source would fail. Now works for either situation.
=> Fix lbbd.gov.uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/whittlesea_vic_gov_au.py, doc/source/whittlesea_vic_gov_au.md
(This is my first ever pull request so bear with me)
The City of Whittlesea Council have launched a redesign of their website and, with it, changed to the OpenCities API.
I used the near-by Nillumbik Shire Council as a foundation for the changes in this pull request as they use the same website design and API. Changes have been made to both the python file and documentation. The configuration has changed so this will be **a breaking change**. I've tested the changes on my personal Home Assistant install without any issues.
Hopefully I've done all of this somewhat correctly and haven't made a complete arse of myself. Cheers.
=> Updated whittlesea_vic_gov_au to use OpenCities API

README.md, doc/ics/kreis_ploen_de.md, doc/ics/yaml/kreis_ploen_de.yaml
=> update kreis_ploen_de ics documentation

doc/source/uttlesford_gov_uk.md
they are not really relevant and will just get outdated
fixes  #2323
=> uttlesford_gov_uk MD: remove section on which waste types are returned

README.md
this hopefully stops people from opening source requests as enhancement or in the discussion section
=> README.md add note on how to request a new source

custom_components/waste_collection_schedule/waste_collection_schedule/source/fenland_gov_uk.py
=> fix_fenland_gov_uk failing if multiple collections at the same day

custom_components/waste_collection_schedule/waste_collection_schedule/source/c_trace_de.py, doc/source/c_trace_de.md
add a new a attribute "abfall" to select specific waste types. Currently all types would be collected. If the attribute is missing, all types will be collect.
=> Add new attribute "abfall"

custom_components/waste_collection_schedule/waste_collection_schedule/source/aha_region_de.py, doc/source/aha_region_de.md
=> fix aha_region_de + add ladeort argument

custom_components/waste_collection_schedule/waste_collection_schedule/source/rbwm_gov_uk.py, doc/source/rbwm_gov_uk.md
=> fix rbwm_gov_uk: requireds uprn AND Postcode now

custom_components/waste_collection_schedule/waste_collection_schedule/source/vivab_se.py
fixes #2386
extends fix #2389 which seem to work only with some addresses: tested first fix to work with `Storgatan 1, FALKENBERG`
=> vivab_se fix bug, where falkenberg address do not work, for real

custom_components/waste_collection_schedule/waste_collection_schedule/source/a_region_ch.py
=> fix a_region_ch failing if disstrict selection does ntot contain ':'

custom_components/waste_collection_schedule/waste_collection_schedule/source/wokingham_gov_uk.py, custom_components/waste_collection_schedule/waste_collection_schedule/wizard/wokingham_uk.py
Wokingham is changing from weekly collections of rubbish/recycling/food waste, and two weekly collections of garden waste, to rubbish and recycling being two weekly on alternate weeks, food waste staying weekly and garden waste remaining unchanged at two weekly.
These changes start from 12th August and the council have a new web page with the details - https://www.wokingham.gov.uk/rubbish-and-recycling/waste-collection/see-your-new-bin-collection-dates
This update moves the source and wizard over to the new pages.
**Note, this might be considered a breaking change as the property numbers returned from the council website are now different.**
This is working for me, I have the following config:
```yaml
waste_collection_schedule:
sources:
- name: wokingham_gov_uk
args:
postcode: …
```
=> Update Wokingham source and wizard.

custom_components/waste_collection_schedule/waste_collection_schedule/source/republicservices_com.py
=> fix republicservices_com

custom_components/waste_collection_schedule/waste_collection_schedule/source/ilrifiutologo_it.py
fixes freshly added source (#2432),
which would fail after the first succesful fetch as parameters got overwritten that should not have been overwritten
=> fix ilrifutologo_it

custom_components/waste_collection_schedule/waste_collection_schedule/source/bielefeld_de.py
=> fix bielefeld only getting results from next season

custom_components/waste_collection_schedule/waste_collection_schedule/source/muellmax_de.py
fixes #2468
but looks like not all services where affected as test case Rhein Sieg Kreis still worked
=> fix Muellmax_de not working: fixed by adding User-Agent

custom_components/waste_collection_schedule/sensor.py, custom_components/waste_collection_schedule/waste_collection_schedule/collection.py, custom_components/waste_collection_schedule/waste_collection_schedule/collection_aggregator.py, custom_components/waste_collection_schedule/wcs_coordinator.py
GUI sensors would ignore details_format after a restart as details_fomrat then is a string instead of a DetailsFromat enum
fixes #2472
fixes #2297
Also added some typehints to the senosrs
=> fixes GUI Senosr details_format ignored after HA restart

custom_components/waste_collection_schedule/waste_collection_schedule/source/ilrifiutologo_it.py
Calling directly the `API_URL_BACKEND` sometimes takes a few minutes causing a timeout error, but by requesting data through the `API_URL` this doesn't happen
=> fix ilrifiutologo_it request rate limit

custom_components/waste_collection_schedule/waste_collection_schedule/wizard/muellmax_de.py
=> fix muellmax wizard

custom_components/waste_collection_schedule/config_flow.py
=> config_flow: random fetch time offset now uses the Duration Selector

custom_components/waste_collection_schedule/waste_collection_schedule/source/aucklandcouncil_govt_nz.py
add User-Agent Header to request
fixes #2552
=> fix aucklandcouncil_govt_nz

README.md, custom_components/waste_collection_schedule/sources.json, custom_components/waste_collection_schedule/translations/en.json, custom_components/waste_collection_schedule/waste_collection_schedule/source/sicaapp_lu.py, doc/source/sicaapp_lu.md, info.md
=> add Sicaapp LU

custom_components/waste_collection_schedule/waste_collection_schedule/source/renfrewshire_gov_uk.py
Hello! 
I have attempted to update the code to handle locations in Renfrewshire that have multiple bin collections on 1 day (See below image)
I'm not fluent with Python yet, so this represents my best effort. I have tested the code and verified it works as far as `schedule` having the expected data.
=> Update renfrewshire_gov_uk.py to handle multiple bin collections on a single day

custom_components/waste_collection_schedule/sensor.py
=> improve error message if YAML sensor is configured but no Source

custom_components/waste_collection_schedule/config_flow.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/umweltverbaende_at.py
also fixed a bug where it would fail if the table is formatted wrong
Not shure why the table is formated like this but it is in one case
fixes #2599
=> Umweltverbaende.at show calendar as list input in GUI

custom_components/waste_collection_schedule/waste_collection_schedule/source/kirklees_gov_uk.py, doc/source/kirklees_gov_uk.md
=> fix Kirklees_gov_uk failing if multiple addresses are found

custom_components/waste_collection_schedule/manifest.json
Actually fixes problem addressed here: #2645, Which just changes the development dependencies
=> fix icalevents version 0.1.28 causing problems

custom_components/waste_collection_schedule/waste_collection_schedule/source/impactapps_com_au.py
=> Impactapps_au fix Blue Mountains + fix issue not being raised

custom_components/waste_collection_schedule/waste_collection_schedule/source/zakb_de.py
Am Herrschaftswald did previously work but Im Bangert not
fixes #2677
=> fix zakb_de not working fo some addresses with spaces in street name

custom_components/waste_collection_schedule/sources.json, custom_components/waste_collection_schedule/waste_collection_schedule/source/recyclecoach_com.py
The source now:
- Providees Default params for the GUI
- raises SourceArgumentNotFoundWithSuggestions for invalid streets. So the GUI suggests alternatives
=> improve recyclecaoch_com

custom_components/waste_collection_schedule/waste_collection_schedule/source/herefordshire_gov_uk.py
Change to the website meant it failed to get the dates.
=> Fixes herefordshire_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/wanneroo_wa_gov_au.py
fixes https://github.com/mampfes/hacs_waste_collection_schedule/issues/2602#issuecomment-2371716167
I did not notice that IntraMapsSession is not static but changes, it seemed to work fine when testing but I guess it stopped working after a fixed amount of time
The new solution now alos gets this value
=> fix Wanneroo_wa_gov_au

custom_components/waste_collection_schedule/translations/de.json, custom_components/waste_collection_schedule/translations/en.json, custom_components/waste_collection_schedule/translations/it.json, custom_components/waste_collection_schedule/waste_collection_schedule/source/okc_gov.py, doc/source/okc_gov.md
addresses https://github.com/mampfes/hacs_waste_collection_schedule/issues/2503#issuecomment-2351298787
=> okc_gov add option to use the offical url again

custom_components/waste_collection_schedule/waste_collection_schedule/source/elmbridge_gov_uk.py, doc/source/elmbridge_gov_uk.md
Fixes Elmbridge (https://github.com/mampfes/hacs_waste_collection_schedule/issues/1131#issuecomment-2344662720)
=> fix elmbridge_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/irenambiente_it.py
=> fix irenambiente_it for house_numbers with spaces

custom_components/waste_collection_schedule/waste_collection_schedule/source/stirling_uk.py
=> fix stirling_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/bir_no.py
also includes added icon as #2772
=> fix bir_no by removing the need for the additional dependency cssselect

custom_components/waste_collection_schedule/waste_collection_schedule/source/lincoln_gov_uk.py
fixes https://github.com/mampfes/hacs_waste_collection_schedule/issues/1246#issuecomment-2391361523
=> licoln_gov_uk use actual collection frequency to populate furute bin collections

doc/source/ilrifiutologo_it.md
=> ilrifiutologo_it fix documentaiton, showing wrong argument names

custom_components/waste_collection_schedule/translations/de.json, custom_components/waste_collection_schedule/translations/en.json, custom_components/waste_collection_schedule/translations/it.json, custom_components/waste_collection_schedule/waste_collection_schedule/source/fcc_group_eu.py, doc/source/fcc_group_eu.md
fixes https://github.com/mampfes/hacs_waste_collection_schedule/issues/2790#issuecomment-2401554710
=> fcc_group_eu support frequencies

custom_components/waste_collection_schedule/translations/de.json, custom_components/waste_collection_schedule/translations/en.json, custom_components/waste_collection_schedule/translations/it.json, doc/ics/abfall_kreis_kassel_de.md, doc/ics/yaml/abfall_kreis_kassel_de.yaml
=> update abfall_kreis_kassel.yaml to better explain link retreaval

custom_components/waste_collection_schedule/waste_collection_schedule/source/recyclecoach_com.py
=> fix recyclecaoch_com (changes to API paths)

custom_components/waste_collection_schedule/translations/de.json, custom_components/waste_collection_schedule/translations/en.json, custom_components/waste_collection_schedule/translations/it.json, custom_components/waste_collection_schedule/waste_collection_schedule/source/rbwm_gov_uk.py, doc/source/rbwm_gov_uk.md
Council website appears to have changed, now can go directly to property with UPRN in the URL and postcode no longer required
Fixes #2841
Issue was reproducible:
```
$ ./test_sources.py -s rbwm_gov_uk -l -i
Testing source rbwm_gov_uk ...
Windsor 1 failed: 'NoneType' object has no attribute 'startswith'
Windsor 2 failed: 'NoneType' object has no attribute 'startswith'
Maidenhead 1 failed: 'NoneType' object has no attribute 'startswith'
Maidenhead 2 failed: 'NoneType' object has no attribute 'startswith'
```
With changes:
```
$ ./test_sources.py -s rbwm_gov_uk -l -i
Testing source rbwm_gov_uk ...
found 10 entries for Windsor 1
2024-10-15 : Garden Waste [mdi:leaf]
2024-10-15 : Recycling [mdi:recycle]
2024-10-22 : Recycling [mdi:recycle]
2024-10-22 : Refuse [mdi:trash-can]
2024-10-29 : Garden …
```
=> Fix Windsor and Maidenhead source

custom_components/waste_collection_schedule/translations/de.json, custom_components/waste_collection_schedule/translations/en.json, custom_components/waste_collection_schedule/translations/it.json, custom_components/waste_collection_schedule/waste_collection_schedule/source/adur_worthing_gov_uk.py, doc/source/adur_worthing_gov_uk.md
Fixes #2852 
Source updated to include the option for a uprn arg (Test_003)
```
Testing source adur_worthing_gov_uk ...
found 9 entries for Test_001
2024-10-23 : Refuse [mdi:trash-can]
2024-11-06 : Refuse [mdi:trash-can]
2024-11-20 : Refuse [mdi:trash-can]
2024-10-16 : Recycling [mdi:recycle]
2024-10-30 : Recycling [mdi:recycle]
2024-11-13 : Recycling [mdi:recycle]
2024-10-16 : Garden [mdi:leaf]
2024-10-23 : Garden [mdi:leaf]
2024-10-30 : Garden [mdi:leaf]
found 9 entries for Test_002
2024-10-17 : Refuse [mdi:trash-can]
2024-10-31 : Refuse [mdi:trash-can]
2024-11-14 : Refuse [mdi:trash-can]
2024-10-24 : Recycling [mdi:recycle]
2024-11-07 : Recycling [mdi:recycle]
2024-11-21 : Recycling [mdi:recycle]
2024-10-17 : Garden [mdi:leaf]
2024-10-24 : Garden [mdi:leaf]
2024-10-31 : Garden …
```
=> Update: Adur- Worthing

custom_components/waste_collection_schedule/waste_collection_schedule/source/app_my_local_services_au.py
=> fix app_my_localca_services_au may fail for some addresses

custom_components/waste_collection_schedule/config_flow.py
=> Fix config_flow failing if title of Module is set to None (Probably only hvcgroep_nl)

custom_components/waste_collection_schedule/waste_collection_schedule/source/gojer_at.py
fixes https://github.com/mampfes/hacs_waste_collection_schedule/issues/2864#issuecomment-2424733131
=> fix gojer_at failing for some regions if multiple collections are at the same day

custom_components/waste_collection_schedule/translations/de.json, custom_components/waste_collection_schedule/translations/en.json, custom_components/waste_collection_schedule/translations/it.json, doc/ics/rhein_lahn_kreis_abfallwirtschaft_de.md, doc/ics/yaml/rhein_lahn_kreis_abfallwirtschaft_de.yaml
=> fix/improve ICS source documentation rhein_lahn_kreis

custom_components/waste_collection_schedule/translations/de.json, custom_components/waste_collection_schedule/translations/en.json, custom_components/waste_collection_schedule/translations/it.json, custom_components/waste_collection_schedule/waste_collection_schedule/source/data_umweltprofis_at.py, doc/source/data_umweltprofis_at.md
=> improve documenation and GUI param description/name

custom_components/waste_collection_schedule/waste_collection_schedule/source/yarra_ranges_vic_gov_au.py
Fixed:
- Test cases - Address structure has changed
- Div selection
Testcases:
```
Testing source yarra_ranges_vic_gov_au ...
found 3 entries for Petstock Lilydale
2024-11-08 : FOGO
2024-11-08 : Rubbish Collection
2024-11-15 : Recycling Collection
found 3 entries for Beechworth Bakery Healesville
2024-11-05 : FOGO
2024-11-12 : Rubbish Collection
2024-11-05 : Recycling Collection
```
=> fix [Bug]: Yarra Ranges Council Error #2974

custom_components/waste_collection_schedule/waste_collection_schedule/source/nottingham_city_gov_uk.py
Not sure exactly when proxy broke, but it's broken.
=> Resolve broken proxy for nottingham city and simplify json processing

custom_components/waste_collection_schedule/translations/de.json, custom_components/waste_collection_schedule/translations/en.json, custom_components/waste_collection_schedule/translations/it.json, doc/ics/eva_abfallentsorgung_de.md, doc/ics/yaml/eva_abfallentsorgung_de.yaml
=> update ICS docs for eva_abfallentsorgung_de

custom_components/waste_collection_schedule/config_flow.py
This is PR tackles the blocking call to load the sources.json in the config_flow initialization. I moved the the _sources and method creation logic out of __init__. 
I'm not sure if this is the best approach. Whenever a new process entry method (other then new, reconfigure) is created, `_async_setup_sources` needs to be called...
Fixes: #3031
=> Fix: Blocking call to open sources.json in config_flow initialization

custom_components/waste_collection_schedule/translations/de.json, custom_components/waste_collection_schedule/waste_collection_schedule/source/landkreis_rhoen_grabfeld.py, doc/source/landkreis_rhoen_grabfeld.md
Fixes #3006 by switching to the new API and updates related documentation.
=> fix source landkreis_rhoen_grabfeld

custom_components/waste_collection_schedule/translations/en.json, custom_components/waste_collection_schedule/waste_collection_schedule/source/hastings_gov_uk.py, doc/source/hastings_gov_uk.md
fixes https://github.com/mampfes/hacs_waste_collection_schedule/issues/2795#issuecomment-2481505079
=> fixed hasting_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/awg_de.py
=> awg_de compleatly disable ssl verification

custom_components/waste_collection_schedule/waste_collection_schedule/source/landkreis_kusel_de.py
Fixes: #3084 
Error: Site structure, ICS API url and bin types changed
Test:
```
Testing source landkreis_kusel_de ...
found 9 entries for Adenbach
2024-11-28 : Bioabfall [mdi:leaf]
2024-12-05 : LVP-Abfälle [mdi:recycle]
2024-12-05 : Glas [mdi:bottle-soda]
2024-12-12 : Bioabfall [mdi:leaf]
2024-12-12 : Umweltmobil [mdi:dump-truck]
2024-12-12 : Restmüll [mdi:trash-can]
2024-12-19 : LVP-Abfälle [mdi:recycle]
2024-12-19 : Papier [mdi:package-variant]
2024-12-27 : Bioabfall [mdi:leaf]
found 11 entries for St. Julian - Eschenau
2024-11-26 : Bioabfall [mdi:leaf]
2024-11-26 : Restmüll [mdi:trash-can]
2024-12-03 : LVP-Abfälle [mdi:recycle]
2024-12-03 : Papier [mdi:package-variant]
2024-12-10 : Bioabfall [mdi:leaf]
2024-12-17 : Glas [mdi:bottle-soda]
2024-12-17 : LVP-Abfälle [mdi:recycle] …
```
=> Fix: Landkreis Kusel_de - Site structure changed

custom_components/waste_collection_schedule/waste_collection_schedule/source/kingston_gov_uk.py
Fixes: https://github.com/mampfes/hacs_waste_collection_schedule/issues/3078
=> fix kingston uk waste collection ssl error and new date format

custom_components/waste_collection_schedule/waste_collection_schedule/source/crawley_gov_uk.py
=> fix crawley_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/data_umweltprofis_at.py
=> umweltprofis_at imporve error message on connection_error

custom_components/waste_collection_schedule/waste_collection_schedule/source/tekniskaverken_se.py
fixes #3054 + improve error message
=> fix tekniskaverken_se + imporve error message

README.md, custom_components/waste_collection_schedule/translations/de.json, custom_components/waste_collection_schedule/translations/en.json, custom_components/waste_collection_schedule/translations/it.json, doc/ics/entsorgung_regional_de.md, doc/ics/yaml/entsorgung_regional_de.yaml, doc/source/ics.md
abfallwirtschaft-enzkreis.de is the new domain
=> Fixed wrong URL for abfallwirtschaft-enzkreis.de

custom_components/waste_collection_schedule/waste_collection_schedule/source/bcp_gov_uk.py
=> bcp_gov_uk fix source returning duplicates

custom_components/waste_collection_schedule/translations/de.json, custom_components/waste_collection_schedule/translations/en.json, custom_components/waste_collection_schedule/translations/it.json, doc/ics/alba_bs_de.md, doc/ics/yaml/alba_bs_de.yaml
=> improve alba_bs_de ICS documentation

custom_components/waste_collection_schedule/waste_collection_schedule/source/rushcliffe_gov_uk.py
Rushcliffe appear to have changed how their website works. I believe that this pull request fixes #3124.
=> Fix Rushcliffe, UK (#3124)

custom_components/waste_collection_schedule/waste_collection_schedule/source/lrasha_de.py
The API URL for lrasha_de has changed. I changed it to the new one.
=> Fix lrasha_de API URL

custom_components/waste_collection_schedule/waste_collection_schedule/source/egn_abfallkalender_de.py
fixes #3255
Only failed for a small amount of addresses where they don't provide a Bin color for the collection type
=> fix egn_abfallkalender_de failing for some addresses

custom_components/waste_collection_schedule/waste_collection_schedule/source/dundeecity_gov_uk.py
Fixes #3130 
_%M_ was being used to process dates. Should have been  _%m_
=> fixes duplicate dates issue

custom_components/waste_collection_schedule/waste_collection_schedule/source/recycleapp_be.py
should fix https://github.com/mampfes/hacs_waste_collection_schedule/issues/1716#issuecomment-2563021955
=> fix recycleapp_be only trying one zip-code id even if one zipcode has multiple ids

doc/source/landkreis_verden_de.md
=> landkreis_verden_de: md fix link

custom_components/waste_collection_schedule/waste_collection_schedule/source/lewisham_gov_uk.py
by adding User-Agent header and using `\r\n` instead of just `\n` in request data
fixes #3079
=> fix lewisham_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_es_de.py, doc/ics/abfall_kreis_kassel_de.md, doc/ics/yaml/abfall_kreis_kassel_de.yaml
=> improve error handling for awb_es_de

custom_components/waste_collection_schedule/waste_collection_schedule/source/liverpool_gov_uk.py
The line to push dates into the next year wasn't working, so I've rewritten it
Tested on my local system and all working well.
=> Fix liverpool council dates in the next year

custom_components/waste_collection_schedule/waste_collection_schedule/source/merton_gov_uk.py
Fixes #3333 
Updated to deal with inconsistent website date formatting.
=> Fix: merton_gov-uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/cederbaum_de.py
The provider made changes to the homepage / data source. These changes should fix that.
=> Fix source cederbaum_de due to homepage/data changes

custom_components/waste_collection_schedule/waste_collection_schedule/source/walsall_gov_uk.py
Fixes #3366 
soup.findAll updated to reflect website changes
```bash
Testing source walsall_gov_uk ...
found 6 entries for test001
2024-12-23 : GREEN [mdi:recycle]
2025-01-06 : GREEN [mdi:recycle]
2025-01-20 : GREEN [mdi:recycle]
2024-12-23 : GREY [mdi:trash-can]
2025-01-06 : GREY [mdi:trash-can]
2025-01-20 : GREY [mdi:trash-can]
found 6 entries for test002
2025-01-04 : GREEN [mdi:recycle]
2025-01-15 : GREEN [mdi:recycle]
2025-01-29 : GREEN [mdi:recycle]
2025-01-04 : GREY [mdi:trash-can]
2025-01-15 : GREY [mdi:trash-can]
2025-01-29 : GREY [mdi:trash-can]
found 6 entries for test003
2024-12-23 : GREEN [mdi:recycle]
2025-01-06 : GREEN [mdi:recycle]
2025-01-20 : GREEN [mdi:recycle]
2024-12-23 : GREY [mdi:trash-can]
2025-01-06 : GREY [mdi:trash-can]
2025-01-20 : GREY [mdi:trash-can]
found 6 …
```
=> Fix: walsall_gov_uk

doc/source/montreal_ca.md
Change example config from address to sector
=> Typo on example of montreal_ca.md

custom_components/waste_collection_schedule/waste_collection_schedule/source/umweltverbaende_at.py
=> fix umweltverbaende_at not working for moedling and maybe others

custom_components/waste_collection_schedule/translations/de.json, custom_components/waste_collection_schedule/translations/en.json, custom_components/waste_collection_schedule/translations/fr.json, custom_components/waste_collection_schedule/translations/it.json, doc/ics/tbr_reutlingen_de.md, doc/ics/yaml/tbr_reutlingen_de.yaml
Adjusted documentation and used new url
=> update tbr_reutlingen_de to support new source url used for 2025

custom_components/waste_collection_schedule/const.py, custom_components/waste_collection_schedule/init_ui.py, custom_components/waste_collection_schedule/translations/de.json, custom_components/waste_collection_schedule/translations/en.json, custom_components/waste_collection_schedule/translations/fr.json, custom_components/waste_collection_schedule/translations/it.json, custom_components/waste_collection_schedule/waste_collection_schedule/source/was_wolfsburg_de.py, doc/source/was_wolfsburg_de.md
WAS Wolfsburg updated their website.
- Data can be retrieved via JSON
- City/District is no longer supported
- Street is mandatory now
=> Update WAS Wolfsburg

custom_components/waste_collection_schedule/translations/de.json, custom_components/waste_collection_schedule/translations/en.json, custom_components/waste_collection_schedule/translations/fr.json, custom_components/waste_collection_schedule/translations/it.json, custom_components/waste_collection_schedule/waste_collection_schedule/source/cheshire_east_gov_uk.py
Fixes https://github.com/mampfes/hacs_waste_collection_schedule/issues/3714
Seems some HA installs are having issues with certification verification
=> fix: Cheshire East Certificate Verification errors

doc/source/apps_imactivate_com.md
=> Typos: Correct Leads to Leeds

custom_components/waste_collection_schedule/waste_collection_schedule/source/torridge_gov_uk.py
Somehow I managed to break the code in #3816 between the tests passing and committing the source. Not sure how that happened, but here's the fix. Sorry and thanks 😄
=> fix(source/torridge): fix date parts unpacking

custom_components/waste_collection_schedule/waste_collection_schedule/source/oxford_gov_uk.py
Fixes #3867 
Website has changed, now shows the next 2 dates for each collection type. 
Sometimes the two dates shows are the same so added a check to make sure collection dates are unique. (May not be needed?)
=> Fix: Oxford

custom_components/waste_collection_schedule/waste_collection_schedule/source/montreal_ca.py
Fixing schedule when pick up is every other week.
=> [montreal_ca] Fix issue #3879

custom_components/waste_collection_schedule/config_flow.py, custom_components/waste_collection_schedule/waste_collection_schedule/source/umweltverbaende_at.py
fixes https://github.com/mampfes/hacs_waste_collection_schedule/pull/3883#issuecomment-2714046606
=> umweltverbaende_at improve error message for GVA Baden if missing calendar

custom_components/waste_collection_schedule/waste_collection_schedule/source/north_kesteven_org_uk.py
Fixes #3610 
Fixes #3538
```bash
Testing source north_kesteven_org_uk ...
found 1 entries for Test_001
2025-03-17 : BLACK [mdi:trash-can]
found 1 entries for Test_002
2025-03-19 : BLACK [mdi:trash-can]
found 1 entries for Test_003
2025-03-21 : BLACK [mdi:trash-can]
found 1 entries for Test_004
2025-03-17 : BLACK [mdi:trash-can]
```
=> Fix: North Kesteven, UK

custom_components/waste_collection_schedule/waste_collection_schedule/source/frankston_vic_gov_au.py
Fixes #3929
```bash
Testing source frankston_vic_gov_au ...
found 9 entries for 45r Wedge Rd
2025-03-24 : Rubbish [mdi:trash-can]
2025-03-31 : Rubbish [mdi:trash-can]
2025-04-07 : Rubbish [mdi:trash-can]
2025-04-14 : Rubbish [mdi:trash-can]
2025-03-24 : Recycling [mdi:recycle]
2025-04-07 : Recycling [mdi:recycle]
2025-03-31 : Green Waste [mdi:leaf]
2025-04-14 : Green Waste [mdi:leaf]
2025-04-14 : Glass [mdl:glass-fragile]
found 9 entries for 300 Wedge Rd
2025-03-24 : Rubbish [mdi:trash-can]
2025-03-31 : Rubbish [mdi:trash-can]
2025-04-07 : Rubbish [mdi:trash-can]
2025-04-14 : Rubbish [mdi:trash-can]
2025-03-31 : Recycling [mdi:recycle]
2025-04-14 : Recycling [mdi:recycle]
2025-03-24 : Green Waste [mdi:leaf]
2025-04-07 : Green Waste [mdi:leaf]
2025-03-24 : Glass [mdl:glass-fragile]
found 9 …
```
=> Fix: Frankston, VIC, AU

custom_components/waste_collection_schedule/waste_collection_schedule/source/bexley_gov_uk.py, doc/source/bexley_gov_uk.md
Updated bexley.gov.uk source,  Fixes #3920,
=> Fix: Bexley, UK

custom_components/waste_collection_schedule/waste_collection_schedule/source/bracknell_forest_gov_uk.py
=> Fix: Bracknell Forest source not working with house names

README.md, custom_components/waste_collection_schedule/sources.json, custom_components/waste_collection_schedule/waste_collection_schedule/source/wangaratta_vic_gov_au.py, doc/source/wangaratta_vic_gov_au.md
=> Add Rural City of Wangaratta VIC Australia

custom_components/waste_collection_schedule/waste_collection_schedule/source/merri_bek_vic_gov_au.py
Fixes #4003
```bash
Testing source merri_bek_vic_gov_au ...
found 292 entries for Monday
found 292 entries for Tuesday
found 318 entries for Wednesday
found 305 entries for Thursday
found 316 entries for Friday
found 291 entries for Glass Drop Off
```
=> Fix: Merri-bek, AUS

doc/source/hornsby_nsw_gov_au.md
Updated url in .md file as mentioned in #4029
=> Update: Hornsby, NSW

custom_components/waste_collection_schedule/waste_collection_schedule/source/armadale_wa_gov_au.py
Fixes #4033 
```bash
Testing source armadale_wa_gov_au ...
found 78 entries for 23 Sexty St, ARMADALE
found 78 entries for 270 Skeet Rd, HARRISDALE
```
=> Fix: Armadale, AUS

custom_components/waste_collection_schedule/waste_collection_schedule/source/iapp_itouchvision_com.py
Fixes #4059
Removes superfluous text causing sensors to fail.
=> Fix: Buckinghamshire, UK

custom_components/waste_collection_schedule/waste_collection_schedule/source/adur_worthing_gov_uk.py
Fixes #4086 
```bash
Testing source adur_worthing_gov_uk ...
2025-05-16 : Refuse [mdi:trash-can]
2025-05-09 : Recycling [mdi:recycle]
2025-05-09 : Garden [mdi:leaf]
2025-05-09 : Refuse [mdi:trash-can]
2025-05-07 : Recycling [mdi:recycle]
2025-05-07 : Garden [mdi:leaf]
2025-05-19 : Refuse [mdi:trash-can]
2025-05-12 : Recycling [mdi:recycle]
2025-05-12 : Garden [mdi:leaf]
```
=> Fix: Adur & Worthing, UK

custom_components/waste_collection_schedule/waste_collection_schedule/source/east_renfrewshire_gov_uk.py
=> Fix East Renfrewshire source: update to HTML table parsing

custom_components/waste_collection_schedule/waste_collection_schedule/source/ccc_govt_nz.py
- Remove use of get_legacy_session as request seem to work fine without it
- Add icon map
- Add logging
- Create a session to grab visid_incap and incap_ses cookies, along with setting the user-agent to not get blocked by the WAF
Fixes https://github.com/mampfes/hacs_waste_collection_schedule/issues/3898
=> Fix WAF blocking overrides fetch

custom_components/waste_collection_schedule/waste_collection_schedule/source/canterbury_gov_uk.py
PROBLEM
Related to #3864
Both the script and curls that used basic headers got a 403
```
ubuntu@ns1:~$ curl -X POST "https://zbr7r13ke2.execute-api.eu-west-2.amazonaws.com/Beta/get-bin-dates" \
-H "Content-Type: application/json" \
-d '{"uprn": "10096027984", "usrn": "5605991"}'
{"message":"Forbidden"}
```
I got the expected 403.
FIX
I've managed to get this to work.
```
ubuntu@ns1:~$ curl -s -X POST "https://zbr7r13ke2.execute-api.eu-west-2.amazonaws.com/Beta/get-bin-dates" \
-H "Content-Type: application/json" \
-H "Origin: https://www.canterbury.gov.uk" \
-H "Referer: https://www.canterbury.gov.uk/" \
-H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0" \
-H "Accept: */*" \
--data '{"uprn": …
```
=> Add Canterbury City Council headers to allow POST

custom_components/waste_collection_schedule/waste_collection_schedule/source/westsuffolk_gov_uk.py
Fixes #4124 
```bash
Testing source westsuffolk_gov_uk ...
found 2 entries for Flat, The Flying Shuttle, Three Counties Way, Withersfield, CB9 7FB
2025-05-23 : Black bin [mdi:trash-can]
2025-05-16 : Blue bin [mdi:recycle]
found 3 entries for Haere Mai, The Street, Troston, IP31 1EW
2025-05-13 : Black bin [mdi:trash-can]
2025-05-20 : Blue bin [mdi:recycle]
2025-05-21 : Brown bin [mdi:leaf]
```
=> Fix: West Suffolk, UK

custom_components/waste_collection_schedule/waste_collection_schedule/source/lumire_se.py
=> Fix lumire

custom_components/waste_collection_schedule/waste_collection_schedule/source/nvaa_se.py
=> Add support for week ranges and missing dates into nvaa_se

custom_components/waste_collection_schedule/waste_collection_schedule/source/eastriding_gov_uk.py
Fixes #4163 
```bash
Testing source eastriding_gov_uk ...
2025-05-28 : Blue Bin [mdi:recycle]
2025-06-02 : Green Bin [mdi:trash-can]
2025-05-30 : Brown Bin [mdi:leaf]
found 2 entries for Test_002
2025-05-27 : Blue Bin [mdi:recycle]
2025-05-30 : Brown Bin [mdi:leaf]
2025-05-28 : Blue Bin [mdi:recycle]
2025-06-02 : Green Bin [mdi:trash-can]
2025-06-03 : Brown Bin [mdi:leaf]
found 3 entries for Test_004
2025-05-28 : Blue Bin [mdi:recycle]
2025-06-02 : Green Bin [mdi:trash-can]
2025-05-30 : Brown Bin [mdi:leaf]
```
=> Fix: East Riding, UK

custom_components/waste_collection_schedule/waste_collection_schedule/source/knowsley_gov_uk.py
Fixes #4136
```bash
Testing source knowsley_gov_uk ...
found 3 entries for L364AR 000040082756
2025-05-27 : Grey [mdi:recycle]
2025-06-03 : Maroon [mdi:trash-can]
2025-06-03 : Blue [mdi:leaf]
found 3 entries for L34 0HZ, 40029195
2025-05-28 : Grey [mdi:recycle]
2025-06-04 : Maroon [mdi:trash-can]
2025-05-28 : Blue [mdi:leaf]
```
=> Fix: Knowsley, UK

custom_components/waste_collection_schedule/waste_collection_schedule/source/adur_worthing_gov_uk.py
=> adur_worthing_gov_uk change garden waste Type to be consistent with old configs

custom_components/waste_collection_schedule/waste_collection_schedule/source/hvcgroep_nl.py
Updated the URL of the Cyclus service in the hvcgroep_nl service.
Fixes bug report #4252
=> Fix: hvcgroep_nl service Cyclus #4252

doc/online.md
Update list of you tube videos mentioning WCS.
=> Update:  online.md

custom_components/waste_collection_schedule/waste_collection_schedule/source/lichfielddc_gov_uk.py
Add User-Agent header to avoid 403 Forbidden response.
=> Fix: Lichfield DC now needs a User-Agent header

custom_components/waste_collection_schedule/waste_collection_schedule/source/swindon_gov_uk.py
Added User Agent to avoid bot detection for the Swindon Source. 
Issue: #4303 4303
=> Swindon: Passing user-agent to bypass detection. Issue #4303

custom_components/waste_collection_schedule/waste_collection_schedule/source/centralbedfordshire_gov_uk.py
This should solve the:
The source returned an invalid response: "403 Client Error: Forbidden for url: https://www.centralbedfordshire.gov.uk/info/163/bins_and_waste_collections_-_check_bin_collection_days". Please check the provided arguments and try again.
To avoid bot detection I have added realistic browser headers.
=> Added realistic browser headers to avoid bot detection for Central Bedfordshire Council

custom_components/waste_collection_schedule/waste_collection_schedule/source/stoke_gov_uk.py
Add user-agent for Stoke-on-Trent source. See #4300
=> Stoke: Passing user-agent to bypass detection. Issue #4300

custom_components/waste_collection_schedule/waste_collection_schedule/source/royalgreenwich_gov_uk.py
Update the URLs to the ones from Browser dev tools
=> Fix Greenwich (UK) URLs

custom_components/waste_collection_schedule/waste_collection_schedule/source/herefordshire_gov_uk.py
Fixes #4354 
```bash
Testing source herefordshire_gov_uk ...
found 2 entries for houseNumber
2025-07-16 : General rubbish [mdi:trash-can]
2025-07-09 : Recycling [mdi:recycle]
```
=> Fix: Herefordshire, UK

custom_components/waste_collection_schedule/waste_collection_schedule/source/tauranga_govt_nz.py
Add additional form data required by the recent changes to the council website.
Tests post change:
```
Testing source tauranga_govt_nz ...
found 6 entries for 121 Castlewold Drive
found 6 entries for 70 Santa Monica Drive
found 5 entries for 21 Wells Avenue
```
=> Fix: Tauranga, NZ

custom_components/waste_collection_schedule/waste_collection_schedule/source/afvalstoffendienst_nl.py
Fixes #4403 
adds `verify=False` to requests to fix SSL error.
```bash
Testing source afvalstoffendienst_nl ...
found 64 entries for s-hertogenbosch, 5151MS 37 
found 52 entries for heuden, 5256EJ, 44C
found 80 entries for vught, 5262 CJ 18
found 78 entries for Oisterwijk 5062 ER 13
found 78 entries for Altena 4286 AL 1
found 79 entries for bernheze
```
=> Fix: Afvalstoffendienst, NL

custom_components/waste_collection_schedule/waste_collection_schedule/source/wiltshire_gov_uk.py
Fixes #4425 
```bash
Testing source wiltshire_gov_uk ...
found 31 entries for standard_uprn
2025-07-04 : Household waste [mdi:trash-can]
2025-07-18 : Household waste [mdi:trash-can]
2025-07-10 : Mixed dry recycling (blue lidded bin) and glass (black box or basket) [mdi:recycle]
2025-07-24 : Mixed dry recycling (blue lidded bin) and glass (black box or basket) [mdi:recycle]
2025-08-01 : Household waste [mdi:trash-can]
2025-08-15 : Household waste [mdi:trash-can]
2025-08-29 : Household waste [mdi:trash-can]
2025-08-07 : Mixed dry recycling (blue lidded bin) and glass (black box or basket) [mdi:recycle]
2025-08-21 : Mixed dry recycling (blue lidded bin) and glass (black box or basket) [mdi:recycle]
2025-09-12 : Household waste [mdi:trash-can]
2025-09-26 : Household waste [mdi:trash-can] …
```
=> Fix: Wiltshire, UK

custom_components/waste_collection_schedule/waste_collection_schedule/source/tbv_velbert_de.py
=> Fix: TBV Velbert, DE

custom_components/waste_collection_schedule/waste_collection_schedule/source/eastherts_gov_uk.py
Fixes #4474
url, api, results format, and waste names have all changed as a result of East Herts moving to a new pattern of waste collections.
```bash
Testing source eastherts_gov_uk ...
Used postcode to find an approximate uprn (10023089734). Update config with property uprn for more accurate results.
found 20 entries for Example
2025-07-25 : Refuse [mdi:trash-can]
2025-08-01 : Mixed Recycling [mdi:recycle]
2025-08-01 : Paper [mdi:newspaper]
2025-08-08 : Paper and Card [mdi:newspaper]
2025-08-08 : Food Waste [mdi:food]
2025-08-15 : Refuse [mdi:trash-can]
2025-08-15 : Food Waste [mdi:food]
2025-08-22 : Mixed Recycling [mdi:recycle]
2025-08-22 : Food Waste [mdi:food]
2025-08-29 : Paper and Card [mdi:newspaper]
2025-08-29 : Food Waste [mdi:food]
2025-09-05 : Food Waste [mdi:food]
2025-09-12 …
```
=> Fix: East Herts, UK

custom_components/waste_collection_schedule/waste_collection_schedule/source/horsham_gov_uk.py
Fixes #4447 
Forces connection to use TLSv1.2 & AES256-SHA256 to match Horsham's server to avoid connection reset error.
```bash
Testing source horsham_gov_uk ...
Forcing requests to use legacy TLSv1.2 & AES256-SHA256 to match horsham.gov.uk website
found 29 entries for Blackthorn Avenue - number
2025-07-23 : Blue-Top Bin for Recycling [mdi:recycle]
2025-07-23 : Brown-Top Bin for Garden Waste [mdi:leaf]
2025-07-30 : Refuse Bin for Non-Recycling [mdi:trash-can]
2025-08-06 : Blue-Top Bin for Recycling [mdi:recycle]
2025-08-06 : Brown-Top Bin for Garden Waste [mdi:leaf]
2025-08-13 : Refuse Bin for Non-Recycling [mdi:trash-can]
2025-08-20 : Blue-Top Bin for Recycling [mdi:recycle]
2025-08-20 : Brown-Top Bin for Garden Waste [mdi:leaf]
2025-08-27 : Refuse Bin for Non-Recycling [mdi:trash-can] …
```
=> Fix: Horsham, UK

custom_components/waste_collection_schedule/waste_collection_schedule/source/darlington_gov_uk.py, doc/source/darlington_gov_uk.md
Fixes: #4512
Changed url to new format:
Testing source darlington_gov_uk ...
found 72 entries for 010013315817
2025-01-08 : Recycle [mdi:recycle]
2025-01-22 : Recycle [mdi:recycle]
2025-02-05 : Recycle [mdi:recycle]
2025-02-19 : Recycle [mdi:recycle]
2025-03-05 : Recycle [mdi:recycle]
2025-03-19 : Recycle [mdi:recycle]
2025-04-01 : Recycle [mdi:recycle]
2025-04-15 : Recycle [mdi:recycle]
2025-04-29 : Recycle [mdi:recycle]
2025-05-13 : Recycle [mdi:recycle]
2025-05-27 : Recycle [mdi:recycle]
2025-06-10 : Recycle [mdi:recycle]
2025-06-24 : Recycle [mdi:recycle]
2025-07-08 : Recycle [mdi:recycle]
2025-07-22 : Recycle [mdi:recycle]
2025-08-05 : Recycle [mdi:recycle]
2025-08-19 : Recycle [mdi:recycle]
2025-09-02 : Recycle [mdi:recycle]
2025-09-16 : Recycle [mdi:recycle]
2025-09-30 : Recycle …
=> Fix for darlington_gov_uk

custom_components/waste_collection_schedule/waste_collection_schedule/source/southglos_gov_uk.py
Fixes #4537 
updated api url, adapted for json response
```bash
Testing source southglos_gov_uk ...
2025-08-19 : GARDEN WASTE [mdi:leaf]
2025-08-13 : RECYCLING [mdi:recycle]
2025-08-20 : BLACK BIN [mdi:trash-can]
2025-08-13 : FOOD BIN [mdi:food]
2025-08-13 : RECYCLING [mdi:recycle]
2025-08-13 : FOOD BIN [mdi:food]
2025-08-20 : BLACK BIN [mdi:trash-can]
```
=> Fix: South Glos, UK

custom_components/waste_collection_schedule/waste_collection_schedule/source/cardinia_vic_gov_au.py
Fixes issues surrounding invalid magicKey parameters and improves the reliability of address lookup
=> Dynamically retrieve magicKey parameter for cardinia_vic_gov_au source

custom_components/waste_collection_schedule/waste_collection_schedule/source/renoweb_dk.py
It seems like Renoweb has changed their APIs to require authencation for some API endpoints. This PR adds a bit of error handling to have Home Assistant show a proper message.
Before:
```
$ ./custom_components/waste_collection_schedule/waste_collection_schedule/test/test_sources.py -s renoweb_dk 
Testing source renoweb_dk ...
test_01 failed: 'list'
test_02 failed: 'list'
test_03 failed: 'list'
test_04 failed: 'list'
```
With this PR:
```
$ ./custom_components/waste_collection_schedule/waste_collection_schedule/test/test_sources.py -s renoweb_dk 
Testing source renoweb_dk ...
Source.fetch(): access denied; data={'status': {'id': 3, 'status': 'AccessDenied', 'msg': 'Metoden GetAffaldsplanMateriel_mitAffald kan ikke tilgås med de nuværende rettigheder.'}}
test_01 failed: Access denied: …
```
=> [#4084] improve renoweb_dk error handling

custom_components/waste_collection_schedule/waste_collection_schedule/source/frankenberg_de.py
If a street is selected, then the filter shall be applied to the iCal generator
=> Add street filter for Frankenberg DE
